### ISSUE TITLE
Crash on clicking a rst widget

### ISSUE THREAD

**Issue by tony** [kivy/kivy-designer#106]
```python
[INFO              ] [Logger      ] Record log in /home/tony/.kivy/logs/kivy_15-07-30_5.txt
[INFO              ] [Kivy        ] v1.9.0
[INFO              ] [Python      ] v2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2]
[INFO              ] [Factory     ] 173 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
[INFO              ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[INFO              ] [GL          ] OpenGL version <3.0 Mesa 10.5.2>
[INFO              ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO              ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Ivybridge Mobile >
[INFO              ] [GL          ] OpenGL parsed version: 3, 0
[INFO              ] [GL          ] Shading version <1.30>
[INFO              ] [GL          ] Texture max size <8192>
[INFO              ] [GL          ] Texture max units <16>
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [Text        ] Provider: pygame
[INFO              ] [Clipboard   ] Provider: pygame(['clipboard_dbusklipper', 'clipboard_gtk3', 'clipboard_xsel'] ignored)
[INFO              ] [OSC         ] using <multiprocessing> for socket
[INFO              ] [Base        ] Start application main loop
[INFO              ] [GL          ] NPOT texture support is available
[INFO              ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "main.py", line 3, in <module>
     DesignerApp().run()
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/app.py", line 824, in run
     runTouchApp()
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 398, in mainloop
     self._mainloop()
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 285, in _mainloop
     EventLoop.idle()
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/base.py", line 330, in idle
     self.dispatch_input()
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/base.py", line 315, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/base.py", line 221, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 904, in on_motion
     self.dispatch('on_touch_down', me)
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 920, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/home/tony/study/kivy/kivy-designer/designer/app.py", line 403, in on_touch_down
     return super(FloatLayout, self).on_touch_down(touch)
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/uix/widget.py", line 382, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/uix/widget.py", line 382, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/uix/widget.py", line 382, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/uix/widget.py", line 382, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/home/tony/study/kivy/kivy-designer/designer/ui_creator.py", line 97, in on_touch_down
     return super(UICreator, self).on_touch_down(*args)
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/uix/widget.py", line 382, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/uix/widget.py", line 382, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/uix/widget.py", line 382, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/home/tony/study/kivy/kivy-designer/designer/playground.py", line 985, in on_touch_down
     App.get_running_app().focus_widget(target)
   File "/home/tony/study/kivy/kivy-designer/designer/app.py", line 1391, in focus_widget
     self.widget_focused = widget
   File "kivy/properties.pyx", line 397, in kivy.properties.Property.__set__ (kivy/properties.c:4680)
   File "kivy/properties.pyx", line 429, in kivy.properties.Property.set (kivy/properties.c:5203)
   File "kivy/properties.pyx", line 484, in kivy.properties.Property.dispatch (kivy/properties.c:5852)
   File "kivy/_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (kivy/_event.c:12154)
   File "kivy/_event.pyx", line 1074, in kivy._event.EventObservers._dispatch (kivy/_event.c:11451)
   File "kivy/_event.pyx", line 716, in kivy._event.EventDispatcher.__proxy_setter (kivy/_event.c:7605)
   File "kivy/properties.pyx", line 429, in kivy.properties.Property.set (kivy/properties.c:5203)
   File "kivy/properties.pyx", line 484, in kivy.properties.Property.dispatch (kivy/properties.c:5852)
   File "kivy/_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (kivy/_event.c:12154)
   File "kivy/_event.pyx", line 1074, in kivy._event.EventObservers._dispatch (kivy/_event.c:11451)
   File "/home/tony/study/kivy/kivy-designer/designer/propertyviewer.py", line 180, in on_widget
     self.discover(value)
   File "/home/tony/study/kivy/kivy-designer/designer/propertyviewer.py", line 200, in discover
     ip = self.build_for(prop)
   File "/home/tony/study/kivy/kivy-designer/designer/propertyviewer.py", line 240, in build_for
     kv_code_input=self.kv_code_input)
   File "/home/tony/study/kivy/kivy-designer/designer/propertyviewer.py", line 112, in __init__
     Spinner.__init__(self, values=prop.options, **kwargs)
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/uix/spinner.py", line 108, in __init__
     super(Spinner, self).__init__(**kwargs)
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/uix/behaviors.py", line 105, in __init__
     super(ButtonBehavior, self).__init__(**kwargs)
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/uix/label.py", line 187, in __init__
     super(Label, self).__init__(**kwargs)
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/uix/widget.py", line 271, in __init__
     Builder.apply(self)
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/lang.py", line 1872, in apply
     self._apply_rule(widget, rule, rule)
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/lang.py", line 2018, in _apply_rule
     e), cause=tb)
 kivy.lang.BuilderException: Parser: File "/home/tony/study/kivy/kivy-designer/designer/designer.kv", line 564:
 ...
     562:
     563:<PropertyBase>:
 >>  564:    propvalue: getattr(self.propwidget, self.propname)
     565:    padding: '6pt', '6pt'
     566:
 ...
 ValueError: PropertyOptions.text accept only str
   File "/home/tony/.pyenv/versions/kivy/local/lib/python2.7/site-packages/kivy/lang.py", line 2012, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 22, in kivy.weakproxy.WeakProxy.__setattr__ (kivy/weakproxy.c:1189)
   File "kivy/properties.pyx", line 397, in kivy.properties.Property.__set__ (kivy/properties.c:4680)
   File "kivy/properties.pyx", line 429, in kivy.properties.Property.set (kivy/properties.c:5203)
   File "kivy/properties.pyx", line 484, in kivy.properties.Property.dispatch (kivy/properties.c:5852)
   File "kivy/_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (kivy/_event.c:12154)
   File "kivy/_event.pyx", line 1074, in kivy._event.EventObservers._dispatch (kivy/_event.c:11451)
   File "/home/tony/study/kivy/kivy-designer/designer/propertyviewer.py", line 117, in on_propvalue
     self.text = self.propvalue
   File "kivy/properties.pyx", line 397, in kivy.properties.Property.__set__ (kivy/properties.c:4680)
   File "kivy/properties.pyx", line 426, in kivy.properties.Property.set (kivy/properties.c:5160)
```

To recreate:

kivy 1.9.0

Launch kivy-designer @ fc24d92e2e5d8ff8a03ae590334204133e1977be (Thu Jun 25 00:02:05 2015 +0300)

Load https://github.com/kivy/kivy/blob/1.9.0/examples/RST_Editor/main.py

Click an rst editor widget.

**Comment by Squirrel8** [comment]
It happens to me too.
When I insert the line `from kivy.uix.rst import RstDocument` (without using rst text in any other line) the mobile app crashes even though it works perfectly on pc.

Have you found the solution?

**Comment by aron-bordin** [comment]
Hi
It's being fixed in this PR: https://github.com/kivy/kivy-designer/pull/173 the code that fixes this bug is not yet in the pr. I'll try to push it soon

**Comment by aron-bordin** [comment]
Hi @tony, thx for the report. Bug is fixed in master.
