### ISSUE TITLE
Crash when viewing buildozer.spec in Project Tree

### ISSUE THREAD

**Issue by dessant** [kivy/kivy-designer#125]
@aron-bordin, I was trying out the gsoc branch with kivy master, this is related to https://github.com/kivy/kivy/pull/3469.

```python
Traceback (most recent call last):
  File "e:\dev\envs\py34_x86\kivy\kivy\core\window\window_sdl2.py", line 606, in mainloop
    self._mainloop()
  File "e:\dev\envs\py34_x86\kivy\kivy\core\window\window_sdl2.py", line 361, in _mainloop
    EventLoop.idle()
  File "e:\dev\envs\py34_x86\kivy\kivy\base.py", line 330, in idle
    self.dispatch_input()
  File "e:\dev\envs\py34_x86\kivy\kivy\base.py", line 315, in dispatch_input
    post_dispatch_input(*pop(0))
  File "e:\dev\envs\py34_x86\kivy\kivy\base.py", line 221, in post_dispatch_input
    listener.dispatch('on_motion', etype, me)
  File "kivy\_event.pyx", line 717, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7635)
  File "e:\dev\envs\py34_x86\kivy\kivy\core\window\__init__.py", line 993, in on_motion
    self.dispatch('on_touch_down', me)
  File "kivy\_event.pyx", line 717, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7635)
  File "e:\dev\envs\py34_x86\kivy\kivy\core\window\__init__.py", line 1009, in on_touch_down
    if w.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 717, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7635)
  File "e:\dev\prs\kivy-designer\designer\app.py", line 547, in on_touch_down
    return super(FloatLayout, self).on_touch_down(touch)
  File "e:\dev\envs\py34_x86\kivy\kivy\uix\widget.py", line 438, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 717, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7635)
  File "e:\dev\envs\py34_x86\kivy\kivy\uix\widget.py", line 438, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 717, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7635)
  File "e:\dev\envs\py34_x86\kivy\kivy\uix\widget.py", line 438, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 717, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7635)
  File "e:\dev\envs\py34_x86\kivy\kivy\uix\widget.py", line 438, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 717, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7635)
  File "e:\dev\envs\py34_x86\kivy\kivy\uix\widget.py", line 438, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 717, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7635)
  File "e:\dev\envs\py34_x86\kivy\kivy\uix\treeview.py", line 495, in on_touch_down
    node.dispatch('on_touch_down', touch)
  File "kivy\_event.pyx", line 713, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7590)
  File "kivy\_event.pyx", line 1223, in kivy._event.EventObservers.dispatch (kivy\_event.c:13325)
  File "kivy\_event.pyx", line 1147, in kivy._event.EventObservers._dispatch (kivy\_event.c:12851)
  File "e:\dev\prs\kivy-designer\designer\designer_content.py", line 174, in _file_node_clicked
    full_path, self.proj_loader)
  File "e:\dev\prs\kivy-designer\designer\designer_content.py", line 269, in show_buildozer_spec_editor
    spec_editor.load_settings(proj_loader.proj_dir)
  File "e:\dev\prs\kivy-designer\designer\buildozer_spec_editor.py", line 157, in load_settings
    'settings', 'buildozer_spec_app.json'))
  File "e:\dev\envs\py34_x86\kivy\kivy\uix\settings.py", line 948, in add_json_panel
    panel = self.create_json_panel(title, config, filename, data)
  File "e:\dev\prs\kivy-designer\designer\buildozer_spec_editor.py", line 213, in create_json_panel
    instance = cls(panel=panel, **str_settings)
  File "e:\dev\envs\py34_x86\kivy\kivy\uix\label.py", line 248, in __init__
    super(Label, self).__init__(**kwargs)
  File "e:\dev\envs\py34_x86\kivy\kivy\uix\widget.py", line 312, in __init__
    super(Widget, self).__init__(**kwargs)
  File "kivy\_event.pyx", line 253, in kivy._event.EventDispatcher.__init__ (kivy\_event.c:4863)
TypeError: object.__init__() takes no parameters
```

**Comment by aron-bordin** [comment]
https://github.com/kivy/kivy/pull/3699 fix it. The problem is that by default, kivy pass panel object to all panel items(https://github.com/kivy/kivy/blob/master/kivy%2Fuix%2Fsettings.py#L989). However, when the setting item is a title, the panel attr is not defined(https://github.com/kivy/kivy/blob/master/kivy%2Fuix%2Fsettings.py#L584).
