### ISSUE TITLE
ImportError: Cannot import name InterfaceWithSidebar

### ISSUE THREAD

**Issue by TheInitializer** [kivy/kivy-designer#131]
Using Windows 10 64-bit, Python 2.7.10, Kivy 1.9.0, running 32-bit versions of everything (because the 64-bit python I've found to be pretty glitchy.)

When running main.py I get this error message:
```
> python main.py                                                                                     
[INFO              ] Kivy v1.7.2                                                                     
[INFO              ] [Logger      ] Record log in C:\Users\David\.kivy\logs\kivy_15-10-12_1.txt      
[INFO              ] [Factory     ] 144 symbols loaded                                               
[DEBUG             ] [Cache       ] register <kv.image> with limit=None, timeout=60s                 
[DEBUG             ] [Cache       ] register <kv.atlas> with limit=None, timeout=Nones               
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif        
[DEBUG             ] [Cache       ] register <kv.texture> with limit=1000, timeout=60s               
[DEBUG             ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600s              
[DEBUG             ] [Cache       ] register <kv.lang> with limit=None, timeout=Nones                
[INFO              ] [Text        ] Provider: pygame                                                 
[DEBUG             ] [Cache       ] register <kv.loader> with limit=500, timeout=60s                 
[INFO              ] [Loader      ] using a thread pool of 2 workers                                 
[DEBUG             ] [Cache       ] register <textinput.label> with limit=None, timeout=60.0s        
[DEBUG             ] [Cache       ] register <textinput.width> with limit=None, timeout=60.0s        
[ERROR             ] [filechooser ] win32file module is missing                                      
[ERROR             ] [filechooser ] we cant check if a file is hidden or not                         
 Traceback (most recent call last):                                                                  
   File "main.py", line 2, in <module>                                                               
     from designer.app import DesignerApp                                                            
   File "C:\Python27\kivy-designer\designer\app.py", line 4, in <module>                             
     from designer.profile_settings import ProfileSettings                                           
   File "C:\Python27\kivy-designer\designer\profile_settings.py", line 8, in <module>                
     from kivy.uix.settings import Settings, InterfaceWithSidebar, \                                 
 ImportError: cannot import name InterfaceWithSidebar                                                
```

**Comment by dessant** [comment]
Your kivy is not 1.9, but `[INFO              ] Kivy v1.7.2`, try upgrading and reopen if the error persists.
