### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by admica** [kivy/kivy-designer#132]
I'm running Fedora 21. When I cloned the kivy-designer repo, the data directory was missing the fonts, so I found them in my kivy installation and rsync'd the whole data directory. Why are the fonts missing from data and what else is missing? There's no instructions that say it needs to be merged into the kivy installation. I give up at this point.

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/kivy/core/window/window_pygame.py", line 398, in mainloop
    self._mainloop()
  File "/usr/lib64/python2.7/site-packages/kivy/core/window/window_pygame.py", line 285, in _mainloop
    EventLoop.idle()
  File "/usr/lib64/python2.7/site-packages/kivy/base.py", line 330, in idle
    self.dispatch_input()
  File "/usr/lib64/python2.7/site-packages/kivy/base.py", line 315, in dispatch_input
    post_dispatch_input(*pop(0))
  File "/usr/lib64/python2.7/site-packages/kivy/base.py", line 221, in post_dispatch_input
    listener.dispatch('on_motion', etype, me)
  File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7008)
  File "/usr/lib64/python2.7/site-packages/kivy/core/window/__init__.py", line 904, in on_motion
    self.dispatch('on_touch_down', me)
  File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7008)
  File "/usr/lib64/python2.7/site-packages/kivy/core/window/__init__.py", line 920, in on_touch_down
    if w.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7008)
  File "/usr/lib64/python2.7/site-packages/kivy/uix/popup.py", line 201, in on_touch_down
    return super(Popup, self).on_touch_down(touch)
  File "/usr/lib64/python2.7/site-packages/kivy/uix/modalview.py", line 242, in on_touch_down
    super(ModalView, self).on_touch_down(touch)
  File "/usr/lib64/python2.7/site-packages/kivy/uix/widget.py", line 382, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7008)
  File "/usr/lib64/python2.7/site-packages/kivy/uix/widget.py", line 382, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7008)
  File "/usr/lib64/python2.7/site-packages/kivy/uix/widget.py", line 382, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7008)
  File "/usr/lib64/python2.7/site-packages/kivy/uix/widget.py", line 382, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7008)
  File "/usr/lib64/python2.7/site-packages/kivy/uix/widget.py", line 382, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7008)
  File "/usr/lib64/python2.7/site-packages/kivy/uix/behaviors.py", line 135, in on_touch_down
    self.dispatch('on_press')
  File "kivy/_event.pyx", line 695, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:6967)
  File "kivy/_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (kivy/_event.c:12191)
  File "kivy/_event.pyx", line 1092, in kivy._event.EventObservers._dispatch (kivy/_event.c:11764)
  File "kivy/_event.pyx", line 695, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:6967)
  File "kivy/_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (kivy/_event.c:12191)
  File "kivy/_event.pyx", line 1092, in kivy._event.EventObservers._dispatch (kivy/_event.c:11764)
  File "/home/admica/workspace/git/kivy/kivy-designer/designer/app.py", line 674, in _perform_new
    self.designer_content.toolbox.add_custom()
  File "/home/admica/workspace/git/kivy/kivy-designer/designer/uix/designer_sandbox.py", line 31, in __exit__
    return self.on_exception(value, tb=tb)
  File "/home/admica/workspace/git/kivy/kivy-designer/designer/uix/designer_sandbox.py", line 38, in on_exception
    self.dispatch('on_getting_exception')
  File "kivy/_event.pyx", line 695, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:6967)
  File "kivy/_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (kivy/_event.c:12191)
  File "kivy/_event.pyx", line 1092, in kivy._event.EventObservers._dispatch (kivy/_event.c:11764)
  File "/home/admica/workspace/git/kivy/kivy-designer/designer/app.py", line 1583, in on_sandbox_getting_exception
    self.ui_creator.error_console.text = text
  File "kivy/weakproxy.pyx", line 22, in kivy.weakproxy.WeakProxy.__setattr__ (kivy/weakproxy.c:1182)
  File "kivy/properties.pyx", line 397, in kivy.properties.Property.__set__ (kivy/properties.c:4677)
  File "kivy/properties.pyx", line 1350, in kivy.properties.AliasProperty.set (kivy/properties.c:21738)
  File "/usr/lib64/python2.7/site-packages/kivy/uix/textinput.py", line 2576, in _set_text
    self._refresh_text(text)
  File "/usr/lib64/python2.7/site-packages/kivy/uix/textinput.py", line 1525, in _refresh_text
    _lines, self._lines_flags = self._split_smart(text)
  File "/usr/lib64/python2.7/site-packages/kivy/uix/textinput.py", line 1914, in _split_smart
    w = text_width(word, _tab_width, _label_cached)
  File "/usr/lib64/python2.7/site-packages/kivy/uix/codeinput.py", line 161, in _get_text_width
    lbl = self._create_line_label(text)
  File "/usr/lib64/python2.7/site-packages/kivy/uix/codeinput.py", line 139, in _create_line_label
    label.refresh()
  File "/usr/lib64/python2.7/site-packages/kivy/core/text/__init__.py", line 617, in refresh
    sz = self.render()
  File "/usr/lib64/python2.7/site-packages/kivy/core/text/markup.py", line 117, in render
    ret = self._pre_render()
  File "/usr/lib64/python2.7/site-packages/kivy/core/text/markup.py", line 219, in _pre_render
    extents = self.get_cached_extents()
  File "/usr/lib64/python2.7/site-packages/kivy/core/text/text_pygame.py", line 88, in get_cached_extents
    return self._get_font().size
  File "/usr/lib64/python2.7/site-packages/kivy/core/text/text_pygame.py", line 49, in _get_font
    font_handle = open(fontname, 'rb')
IOError: [Errno 2] No such file or directory: 'data/fonts/DroidSansMono.ttf'

**Comment by dessant** [comment]
Copying fonts is not needed. Are you using Kivy 1.9.0? If yes, pygame should not be the default, but sdl2.

But even then, Kivy Designer master references Roboto https://github.com/kivy/kivy-designer/search?utf8=%E2%9C%93&q=roboto.
Kivy switched to Roboto after the 1.9.0 release, so Kivy master is needed in order to run KD.

**Comment by aron-bordin** [comment]
Hi @admica 

KD UIX components uses kivy default fonts by default now. 
So you can use KD with your kivy installed from pip.

Thx for posting.

**Comment by admica** [comment]
$ python main.py 
[INFO   ] [Logger      ] Record log in /home/acarr/.kivy/logs/kivy_15-10-15_94.txt
[INFO   ] [Kivy        ] v1.9.0
[INFO   ] [Python      ] v2.7.8 (default, Jul  5 2015, 14:16:16) 
[GCC 4.9.2 20150212 (Red Hat 4.9.2-6)]
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
[INFO   ] [Factory     ] 173 symbols loaded
[INFO   ] [Text        ] Provider: pygame
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
[INFO   ] [GL          ] OpenGL version <4.5.0 NVIDIA 352.41>
[INFO   ] [GL          ] OpenGL vendor <NVIDIA Corporation>
[INFO   ] [GL          ] OpenGL renderer <Quadro 600/PCIe/SSE2>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <4.50 NVIDIA>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Clipboard   ] Provider: gtk3(['clipboard_dbusklipper'] ignored)
 Traceback (most recent call last):
   File "main.py", line 2, in <module>
     from designer.app import DesignerApp
   File "/home/admica/kivy-designer-master/designer/app.py", line 62, in <module>
     from designer.uix.bug_reporter import BugReporterApp
   File "/home/admica/kivy-designer-master/designer/uix/bug_reporter.py", line 7, in <module>
     import six.moves.urllib
 ImportError: No module named urllib

**Comment by dessant** [comment]
@admica, btw, how did you install kivy?

**Comment by admica** [comment]
I removed the repo after I tried splicing in dirs/files it complained about and started fresh.
$ sudo pip install kivy --upgrade # but I already have it, version is 1.9.0
$ git clone https://github.com/kivy/kivy-designer.git && cd kivy-designer-master
$ sudo pip install -r requirements.txt

Everything looks find until I try to run main.py

$ python main.py 
Purge log fired. Analysing...
Purge finished!
[INFO   ] [Logger      ] Record log in /home/admica/.kivy/logs/kivy_15-10-15_25.txt
[INFO   ] [Kivy        ] v1.9.0
[INFO   ] [Python      ] v2.7.8 (default, Jul  5 2015, 14:16:16) 
[GCC 4.9.2 20150212 (Red Hat 4.9.2-6)]
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
[INFO   ] [Factory     ] 173 symbols loaded
[INFO   ] [Text        ] Provider: pygame
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
[INFO   ] [GL          ] OpenGL version <4.5.0 NVIDIA 352.41>
[INFO   ] [GL          ] OpenGL vendor <NVIDIA Corporation>
[INFO   ] [GL          ] OpenGL renderer <Quadro 600/PCIe/SSE2>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <4.50 NVIDIA>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked

** (main.py:20944): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[INFO   ] [Clipboard   ] Provider: gtk3(['clipboard_dbusklipper'] ignored)
 Traceback (most recent call last):
   File "main.py", line 2, in <module>
     from designer.app import DesignerApp
   File "/home/admica/kivy-designer-master/designer/app.py", line 62, in <module>
     from designer.uix.bug_reporter import BugReporterApp
   File "/home/admica/kivy-designer-master/designer/uix/bug_reporter.py", line 7, in <module>
     import six.moves.urllib
 ImportError: No module named urllib

I can import six and six.moves
but six.moves is looking pretty sparce:
>>> dir(six.moves)
['__doc__', '__name__']

**Comment by dessant** [comment]
I'm not sure what's going on with six, but you should also install the rest of the deps: http://kivy.org/docs/installation/installation-linux.html#dependencies-with-sdl2.

As i said, until you see pygame in your logs, your setup is wrong.

**Comment by aron-bordin** [comment]
@admica 

Are you using a recent version of `six`?

Run the command to get six version:

    python -c 'import six; print(six.__version__)'
