### ISSUE TITLE
Problem running on Ubuntu guest with Mac parallel

### ISSUE THREAD

**Issue by phsamuel** [kivy/kivy-designer#134]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 539, in mainloop
    self._mainloop()
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 300, in _mainloop
    EventLoop.idle()
  File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 330, in idle
    self.dispatch_input()
  File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 315, in dispatch_input
    post_dispatch_input(*pop(0))
  File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 281, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:6856)
  File "/usr/lib/python2.7/dist-packages/kivy/uix/behaviors.py", line 163, in on_touch_up
    self.dispatch('on_release')
  File "_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:6856)
  File "/usr/lib/python2.7/dist-packages/kivy/uix/tabbedpanel.py", line 179, in on_release
    self.panel.switch_to(self.panel.current_tab)
AttributeError: 'DesignerCloseableTab' object has no attribute 'panel'

**Comment by aron-bordin** [comment]
Hi @phsamuel , thx for the bug report. This issue is fixed in master.
