### ISSUE TITLE
I don't know what's happened

### ISSUE THREAD

**Issue by fenglingjie** [kivy/kivy-designer#136]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 539, in mainloop
    self._mainloop()
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 300, in _mainloop
    EventLoop.idle()
  File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 327, in idle
    Clock.tick()
  File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 483, in tick
    self._process_events()
  File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 615, in _process_events
    event.tick(self._last_tick, remove)
  File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 374, in tick
    ret = callback(self._dt)
  File "/home/mark/kivy-designer/designer/playground.py", line 956, in start_widget_dragging
    drag_elem = App.get_running_app().create_draggable_element(
AttributeError: 'BugReporterApp' object has no attribute 'create_draggable_element'

**Comment by aron-bordin** [comment]
Hi, thanks for the report. There was a bug on bug reporter, and sometimes, bug reporter was displaying an incorrect traceback. This issue was fixed in the last commit, if you find a new bug, please, create a new issue.

Thx, and sorry for the confusion !
