### ISSUE TITLE
shutdown mavericks

### ISSUE THREAD

**Issue by diekanne** [kivy/kivy-designer#137]
Traceback (most recent call last):
  File "/Users/admin/venv/base/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 525, in mainloop
    self._mainloop()
  File "/Users/admin/venv/base/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 290, in _mainloop
    EventLoop.idle()
  File "/Users/admin/venv/base/lib/python2.7/site-packages/kivy/base.py", line 327, in idle
    Clock.tick()
  File "/Users/admin/venv/base/lib/python2.7/site-packages/kivy/clock.py", line 483, in tick
    self._process_events()
  File "/Users/admin/venv/base/lib/python2.7/site-packages/kivy/clock.py", line 615, in _process_events
    event.tick(self._last_tick, remove)
  File "/Users/admin/venv/base/lib/python2.7/site-packages/kivy/clock.py", line 374, in tick
    ret = callback(self._dt)
  File "/Users/admin/venv/base/lib/python2.7/site-packages/kivy/uix/label.py", line 267, in texture_update
    self._label.refresh()
  File "/Users/admin/venv/base/lib/python2.7/site-packages/kivy/core/text/__init__.py", line 614, in refresh
    self.resolve_font_name()
  File "/Users/admin/venv/base/lib/python2.7/site-packages/kivy/core/text/__init__.py", line 257, in resolve_font_name
    raise IOError('Label: File %r not found' % fontname)
IOError: Label: File 'h.ttf' not found

**Comment by aron-bordin** [comment]
This seems to be a problem in the kivy package. If you face the problem again, please, just let me know.

Thanks for the report
