### ISSUE TITLE
Kivy designer not run

### ISSUE THREAD

**Issue by jcsena** [kivy/kivy-designer#140]
Kivy designer not run
```
Traceback (most recent call last):
   File "main.py", line 2, in <module>
     from designer.app import DesignerApp
   File "/Users/Julio/Documents/kivy/kivy-designer/designer/app.py", line 45, in <module>
     from designer.project_loader import ProjectLoader, ProjectLoaderException
   File "/Users/Julio/Documents/kivy/kivy-designer/designer/project_loader.py", line 10, in <module>
     from six import exec_
 ImportError: No module named six
```
<img width="840" alt="image" src="https://cloud.githubusercontent.com/assets/4293508/11340030/2da2f5f6-91ca-11e5-8c0a-2563c02895fa.png">

**Comment by dessant** [comment]
Make sure to have all dependencies installed: https://github.com/kivy/kivy-designer/blob/master/requirements.txt.
