### ISSUE TITLE
After I create a new project to select Action bar template this error pops up.

### ISSUE THREAD

**Issue by kiok46** [kivy/kivy-designer#141]
I created a new project and selected action bar template then I clicked on action bar widget multiple time and this error pops up.

## Environment Info

kivy: 1.9.0
pygments: 2.0.2
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 1.0.1
six: 1.10.0
kivy-garden: 0.1.4

Platform: Linux-4.2.0-18-generic-x86_64-with-Ubuntu-15.10-wily
Python: 2.7.10

## Traceback

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 525, in mainloop
    self._mainloop()
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 290, in _mainloop
    EventLoop.idle()
  File "/usr/local/lib/python2.7/dist-packages/kivy/base.py", line 327, in idle
    Clock.tick()
  File "/usr/local/lib/python2.7/dist-packages/kivy/clock.py", line 483, in tick
    self._process_events()
  File "/usr/local/lib/python2.7/dist-packages/kivy/clock.py", line 615, in _process_events
    event.tick(self._last_tick, remove)
  File "/usr/local/lib/python2.7/dist-packages/kivy/clock.py", line 374, in tick
    ret = callback(self._dt)
  File "/home/kuldeep/Downloads/kivy-designer-master/designer/nodetree.py", line 115, in _refresh
    self._clear_tree(self.tree, self.tree.root)
  File "/home/kuldeep/Downloads/kivy-designer-master/designer/nodetree.py", line 108, in _clear_tree
    self._clear_tree(tree, n)
  File "/home/kuldeep/Downloads/kivy-designer-master/designer/nodetree.py", line 108, in _clear_tree
    self._clear_tree(tree, n)
  File "/home/kuldeep/Downloads/kivy-designer-master/designer/nodetree.py", line 107, in _clear_tree
    for n in node.nodes[:]:
  File "kivy/weakproxy.pyx", line 19, in kivy.weakproxy.WeakProxy.__getattr__ (/tmp/pip-build-PcmCq7/kivy/kivy/weakproxy.c:1097)
  File "kivy/weakproxy.pyx", line 15, in kivy.weakproxy.WeakProxy.__ref__ (/tmp/pip-build-PcmCq7/kivy/kivy/weakproxy.c:1004)
ReferenceError: weakly-referenced object no longer exists

**Comment by kiok46** [comment]
Issue number #141 and issue number #142 are both different.

**Comment by aron-bordin** [comment]
Hi @kiok46 

I made several modifications to playground lately. Do you still getting this error ? (I could not reproduce it here )

**Comment by kiok46** [comment]
@aron-bordin  Neither can I, I will re-open, if it occurs again. closing.
