### ISSUE TITLE
After I create a new project to select Action bar template this error pops up.

### ISSUE THREAD

**Issue by kiok46** [kivy/kivy-designer#142]
I created a new project and selected action bar template then I clicked on playground area and this error pops up.

## Environment Info

kivy: 1.9.0
pygments: 2.0.2
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 1.0.1
six: 1.10.0
kivy-garden: 0.1.4

Platform: Linux-4.2.0-18-generic-x86_64-with-Ubuntu-15.10-wily
Python: 2.7.10

## Traceback

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 525, in mainloop
    self._mainloop()
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 290, in _mainloop
    EventLoop.idle()
  File "/usr/local/lib/python2.7/dist-packages/kivy/base.py", line 327, in idle
    Clock.tick()
  File "/usr/local/lib/python2.7/dist-packages/kivy/clock.py", line 483, in tick
    self._process_events()
  File "/usr/local/lib/python2.7/dist-packages/kivy/clock.py", line 615, in _process_events
    event.tick(self._last_tick, remove)
  File "/usr/local/lib/python2.7/dist-packages/kivy/clock.py", line 374, in tick
    ret = callback(self._dt)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/textinput.py", line 1494, in _refresh_line_options
    self._refresh_text_from_property()
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/textinput.py", line 1513, in _refresh_text_from_property
    self._refresh_text(self._get_text(encode=False), *largs)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/textinput.py", line 1538, in _refresh_text
    self._lines = _lines
  File "kivy/properties.pyx", line 397, in kivy.properties.Property.__set__ (/tmp/pip-build-PcmCq7/kivy/kivy/properties.c:4680)
  File "kivy/properties.pyx", line 696, in kivy.properties.ListProperty.set (/tmp/pip-build-PcmCq7/kivy/kivy/properties.c:10169)
  File "kivy/properties.pyx", line 429, in kivy.properties.Property.set (/tmp/pip-build-PcmCq7/kivy/kivy/properties.c:5203)
  File "kivy/properties.pyx", line 484, in kivy.properties.Property.dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/properties.c:5852)
  File "kivy/_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:12154)
  File "kivy/_event.pyx", line 1074, in kivy._event.EventObservers._dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:11451)
  File "kivy/properties.pyx", line 1328, in kivy.properties.AliasProperty.trigger_change (/tmp/pip-build-PcmCq7/kivy/kivy/properties.c:21267)
  File "kivy/properties.pyx", line 1334, in kivy.properties.AliasProperty.trigger_change (/tmp/pip-build-PcmCq7/kivy/kivy/properties.c:21158)
  File "kivy/properties.pyx", line 484, in kivy.properties.Property.dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/properties.c:5852)
  File "kivy/_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:12154)
  File "kivy/_event.pyx", line 1074, in kivy._event.EventObservers._dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:11451)
  File "/home/kuldeep/Downloads/kivy-designer-master/designer/eventviewer.py", line 96, in on_text
    self.text)
  File "/home/kuldeep/Downloads/kivy-designer-master/designer/uix/kv_lang_area.py", line 616, in set_event_handler
    path_to_widget = self._get_widget_path(widget)
  File "/home/kuldeep/Downloads/kivy-designer-master/designer/uix/kv_lang_area.py", line 173, in _get_widget_path
    _widget.parent.children.index(_widget) - 1
ValueError: <kivy.core.window.window_sdl2.WindowSDL object at 0x7fdbe8166db8> is not in list

**Comment by kiok46** [comment]
Issue number #141 and issue number #142 are both different.

**Comment by aron-bordin** [comment]
Hi @kiok46 

I made several modifications to playground lately. Do you still getting this error ? (I could not reproduce it here )

**Comment by kiok46** [comment]
@aron-bordin  Neither can I, I will re-open, if it occurs again. closing.
