### ISSUE TITLE
No attribute 'root_rule'

### ISSUE THREAD

**Issue by kiok46** [kivy/kivy-designer#143]
I created a new BoxLayout widget and then added new button via drag and drop after that I tried to add another button and then this error pops up.

## Environment Info

kivy: 1.9.0
pygments: 2.0.2
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 1.0.1
six: 1.10.0
kivy-garden: 0.1.4

Platform: Linux-4.2.0-18-generic-x86_64-with-Ubuntu-15.10-wily
Python: 2.7.10

## Traceback

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 525, in mainloop
    self._mainloop()
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 290, in _mainloop
    EventLoop.idle()
  File "/usr/local/lib/python2.7/dist-packages/kivy/base.py", line 330, in idle
    self.dispatch_input()
  File "/usr/local/lib/python2.7/dist-packages/kivy/base.py", line 315, in dispatch_input
    post_dispatch_input(*pop(0))
  File "/usr/local/lib/python2.7/dist-packages/kivy/base.py", line 221, in post_dispatch_input
    listener.dispatch('on_motion', etype, me)
  File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:7011)
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/__init__.py", line 904, in on_motion
    self.dispatch('on_touch_down', me)
  File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:7011)
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/__init__.py", line 920, in on_touch_down
    if w.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:7011)
  File "/home/kuldeep/Downloads/kivy-designer-master/designer/app.py", line 558, in on_touch_down
    return super(FloatLayout, self).on_touch_down(touch)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/widget.py", line 382, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:7011)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/widget.py", line 382, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:7011)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/widget.py", line 382, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:7011)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/widget.py", line 382, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:7011)
  File "/home/kuldeep/Downloads/kivy-designer-master/designer/ui_creator.py", line 97, in on_touch_down
    return super(UICreator, self).on_touch_down(*args)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/widget.py", line 382, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:7011)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/widget.py", line 382, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:7011)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/widget.py", line 382, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:7011)
  File "/home/kuldeep/Downloads/kivy-designer-master/designer/playground.py", line 986, in on_touch_down
    App.get_running_app().focus_widget(target)
  File "/home/kuldeep/Downloads/kivy-designer-master/designer/app.py", line 1779, in focus_widget
    self.widget_focused = widget
  File "kivy/properties.pyx", line 397, in kivy.properties.Property.__set__ (/tmp/pip-build-PcmCq7/kivy/kivy/properties.c:4680)
  File "kivy/properties.pyx", line 429, in kivy.properties.Property.set (/tmp/pip-build-PcmCq7/kivy/kivy/properties.c:5203)
  File "kivy/properties.pyx", line 484, in kivy.properties.Property.dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/properties.c:5852)
  File "kivy/_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:12154)
  File "kivy/_event.pyx", line 1074, in kivy._event.EventObservers._dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:11451)
  File "kivy/_event.pyx", line 716, in kivy._event.EventDispatcher.__proxy_setter (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:7605)
  File "kivy/properties.pyx", line 429, in kivy.properties.Property.set (/tmp/pip-build-PcmCq7/kivy/kivy/properties.c:5203)
  File "kivy/properties.pyx", line 484, in kivy.properties.Property.dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/properties.c:5852)
  File "kivy/_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:12154)
  File "kivy/_event.pyx", line 1074, in kivy._event.EventObservers._dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:11451)
  File "/home/kuldeep/Downloads/kivy-designer-master/designer/eventviewer.py", line 185, in on_widget
    self.discover(value)
  File "/home/kuldeep/Downloads/kivy-designer-master/designer/eventviewer.py", line 203, in discover
    ip = self.build_for(event)
  File "/home/kuldeep/Downloads/kivy-designer-master/designer/eventviewer.py", line 304, in build_for
    info_message="Set event handler for event %s" % (name))
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/textinput.py", line 484, in __init__
    super(TextInput, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/behaviors.py", line 771, in __init__
    super(FocusBehavior, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/widget.py", line 261, in __init__
    super(Widget, self).__init__(**kwargs)
  File "kivy/_event.pyx", line 271, in kivy._event.EventDispatcher.__init__ (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:4933)
  File "kivy/properties.pyx", line 397, in kivy.properties.Property.__set__ (/tmp/pip-build-PcmCq7/kivy/kivy/properties.c:4680)
  File "kivy/properties.pyx", line 1350, in kivy.properties.AliasProperty.set (/tmp/pip-build-PcmCq7/kivy/kivy/properties.c:21715)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/textinput.py", line 2576, in _set_text
    self._refresh_text(text)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/textinput.py", line 1538, in _refresh_text
    self._lines = _lines
  File "kivy/properties.pyx", line 397, in kivy.properties.Property.__set__ (/tmp/pip-build-PcmCq7/kivy/kivy/properties.c:4680)
  File "kivy/properties.pyx", line 696, in kivy.properties.ListProperty.set (/tmp/pip-build-PcmCq7/kivy/kivy/properties.c:10169)
  File "kivy/properties.pyx", line 429, in kivy.properties.Property.set (/tmp/pip-build-PcmCq7/kivy/kivy/properties.c:5203)
  File "kivy/properties.pyx", line 484, in kivy.properties.Property.dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/properties.c:5852)
  File "kivy/_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:12154)
  File "kivy/_event.pyx", line 1074, in kivy._event.EventObservers._dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:11451)
  File "kivy/properties.pyx", line 1328, in kivy.properties.AliasProperty.trigger_change (/tmp/pip-build-PcmCq7/kivy/kivy/properties.c:21267)
  File "kivy/properties.pyx", line 1334, in kivy.properties.AliasProperty.trigger_change (/tmp/pip-build-PcmCq7/kivy/kivy/properties.c:21158)
  File "kivy/properties.pyx", line 484, in kivy.properties.Property.dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/properties.c:5852)
  File "kivy/_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:12154)
  File "kivy/_event.pyx", line 1074, in kivy._event.EventObservers._dispatch (/tmp/pip-build-PcmCq7/kivy/kivy/_event.c:11451)
  File "/home/kuldeep/Downloads/kivy-designer-master/designer/eventviewer.py", line 107, in on_text
    root = self.project_loader.root_rule.widget
AttributeError: 'NoneType' object has no attribute 'root_rule'

**Comment by aron-bordin** [comment]
The project loader was rewrote in my fork, so I'll fix this line  root = self.project_loader.root_rule.widget with the new project_loader implementation.

**Comment by aron-bordin** [comment]
fixed in master
