### ISSUE TITLE
Cannot open kivy-designer on the RaspberryPI

### ISSUE THREAD

**Issue by skarbat** [kivy/kivy-designer#152]
When trying to run kivy-designer on the RaspberryPI, I get the exception below.
Running on top of the latest kivy sources as of this writing.

```
[INFO              ] [Base        ] Start application main loop
[INFO              ] [HIDMotionEvent] using <MOSART Semi. 2.4G Keyboard Mouse>
[INFO              ] [HIDMotionEvent] using <MOSART Semi. 2.4G Keyboard Mouse>
[INFO              ] [GL          ] NPOT texture support is available
[INFO              ] [HIDMotionEvent] using <FT5406 memory based driver>
[INFO              ] [HIDMotionEvent] <FT5406 memory based driver> range ABS X position is 0 - 800
[INFO              ] [HIDMotionEvent] <FT5406 memory based driver> range ABS Y position is 0 - 480
[INFO              ] [HIDMotionEvent] <FT5406 memory based driver> range position X is 0 - 800
[INFO              ] [HIDMotionEvent] <FT5406 memory based driver> range position Y is 0 - 480
[WARNING           ] [Accordion   ] not enough space for displaying all children
[WARNING           ] [Accordion   ] need 176px, got 100px
[WARNING           ] [Accordion   ] layout aborted.
[WARNING           ] [Accordion   ] not enough space for displaying all children
[WARNING           ] [Accordion   ] need 220px, got 100px
[WARNING           ] [Accordion   ] layout aborted.
[WARNING           ] [Accordion   ] not enough space for displaying all children
[WARNING           ] [Accordion   ] need 220px, got 100px
[WARNING           ] [Accordion   ] layout aborted.
[INFO              ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "main.py", line 6, in <module>
     DesignerApp().run()
   File "/usr/local/lib/python2.7/dist-packages/kivy/app.py", line 828, in run
     runTouchApp()
   File "/usr/local/lib/python2.7/dist-packages/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_egl_rpi.py", line 89, in mainloop
     self._mainloop()
   File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_egl_rpi.py", line 84, in _mainloop
     EventLoop.idle()
   File "/usr/local/lib/python2.7/dist-packages/kivy/base.py", line 327, in idle
     Clock.tick()
   File "/usr/local/lib/python2.7/dist-packages/kivy/clock.py", line 515, in tick
     self._process_events()
   File "/usr/local/lib/python2.7/dist-packages/kivy/clock.py", line 647, in _process_events
     event.tick(self._last_tick, remove)
   File "/usr/local/lib/python2.7/dist-packages/kivy/clock.py", line 406, in tick
     ret = callback(self._dt)
 TypeError: create_window() takes exactly 1 argument (2 given)
```

**Comment by Kmarconi** [comment]
Up !

**Comment by tshirtman** [comment]
I'm sorry, but i must say this project is not maintained at all, and there is little to no will to change that, i assume that as people get comfortable with kvlang, they see little use for such effort. If you are interested in helping it, you are welcome to, but don't expect further development soon here.

**Comment by Kmarconi** [comment]
Ok :) I just saw this post and it correspond exactly to my problem and i found only one solution which was about the parameters of my window.size but i don't know where i can change the value of it ... I'm working on Raspberry Pi
