### ISSUE TITLE
want to drag image to the project

### ISSUE THREAD

**Issue by Tomis1** [kivy/kivy-designer#168]
## Environment Info

kivy: 1.9.1
pygments: 2.0.2
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 1.0.1
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-10-10.0.10586
Python: 3.4.4

## Traceback

Traceback (most recent call last):
  File "C:\Python\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Python\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Python\Python34\lib\site-packages\kivy\base.py", line 330, in idle
    self.dispatch_input()
  File "C:\Python\Python34\lib\site-packages\kivy\base.py", line 315, in dispatch_input
    post_dispatch_input(*pop(0))
  File "C:\Python\Python34\lib\site-packages\kivy\base.py", line 221, in post_dispatch_input
    listener.dispatch('on_motion', etype, me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python\Python34\lib\site-packages\kivy\core\window\__init__.py", line 1030, in on_motion
    self.dispatch('on_touch_down', me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python\Python34\lib\site-packages\kivy\core\window\__init__.py", line 1046, in on_touch_down
    if w.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kiv

**Comment by aron-bordin** [comment]
Hi,  bug fixed in master.

Thx
