### ISSUE TITLE
PropertyOptions.text only accepts str (line 1181 in designer.kv)

### ISSUE THREAD

**Issue by kiok46** [kivy/kivy-designer#169]
## Environment Info

kivy: 1.9.1
pygments: 2.0.2
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 1.0.1
six: 1.10.0
kivy-garden: 0.1.4

Platform: Linux-4.2.0-23-generic-x86_64-with-Ubuntu-15.10-wily
Python: 2.7.10

## Traceback

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "/usr/local/lib/python2.7/dist-packages/kivy/base.py", line 330, in idle
    self.dispatch_input()
  File "/usr/local/lib/python2.7/dist-packages/kivy/base.py", line 315, in dispatch_input
    post_dispatch_input(*pop(0))
  File "/usr/local/lib/python2.7/dist-packages/kivy/base.py", line 221, in post_dispatch_input
    listener.dispatch('on_motion', etype, me)
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-HBE8tC/kivy/kivy/_event.c:7699)
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/__init__.py", line 1030, in on_motion
    self.dispatch('on_touch_down', me)
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-HBE8tC/kivy/kivy/_event.c:7699)
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/__init__.py", line 1046, in on_touch_down
    if w.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-HBE8tC/kivy/kivy/_event.c:7699)
  File "/home/kuldeep/Downloads/kivy-designers/after/kivy-designer/designer/app.py", line 622, in on_touch_down
    return super(FloatLayout, self).on_touch_down(touch)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-HBE8tC/kivy/kivy/_event.c:7699)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-HBE8tC/kivy/kivy/_event.c:7699)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-HBE8tC/kivy/kivy/_event.c:7699)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-HBE8tC/kivy/kivy/_event.c:7699)
  File "/home/kuldeep/Downloads/kivy-designers/after/kivy-designer/designer/ui_creator.py", line 98, in on_touch_down
    return super(UICreator, self).on_touch_down(*args)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-HBE8tC/kivy/kivy/_event.c:7699)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-HBE8tC/kivy/kivy/_event.c:7699)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-HBE8tC/kivy/kivy/_event.c:7699)
  File "/home/kuldeep/Downloads/kivy-designers/after/kivy-designer/designer/playground.py", line 1198, in on_touch_down
    App.get_running_app().focus_widget(target)
  File "/home/kuldeep/Downloads/kivy-designers/after/kivy-designer/designer/app.py", line 1704, in focus_widget
    self.widget_focused = widget
  File "kivy/properties.pyx", line 408, in kivy.properties.Property.__set__ (/tmp/pip-build-HBE8tC/kivy/kivy/properties.c:5114)
  File "kivy/properties.pyx", line 446, in kivy.properties.Property.set (/tmp/pip-build-HBE8tC/kivy/kivy/properties.c:5876)
  File "kivy/properties.pyx", line 501, in kivy.properties.Property.dispatch (/tmp/pip-build-HBE8tC/kivy/kivy/properties.c:6557)
  File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (/tmp/pip-build-HBE8tC/kivy/kivy/_event.c:13497)
  File "kivy/_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (/tmp/pip-build-HBE8tC/kivy/kivy/_event.c:12696)
  File "kivy/_event.pyx", line 735, in kivy._event.EventDispatcher.__proxy_setter (/tmp/pip-build-HBE8tC/kivy/kivy/_event.c:8285)
  File "kivy/properties.pyx", line 446, in kivy.properties.Property.set (/tmp/pip-build-HBE8tC/kivy/kivy/properties.c:5876)
  File "kivy/properties.pyx", line 501, in kivy.properties.Property.dispatch (/tmp/pip-build-HBE8tC/kivy/kivy/properties.c:6557)
  File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (/tmp/pip-build-HBE8tC/kivy/kivy/_event.c:13497)
  File "kivy/_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (/tmp/pip-build-HBE8tC/kivy/kivy/_event.c:12696)
  File "/home/kuldeep/Downloads/kivy-designers/after/kivy-designer/designer/propertyviewer.py", line 180, in on_widget
    self.discover(value)
  File "/home/kuldeep/Downloads/kivy-designers/after/kivy-designer/designer/propertyviewer.py", line 200, in discover
    ip = self.build_for(prop)
  File "/home/kuldeep/Downloads/kivy-designers/after/kivy-designer/designer/propertyviewer.py", line 240, in build_for
    kv_code_input=self.kv_code_input)
  File "/home/kuldeep/Downloads/kivy-designers/after/kivy-designer/designer/propertyviewer.py", line 112, in __init__
    Spinner.__init__(self, values=prop.options, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/spinner.py", line 111, in __init__
    super(Spinner, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/behaviors/button.py", line 80, in __init__
    super(ButtonBehavior, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/label.py", line 266, in __init__
    super(Label, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/widget.py", line 320, in __init__
    Builder.apply(self, ignored_consts=self._kwargs_applied_init)
  File "/usr/local/lib/python2.7/dist-packages/kivy/lang.py", line 1970, in apply
    self._apply_rule(widget, rule, rule, ignored_consts=ignored_consts)
  File "/usr/local/lib/python2.7/dist-packages/kivy/lang.py", line 2130, in _apply_rule
    e), cause=tb)
BuilderException: Parser: File "/home/kuldeep/Downloads/kivy-designers/after/kivy-designer/designer/designer.kv", line 1181:
...
   1179:
   1180:<PropertyBase>:
>> 1181:    propvalue: getattr(self.propwidget, self.propname)
   1182:    padding: '6pt', '6pt'
   1183:
...
ValueError: PropertyOptions.text accept only str
  File "/usr/local/lib/python2.7/dist-packages/kivy/lang.py", line 2119, in _apply_rule
    setattr(widget_set, key, value)
  File "kivy/weakproxy.pyx", line 22, in kivy.weakproxy.WeakProxy.__setattr__ (/tmp/pip-build-HBE8tC/kivy/kivy/weakproxy.c:1235)
  File "kivy/properties.pyx", line 408, in kivy.properties.Property.__set__ (/tmp/pip-build-HBE8tC/kivy/kivy/properties.c:5114)
  File "kivy/properties.pyx", line 446, in kivy.properties.Property.set (/tmp/pip-build-HBE8tC/kivy/kivy/properties.c:5876)
  File "kivy/properties.pyx", line 501, in kivy.properties.Property.dispatch (/tmp/pip-build-HBE8tC/kivy/kivy/properties.c:6557)
  File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (/tmp/pip-build-HBE8tC/kivy/kivy/_event.c:13497)
  File "kivy/_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (/tmp/pip-build-HBE8tC/kivy/kivy/_event.c:12696)
  File "/home/kuldeep/Downloads/kivy-designers/after/kivy-designer/designer/propertyviewer.py", line 117, in on_propvalue
    self.text = self.propvalue
  File "kivy/properties.pyx", line 408, in kivy.properties.Property.__set__ (/tmp/pip-build-HBE8tC/kivy/kivy/properties.c:5114)
  File "kivy/properties.pyx", line 443, in kivy.properties.Property.set (/tmp/pip-build-HBE8tC/kivy/kivy/properties.c:5825)

**Comment by aron-bordin** [comment]
Hi, bug fixed in master. 

Thx
