### ISSUE TITLE
ImportError: watchdog.events

### ISSUE THREAD

**Issue by LilyFirefly** [kivy/kivy-designer#17]
After following the installation instructions, I got this error:

``` python
~/kivy-designer$ python main.py 
[INFO   ] Kivy v1.8.0-dev
register context
[INFO   ] [Logger      ] Record log in /home/quartic/.kivy/logs/kivy_13-09-22_28.txt
[INFO   ] [Factory     ] 155 symbols loaded
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=Nones
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60s
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=Nones
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif 
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60s
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600s
[DEBUG  ] [Window      ] Ignored <egl_rpi> (import error)
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[WARNING] [WinPygame   ] Video: failed (multisamples=2)
[WARNING] [WinPygame   ] trying without antialiasing
[DEBUG  ] [Window      ] Display driver x11
[DEBUG  ] [Window      ] Actual window size: 800x600
[DEBUG  ] [Window      ] Actual color bits r8 g8 b8 a8
[DEBUG  ] [Window      ] Actual depth bits: 24
[DEBUG  ] [Window      ] Actual stencil bits: 8
[DEBUG  ] [Window      ] Actual multisampling samples: 0
[INFO   ] [GL          ] OpenGL version <2.1 Mesa 9.1.4>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Mobile Intel® GM45 Express Chipset x86/MMX/SSE2>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <1.20>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[DEBUG  ] [Shader      ] Fragment compiled successfully
[DEBUG  ] [Shader      ] Vertex compiled successfully
[DEBUG  ] [ImagePygame ] Load </home/quartic/kivy/kivy/data/glsl/default.png>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: pygame
[DEBUG  ] [Cache       ] register <kv.loader> with limit=500, timeout=60s
[INFO   ] [Loader      ] using a thread pool of 2 workers
[DEBUG  ] [Cache       ] register <textinput.label> with limit=None, timeout=60.0s
[DEBUG  ] [Cache       ] register <textinput.width> with limit=None, timeout=60.0s
[INFO   ] [Clipboard   ] Provider: pygame
 Traceback (most recent call last):
   File "main.py", line 2, in <module>
     from designer.app import DesignerApp
   File "/home/quartic/kivy-designer/designer/app.py", line 31, in <module>
     from designer.project_loader import ProjectLoader, ProjectLoaderException
   File "/home/quartic/kivy-designer/designer/project_loader.py", line 23, in <module>
     from designer.proj_watcher import ProjectWatcher
   File "/home/quartic/kivy-designer/designer/proj_watcher.py", line 5, in <module>
     from watchdog.events import FileSystemEventHandler
 ImportError: No module named watchdog.events
```

**Comment by element94** [comment]
I'm getting the same error. Using the instructions above. Yosemite 10.10.
