### ISSUE TITLE
Error while launching main.py

### ISSUE THREAD

**Issue by kleziegler** [kivy/kivy-designer#175]
Ubuntu 14.04
Kivy: 1.9.1
Python 2.7.6
Pygments 2.1

I tried to launch main.py, but i get following error:
```
[INFO   ] [Logger      ] Record log in /home/andi/.kivy/logs/kivy_16-01-30_17.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pygame
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 10.5.9>
[INFO   ] [GL          ] OpenGL vendor <X.Org>
[INFO   ] [GL          ] OpenGL renderer <Gallium 0.4 on AMD HAWAII>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "main.py", line 2, in <module>
     from designer.app import DesignerApp
   File "/home/andi/Kivy/kivy-designer/designer/app.py", line 51, in <module>
     from designer.designer_content import DesignerContent
   File "/home/andi/Kivy/kivy-designer/designer/designer_content.py", line 12, in <module>
     from designer.buildozer_spec_editor import BuildozerSpecEditor
   File "/home/andi/Kivy/kivy-designer/designer/buildozer_spec_editor.py", line 16, in <module>
     from pygments.lexers.configs import IniLexer
 ImportError: No module named configs
```
I removed pygments and reinstalled it with pip, but no difference

**Comment by aron-bordin** [comment]
Hi @kleziegler 

Could you try to remove pygments and install it again and give me some feedback, please ?

http://pygments.org/docs/lexers/#pygments.lexers.configs.IniLexer

The `configs` module should be available.

**Comment by hyOzd** [comment]
@kleziegler are you sure that pip can actually install pygments.

In my case, since pygments was installed via systems package manager (apt-get), pip refused to install. Updating the `python-pygments` package via apt-get fixed the issue.

**Comment by aron-bordin** [comment]
Hi,

I'm closing this issue because that is something missing on your pygments installation. If you need help or get any new error, just let us know.

Thx
