### ISSUE TITLE
kivy designer crashes when making a new project

### ISSUE THREAD

**Issue by LukeSkywalker92** [kivy/kivy-designer#177]
When I try to make a new project, I see the UI for a short time till I get the following error:

`
## Environment Info

kivy: 1.9.1
pygments: 2.1
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 1.0.1
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-7-6.1.7601-SP1
Python: 2.7.11

## Traceback

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Python27\lib\site-packages\kivy\base.py", line 327, in idle
    Clock.tick()
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 515, in tick
    self._process_events()
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 406, in tick
    ret = callback(self._dt)
  File "C:\Users\Luke\Downloads\kivy-designer-master\designer\uix\kivy_console.py", line 285, in run_command
    self._run_command_list()
  File "C:\Users\Luke\Downloads\kivy-designer-master\designer\uix\kivy_console.py", line 293, in _run_command_list
    self.stdin.write(self.command_list.pop(0))
  File "C:\Users\Luke\Downloads\kivy-designer-master\designer\uix\kivy_console.py", line 842, in write
    self.obj.on_enter()
  File "C:\Users\Luke\Downloads\kivy-designer-master\designer\uix\kivy_console.py", line 723, in on_enter
    ' directory:' + command[3:])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 31: ordinal not in range(128)

`

**Comment by aron-bordin** [comment]
Hi, 

this error may be fixed in master.
If you still getting this error please let me know.

Thx
