### ISSUE TITLE
Bug while using on ubuntu

### ISSUE THREAD

**Issue by Immortalin** [kivy/kivy-designer#179]
Stacktrace:
```Python3 
[CRITICAL] [Window      ] Unable to find any valuable Window provider at all!
egl_rpi - ImportError: cannot import name 'bcm'
  File "/usr/local/lib/python3.4/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/local/lib/python3.4/dist-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

pygame - ImportError: No module named 'pygame'
  File "/usr/local/lib/python3.4/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/local/lib/python3.4/dist-packages/kivy/core/window/window_pygame.py", line 8, in <module>
    import pygame

x11 - ImportError: No module named 'kivy.core.window.window_x11'
  File "/usr/local/lib/python3.4/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [App         ] Unable to get a Window, abort.
 Exception ignored in: 'kivy.properties.dpi2px'
 Traceback (most recent call last):
   File "/usr/local/lib/python3.4/dist-packages/kivy/utils.py", line 513, in __get__
     retval = self.func(inst)
   File "/usr/local/lib/python3.4/dist-packages/kivy/metrics.py", line 175, in dpi
     EventLoop.ensure_window()
   File "/usr/local/lib/python3.4/dist-packages/kivy/base.py", line 126, in ensure_window
     sys.exit(1)
 SystemExit: 1

** (main.py:17206): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-XjryLccyVq: Connection refused
[INFO   ] [Clipboard   ] Provider: gtk3(['clipboard_dbusklipper'] ignored)
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
[INFO   ] [Cutbuffer   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
[CRITICAL] [App         ] Unable to get a Window, abort.

```

**Comment by aron-bordin** [comment]
Hi @Immortalin 
Apparently your Kivy is missing some dependencies. Please install the latest kivy following this doc: https://kivy.org/docs/installation/installation-linux.html
