### ISSUE TITLE
Crash on first run

### ISSUE THREAD

**Issue by jraklovits** [kivy/kivy-designer#180]
Crashes on first run.  Satisfied the requirements from the github page and run main.py. 

Traceback (most recent call last):
   File "main.py", line 7, in <module>
     DesignerApp().run()
   File "C:\python27\lib\site-packages\kivy\app.py", line 828, in run
     runTouchApp()
   File "C:\python27\lib\site-packages\kivy\base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 622, in mainloop
     r = ExceptionManager.handle_exception(inst)
   File "C:\python27\lib\site-packages\kivy\base.py", line 86, in handle_exception
     r = handler.handle_exception(inst)
   File "C:\Users\jamie\Desktop\designer\kivy-designer\designer\app.py", line 1549, in handle_exception
     App.get_running_app().stop()
   File "C:\python27\lib\site-packages\kivy\app.py", line 837, in stop
     self.dispatch('on_stop')
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
   File "C:\Users\jamie\Desktop\designer\kivy-designer\designer\app.py", line 1575, in on_stop
     self.root.ui_creator.py_console.exit()
 AttributeError: 'NoneType' object has no attribute 'py_console'

**Comment by aron-bordin** [comment]
Hi @jraklovits 

Is kivy's dependencies installed on your system? 

Please, check the installation docs: https://kivy.org/docs/installation/installation-windows.html and give some feedback when possible

**Comment by jraklovits** [comment]
Kivy itself runs fine.  I can run anything while importing kivy.  I just get the crash when kivy-designer's main.py gets run.  I will probably uninstall the dependencies and reinstall them.  Maybe something didn't get installed quite right.

**Comment by aron-bordin** [comment]
Hi

This bug is not longer present in kivy-design master. Thank you for reporting.
