### ISSUE TITLE
Simply trying to move something on a new tabbed project

### ISSUE THREAD

**Issue by ccxx72** [kivy/kivy-designer#181]
## Environment Info

kivy: 1.9.1
pygments: 2.1
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 1.0.1
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-7-6.1.7601-SP1
Python: 3.4.3

## Traceback

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Python34\lib\site-packages\kivy\base.py", line 330, in idle
    self.dispatch_input()
  File "C:\Python34\lib\site-packages\kivy\base.py", line 315, in dispatch_input
    post_dispatch_input(*pop(0))
  File "C:\Python34\lib\site-packages\kivy\base.py", line 221, in post_dispatch_input
    listener.dispatch('on_motion', etype, me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python34\lib\site-packages\kivy\core\window\__init__.py", line 1030, in on_motion
    self.dispatch('on_touch_down', me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python34\lib\site-packages\kivy\core\window\__init__.py", line 1046, in on_touch_down
    if w.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python34\kivy-

**Comment by aron-bordin** [comment]
Hi @ccxx72 ,

thank you for reporting this bug. I fixed this bug here: https://github.com/kivy/kivy-designer/pull/184 . The traceback posted here is not complete, so I'm not sure it's the same bug with tabbed panel. If you get this error again, please, just let me know.
