### ISSUE TITLE
Kivy-designer crash on project loading

### ISSUE THREAD

**Issue by ringk** [kivy/kivy-designer#182]
Hi I just installed kivy-designer, I can launch it without any problem, Create a new project, but then when i try to load it, kivy designer crashes with this message: 

## Environment Info

kivy: 1.9.1
pygments: 2.1
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 1.0.1
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-10-10.0.10586
Python: 2.7.11

## Traceback

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Python27\lib\site-packages\kivy\base.py", line 327, in idle
    Clock.tick()
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 515, in tick
    self._process_events()
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 406, in tick
    ret = callback(self._dt)
  File "C:\Users\RingK\Programmazione\kivy-designer\designer\uix\kivy_console.py", line 285, in run_command
    self._run_command_list()
  File "C:\Users\RingK\Programmazione\kivy-designer\designer\uix\kivy_console.py", line 293, in _run_command_list
    self.stdin.write(self.command_list.pop(0))
  File "C:\Users\RingK\Programmazione\kivy-designer\designer\uix\kivy_console.py", line 842, in write
    self.obj.on_enter()
  File "C:\Users\RingK\Programmazione\kivy-designer\designer\uix\kivy_console.py", line 723, in on_enter
    ' directory:' + command[3:])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 83: ordinal not in range(128)

Am I doing something wrong?
Thanks in advance!

**Comment by aron-bordin** [comment]
Hi @ringk ,

Some users are facing this bug, I'll try to fix it asap.
Could you please share the path of your project ?

**Comment by ringk** [comment]
Hi!
Path is: C:\Users\user\AppData\Roaming\designer\.kivy-designer\new_proj (kivy-designer picked this, not me).
I'm on win 10 64bit.
Good luck with the bug fixing!

**Comment by aron-bordin** [comment]
Hi, 

this error may be fixed in master.
If you still getting this error please let me know.

Thx

**Comment by ringk** [comment]
Thanks, I'll try ASAP!

2016-02-19 1:50 GMT+01:00 Aron Barreira Bordin <notifications@github.com>:

**Comment by blutril** [comment]
Just got the same issue with the current master branch : 
## Environment Info

kivy: 1.9.1
pygments: 2.1.1
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 1.0.2
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-8-6.2.9200
Python: 2.7.10

## Traceback

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Python27\lib\site-packages\kivy\base.py", line 327, in idle
    Clock.tick()
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 515, in tick
    self._process_events()
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 406, in tick
    ret = callback(self._dt)
  File "C:\Users\patrick\Desktop\kivy-designer-master\designer\uix\kivy_console.py", line 285, in run_command
    self._run_command_list()
  File "C:\Users\patrick\Desktop\kivy-designer-master\designer\uix\kivy_console.py", line 293, in _run_command_list
    self.stdin.write(self.command_list.pop(0))
  File "C:\Users\patrick\Desktop\kivy-designer-master\designer\uix\kivy_console.py", line 842, in write
    self.obj.on_enter()
  File "C:\Users\patrick\Desktop\kivy-designer-master\designer\uix\kivy_console.py", line 723, in on_enter
    ' directory:' + command[3:])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 31: ordinal not in range(128)

**Comment by 093pk01** [comment]
I love the idea of it but the problem I am facing is, whenever I try to modify any of the properties in lower right corner, the whole program crashes.

**Comment by aron-bordin** [comment]
Hi all, this bug is fixed in master. 
Thanks
