### ISSUE TITLE
Crash Error when start project

### ISSUE THREAD

**Issue by aarondiazr** [kivy/kivy-designer#183]
## Environment Info

kivy: 1.9.1
pygments: 2.1
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 1.0.2
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-7-6.1.7601-SP1
Python: 2.7.11

## Traceback

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Python27\lib\site-packages\kivy\base.py", line 330, in idle
    self.dispatch_input()
  File "C:\Python27\lib\site-packages\kivy\base.py", line 315, in dispatch_input
    post_dispatch_input(*pop(0))
  File "C:\Python27\lib\site-packages\kivy\base.py", line 221, in post_dispatch_input
    listener.dispatch('on_motion', etype, me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python27\lib\site-packages\kivy\core\window\__init__.py", line 1030, in on_motion
    self.dispatch('on_touch_down', me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python27\lib\site-packages\kivy\core\window\__init__.py", line 1046, in on_touch_down
    if w.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Users\ironsistem\Programas\kivy\kivy-designer-master\designer\app.py", line 630, in on_touch_down
    return super(FloatLayout, self).on_touch_down(touch)
  File "C:\Python27\lib\site-packages\kivy\uix\widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python27\lib\site-packages\kivy\uix\widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python27\lib\site-packages\kivy\uix\widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python27\lib\site-packages\kivy\uix\widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Users\ironsistem\Programas\kivy\kivy-designer-master\designer\ui_creator.py", line 98, in on_touch_down
    return super(UICreator, self).on_touch_down(*args)
  File "C:\Python27\lib\site-packages\kivy\uix\widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python27\lib\site-packages\kivy\uix\widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python27\lib\site-packages\kivy\uix\widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Users\ironsistem\Programas\kivy\kivy-designer-master\designer\playground.py", line 1226, in on_touch_down
    App.get_running_app().focus_widget(target)
  File "C:\Users\ironsistem\Programas\kivy\kivy-designer-master\designer\app.py", line 1721, in focus_widget
    self.widget_focused = widget
  File "kivy\properties.pyx", line 408, in kivy.properties.Property.__set__ (kivy\properties.c:5114)
  File "kivy\properties.pyx", line 446, in kivy.properties.Property.set (kivy\properties.c:5876)
  File "kivy\properties.pyx", line 501, in kivy.properties.Property.dispatch (kivy\properties.c:6557)
  File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
  File "kivy\_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (kivy\_event.c:12696)
  File "kivy\_event.pyx", line 735, in kivy._event.EventDispatcher.__proxy_setter (kivy\_event.c:8285)
  File "kivy\properties.pyx", line 446, in kivy.properties.Property.set (kivy\properties.c:5876)
  File "kivy\properties.pyx", line 501, in kivy.properties.Property.dispatch (kivy\properties.c:6557)
  File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
  File "kivy\_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (kivy\_event.c:12696)
  File "C:\Users\ironsistem\Programas\kivy\kivy-designer-master\designer\eventviewer.py", line 173, in on_widget
    self.discover(value)
  File "C:\Users\ironsistem\Programas\kivy\kivy-designer-master\designer\eventviewer.py", line 191, in discover
    ip = self.build_for(event)
  File "C:\Users\ironsistem\Programas\kivy\kivy-designer-master\designer\eventviewer.py", line 309, in build_for
    info_message="Set event handler for event %s" % (name))
  File "C:\Python27\lib\site-packages\kivy\uix\textinput.py", line 500, in __init__
    super(TextInput, self).__init__(**kwargs)
  File "C:\Python27\lib\site-packages\kivy\uix\behaviors\focus.py", line 329, in __init__
    super(FocusBehavior, self).__init__(**kwargs)
  File "C:\Python27\lib\site-packages\kivy\uix\widget.py", line 312, in __init__
    super(Widget, self).__init__(**kwargs)
  File "kivy\_event.pyx", line 273, in kivy._event.EventDispatcher.__init__ (kivy\_event.c:5348)
  File "kivy\properties.pyx", line 408, in kivy.properties.Property.__set__ (kivy\properties.c:5114)
  File "kivy\properties.pyx", line 1390, in kivy.properties.AliasProperty.set (kivy\properties.c:23025)
  File "C:\Python27\lib\site-packages\kivy\uix\textinput.py", line 2854, in _set_text
    self._refresh_text(text)
  File "C:\Python27\lib\site-packages\kivy\uix\textinput.py", line 1792, in _refresh_text
    self._lines = _lines
  File "kivy\properties.pyx", line 408, in kivy.properties.Property.__set__ (kivy\properties.c:5114)
  File "kivy\properties.pyx", line 733, in kivy.properties.ListProperty.set (kivy\properties.c:11127)
  File "kivy\properties.pyx", line 446, in kivy.properties.Property.set (kivy\properties.c:5876)
  File "kivy\properties.pyx", line 501, in kivy.properties.Property.dispatch (kivy\properties.c:6557)
  File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
  File "kivy\_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (kivy\_event.c:12696)
  File "kivy\properties.pyx", line 1368, in kivy.properties.AliasProperty.trigger_change (kivy\properties.c:22563)
  File "kivy\properties.pyx", line 1374, in kivy.properties.AliasProperty.trigger_change (kivy\properties.c:22448)
  File "kivy\properties.pyx", line 501, in kivy.properties.Property.dispatch (kivy\properties.c:6557)
  File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
  File "kivy\_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (kivy\_event.c:12696)
  File "C:\Users\ironsistem\Programas\kivy\kivy-designer-master\designer\eventviewer.py", line 95, in on_text
    self.text)
  File "C:\Users\ironsistem\Programas\kivy\kivy-designer-master\designer\uix\kv_lang_area.py", line 687, in set_event_handler
    self.insert_text(indent_str + prop + ': ' + str(value))
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by aron-bordin** [comment]
Hi!

Are you creating a new project ? If so, which template are you using ?

**Comment by aarondiazr** [comment]
ScreenManager & Action Bar

**Comment by aron-bordin** [comment]
Do you see this bug when opening the project ? Or when clicking somewhere ? (I'm trying to reproduce it here to fix this issue)

**Comment by aarondiazr** [comment]
When clicking somewhere, because i'm trying select the widget to edit, but the app crash...
