### ISSUE TITLE
Sorry Kivi designer experienced an internal error

### ISSUE THREAD

**Issue by GammaSoul** [kivy/kivy-designer#187]
## Environment Info

kivy: 1.9.1
pygments: 2.1.1
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 1.0.2
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-7-6.1.7601-SP1
Python: 3.4.4

## Traceback

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Python34\lib\site-packages\kivy\base.py", line 327, in idle
    Clock.tick()
  File "C:\Python34\lib\site-packages\kivy\clock.py", line 515, in tick
    self._process_events()
  File "C:\Python34\lib\site-packages\kivy\clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "C:\Python34\lib\site-packages\kivy\clock.py", line 406, in tick
    ret = callback(self._dt)
  File "T:\Kivy\Projects\Kivy UI Designer\designer\project_manager.py", line 99, in _resume_watching
    if self._observer:
AttributeError: 'ProjectWatcher' object has no attribute '_observer'

End of Traceback

**Comment by aron-bordin** [comment]
Hi @GammaSoul,
Thank you for reporting, this bug is fixed in master.
