### ISSUE TITLE
After install pygame on macosx el capitan

### ISSUE THREAD

**Issue by Pyc0kw4k** [kivy/kivy-designer#193]
## Environment Info

kivy: 1.9.1
pygments: 2.1.1
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 1.0.2
six: 1.10.0
kivy-garden: 0.1.4

Platform: Darwin-15.3.0-x86_64-i386-64bit
Python: 2.7.10

## Traceback

Traceback (most recent call last):
  File "/Users/Pyc0kw4k/Lab/.virtualenvs/kivy/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 403, in mainloop
    self._mainloop()
  File "/Users/Pyc0kw4k/Lab/.virtualenvs/kivy/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 290, in _mainloop
    EventLoop.idle()
  File "/Users/Pyc0kw4k/Lab/.virtualenvs/kivy/lib/python2.7/site-packages/kivy/base.py", line 327, in idle
    Clock.tick()
  File "/Users/Pyc0kw4k/Lab/.virtualenvs/kivy/lib/python2.7/site-packages/kivy/clock.py", line 515, in tick
    self._process_events()
  File "/Users/Pyc0kw4k/Lab/.virtualenvs/kivy/lib/python2.7/site-packages/kivy/clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "/Users/Pyc0kw4k/Lab/.virtualenvs/kivy/lib/python2.7/site-packages/kivy/clock.py", line 406, in tick
    ret = callback(self._dt)
  File "/Users/Pyc0kw4k/Lab/.virtualenvs/kivy/lib/python2.7/site-packages/kivy/uix/label.py", line 352, in texture_update
    self._label.texture.bind()
  File "kivy/graphics/texture.pyx", line 761, in kivy.graphics.texture.Texture.bind (/private/var/folders/1q/5c1jbf9s6ksdt6p4_47tzwjc0000gn/T/pip-build-IHaXjA/kivy/kivy/graphics/texture.c:10121)
  File "kivy/graphics/texture.pyx", line 786, in kivy.graphics.texture.Texture.bind (/private/var/folders/1q/5c1jbf9s6ksdt6p4_47tzwjc0000gn/T/pip-build-IHaXjA/kivy/kivy/graphics/texture.c:9844)
  File "/Users/Pyc0kw4k/Lab/.virtualenvs/kivy/lib/python2.7/site-packages/kivy/core/text/__init__.py", line 628, in _texture_fill
    self.render(real=True)
  File "/Users/Pyc0kw4k/Lab/.virtualenvs/kivy/lib/python2.7/site-packages/kivy/core/text/markup.py", line 119, in render
    ret = self._render_real()
  File "/Users/Pyc0kw4k/Lab/.virtualenvs/kivy/lib/python2.7/site-packages/kivy/core/text/__init__.py", line 559, in _render_real
    data = self._render_end()
  File "/Users/Pyc0kw4k/Lab/.virtualenvs/kivy/lib/python2.7/site-packages/kivy/core/text/text_pil.py", line 57, in _render_end
    self._pil_im.mode.lower(), self._pil_im.tostring())
  File "/Users/Pyc0kw4k/Lab/.virtualenvs/kivy/lib/python2.7/site-packages/PIL/Image.py", line 695, in tostring
    "Please call tobytes() instead.")
Exception: tostring() has been removed. Please call tobytes() instead.

End of Traceback

**Comment by dessant** [comment]
The tostring issue has been fixed in kivy master https://github.com/kivy/kivy/commit/83a9528acc0f369c364a02812e49f47792152fd3.

You should also use sdl2 instead of pygame, follow the installation docs:
https://kivy.org/docs/installation/installation-osx.html
