### ISSUE TITLE
'NoneType' object has no attribute 'close_button'

### ISSUE THREAD

**Issue by mnural** [kivy/kivy-designer#195]
I can't launch kivy designer on ubuntu 15.10.
in terminal:
mnrl@mnrl-K54HR:~/Masaüstü/kivy-designer-master$ ./main.py
[INFO   ] [Logger      ] Record log in /home/mnrl/.kivy/logs/kivy_16-03-06_7.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010]
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Factory     ] 182 symbols loaded
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 11.0.2>
[INFO   ] [GL          ] OpenGL vendor <X.Org>
[INFO   ] [GL          ] OpenGL renderer <Gallium 0.4 on AMD CAICOS (DRM 2.40.0, LLVM 3.6.2)>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Clipboard   ] Provider: gtk3(['clipboard_dbusklipper'] ignored)
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
[INFO   ] [Cutbuffer   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
 Traceback (most recent call last):
   File "./main.py", line 12, in <module>
     DesignerApp().run()
   File "/usr/lib/python2.7/dist-packages/kivy/app.py", line 802, in run
     root = self.build()
   File "/home/mnrl/Masaüstü/kivy-designer-master/designer/app.py", line 1708, in build
     self.root = Designer()
   File "/home/mnrl/Masaüstü/kivy-designer-master/designer/app.py", line 204, in __init__
     self.designer_settings = DesignerSettings()
   File "/home/mnrl/Masaüstü/kivy-designer-master/designer/designer_settings.py", line 50, in __init__
     super(DesignerSettings, self).__init__(*kwargs)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/settings.py", line 905, in __init__
     self.add_interface()
   File "/usr/lib/python2.7/dist-packages/kivy/uix/settings.py", line 935, in add_interface
     interface = cls()
   File "/usr/lib/python2.7/dist-packages/kivy/uix/settings.py", line 687, in __init__
     self.menu.close_button.bind(
 AttributeError: 'NoneType' object has no attribute 'close_button'

all requirements are installed and up to date.

**Comment by yvznvr** [comment]
I cant launch too on ubuntu 16.04 and 14.04,

''[INFO   ] [Logger      ] Record log in /home/yavuz/.kivy/logs/kivy_16-06-18_0.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v2.7.11+ (default, Apr 17 2016, 14:00:29) 
[GCC 5.3.1 20160413]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 11.2.0>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Haswell Mobile >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 /usr/local/lib/python2.7/dist-packages/kivy/core/clipboard/clipboard_gtk3.py:14: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
   from gi.repository import Gtk, Gdk
[INFO   ] [Clipboard   ] Provider: gtk3(['clipboard_dbusklipper'] ignored)
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
[INFO   ] [Cutbuffer   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
 Traceback (most recent call last):
   File "main.py", line 12, in <module>
     DesignerApp().run()
   File "/usr/local/lib/python2.7/dist-packages/kivy/app.py", line 802, in run
     root = self.build()
   File "/home/yavuz/kivy-designer/designer/app.py", line 1713, in build
     self.root = Designer()
   File "/home/yavuz/kivy-designer/designer/app.py", line 206, in __init__
     self.designer_settings = DesignerSettings()
   File "/home/yavuz/kivy-designer/designer/designer_settings.py", line 49, in __init__
     super(DesignerSettings, self).__init__(*kwargs)
   File "/usr/local/lib/python2.7/dist-packages/kivy/uix/settings.py", line 906, in __init__
     self.add_interface()
   File "/usr/local/lib/python2.7/dist-packages/kivy/uix/settings.py", line 936, in add_interface
''

**Comment by mustafa-altinisik** [comment]
same error on me

**Comment by trDjango** [comment]
same error:(((
