### ISSUE TITLE
Just playing with kivy designer and a crash occured.

### ISSUE THREAD

**Issue by pipoupiwam** [kivy/kivy-designer#198]
## Environment Info

kivy: 1.9.1
pygments: 2.1.3
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 1.0.2
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-8-6.2.9200
Python: 2.7.9

## Traceback

Traceback (most recent call last):
  File "C:\Users\micha\kivy191\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Users\micha\kivy191\lib\site-packages\kivy\core\window\window_sdl2.py", line 552, in _mainloop
    self.modifiers):
  File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7654)
  File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
  File "kivy\_event.pyx", line 1148, in kivy._event.EventObservers._dispatch (kivy\_event.c:13023)
  File "C:\Users\micha\kivy191\lib\site-packages\kivy\core\window\__init__.py", line 159, in _on_window_key_down
    return self.dispatch('on_key_down', keycode, text, modifiers)
  File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7654)
  File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
  File "kivy\_event.pyx", line 1148, in kivy._event.EventObservers._dispatch (kivy\_event.c:13023)
  File "C:\Users\micha\kivydesigner\kivy-designer\designer\playground.py", line 1065, in _on_keyboard_down
    self.do_undo()
  File "C:\Users\micha\kivydesigner\kivy-designer\designer\pla

**Comment by aron-bordin** [comment]
Hi,

I'm closing this bug report because the traceback is not complete. Please, read the Bug Reporter instruction, a complete report must end with "End of Traceback" in the last line. With this report we are not able to identify what is wrong here.

Thank you.
