### ISSUE TITLE
Screen Manager & ActionBar new Project error

### ISSUE THREAD

**Issue by cllCodeGeek** [kivy/kivy-designer#207]
## Environment Info

kivy: 1.9.2.dev0
pygments: 2.1.3
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 1.0.2
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-10-10.0.10586
Python: 2.7.11

## Traceback

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Python27\lib\site-packages\kivy\base.py", line 327, in idle
    Clock.tick()
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 515, in tick
    self._process_events()
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 406, in tick
    ret = callback(self._dt)
  File "C:\Users\cll\Desktop\kivy-designer\designer\uix\kivy_console.py", line 291, in run_command
    self._run_command_list()
  File "C:\Users\cll\Desktop\kivy-designer\designer\uix\kivy_console.py", line 299, in _run_command_list
    self.stdin.write(self.command_list.pop(0))
  File "C:\Users\cll\Desktop\kivy-designer\designer\uix\kivy_console.py", line 855, in write
    self.obj.on_enter()
  File "C:\Users\cll\Desktop\kivy-designer\designer\uix\kivy_console.py", line 734, in on_enter
    ' dire

**Comment by aron-bordin** [comment]
Hi,

Sorry, but your traceback is not complete. Please, feel free to reopen this issue if you get the this issue again, and copy the full traceback, so we can identify the problem .

Thank you
