### ISSUE TITLE
Error after creating a new project "Carousel and Action Bar"

### ISSUE THREAD

**Issue by andryfailli** [kivy/kivy-designer#209]
## Environment Info

kivy: 1.9.1
pygments: 2.1.3
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 1.0.2
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-7-6.1.7601-SP1
Python: 2.7.11

## Traceback

Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Anaconda2\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Anaconda2\lib\site-packages\kivy\base.py", line 327, in idle
    Clock.tick()
  File "C:\Anaconda2\lib\site-packages\kivy\clock.py", line 515, in tick
    self._process_events()
  File "C:\Anaconda2\lib\site-packages\kivy\clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "C:\Anaconda2\lib\site-packages\kivy\clock.py", line 406, in tick
    ret = callback(self._dt)
  File "C:\Users\Andrea\git\kivy-designer\designer\uix\kivy_console.py", line 291, in run_command
    self._run_command_list()
  File "C:\Users\Andrea\git\kivy-designer\designer\uix\kivy_console.py", line 299, in _run_command_list
    self.stdin.write(self.command_list.pop(0))
  File "C:\Users\Andrea\git\kivy-designer\designer\uix\kivy_console.py", line 855, in write
    self.obj.on_enter()
  File "C:\Users\Andrea\git\kivy-designer\designer\uix\kivy_console.py", line 734, in on_enter
    ' directory:' + command[3:])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 83: ordinal not in range(128)

End of Traceback

**Comment by aron-bordin** [comment]
Hi, 
I'm closing this issue because the same bug was reported here: https://github.com/kivy/kivy-designer/issues/182
Thx
