### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9

### ISSUE THREAD

**Issue by OlivierDz** [kivy/kivy-designer#210]
Hello,
 
I’m trying to create a new project on kivy designer.
But there is always this internal error.
What’s the solution ?
 
Thank you!

## Environment Info

kivy: 1.9.1
pygments: 2.1.3
docutils: 0.12
watchdog: 0.8.2
jedi: 0.9.0
gitpython: 1.0.2
six: 1.10.0
kivy-garden: 0.1.4
 
Platform: Windows-7-6.1.7601-SP1
Language French
Python: 2.7.11
 

## Traceback
 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 620, in mainloop
    self._mainloop()
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 363, in _mainloop
    EventLoop.idle()
  File "C:\Python27\lib\site-packages\kivy\base.py", line 328, in idle
    Clock.tick()
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 515, in tick
    self._process_events()
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 406, in tick
    ret = callback(self._dt)
  File "C:\kivy-designer\designer\uix\kivy_console.py", line 291, in run_command
    self._run_command_list()
  File "C:\kivy-designer\designer\uix\kivy_console.py", line 299, in _run_command_list
    self.stdin.write(self.command_list.pop(0))
  File "C:\kivy-designer\designer\uix\kivy_console.py", line 855, in write
    self.obj.on_enter()
  File "C:\kivy-designer\designer\uix\kivy_console.py", line 734, in on_enter
    ' directory:' + command[3:])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 53: ordinal not in range(128)

 
 

End of Traceback

**Comment by OlivierDz** [comment]
In other PC, the same error...
When I create a new project whatever the template.

## Environment Info

kivy: 1.9.2.dev0
pygments: 2.1.3
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 1.0.2
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-8-6.2.9200
Python: 2.7.11

## Traceback

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 622, in mainloop
    self._mainloop()
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 365, in _mainloop
    EventLoop.idle()
  File "C:\Python27\lib\site-packages\kivy\base.py", line 327, in idle
    Clock.tick()
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 512, in tick
    self._process_events()
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 644, in _process_events
    event.tick(self._last_tick, remove)
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 403, in tick
    ret = callback(self._dt)
  File "C:\kivy-designer\designer\uix\kivy_console.py", line 286, in run_command
    self._run_command_list()
  File "C:\kivy-designer\designer\uix\kivy_console.py", line 294, in _run_command_list
    self.stdin.write(self.command_list.pop(0))
  File "C:\kivy-designer\designer\uix\kivy_console.py", line 850, in write
    self.obj.on_enter()
  File "C:\kivy-designer\designer\uix\kivy_console.py", line 729, in on_enter
    ' directory:' + command[3:])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 53: ordinal not in range(128)

**Comment by aron-bordin** [comment]
Hi,

This bug was reported here: https://github.com/kivy/kivy-designer/issues/182
I'm closing this issue to remove the duplicate, but thank you for posting.
