### ISSUE TITLE
I got this error can someone help

### ISSUE THREAD

**Issue by MeDzIeDaRbI** [kivy/kivy-designer#217]
## Environment Info

kivy: 1.9.1
pygments: 2.1.3
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 1.0.2
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-7-6.1.7601-SP1
Python: 2.7.2

## Traceback

Traceback (most recent call last):
  File "C:\python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\python27\lib\site-packages\kivy\base.py", line 327, in idle
    Clock.tick()
  File "C:\python27\lib\site-packages\kivy\clock.py", line 515, in tick
    self._process_events()
  File "C:\python27\lib\site-packages\kivy\clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "C:\python27\lib\site-packages\kivy\clock.py", line 406, in tick
    ret = callback(self._dt)
  File "C:\Users\zied\Desktop\kivy-designer-master\designer\uix\kivy_console.py", line 291, in run_command
    self._run_command_list()
  File "C:\Users\zied\Desktop\kivy-designer-master\designer\uix\kivy_console.py", line 299, in _run_command_list
    self.stdin.write(self.command_list.pop(0))
  File "C:\Users\zied\Desktop\kivy-designer-master\designer\uix\kivy_console.py", line 855, in write
    self.obj.on_enter()
  File "C:\Users\zied\Desktop\kivy-designer-master\designer\uix\kivy_console.py", line 734, in on_ent

**Comment by aron-bordin** [comment]
Hi, sorry, but your traceback is incomplete. I made some modifications on master, please, download kivy designer again, and if you face this same issue, reopen this issue with the traceback.

Thank you

**Comment by MeDzIeDaRbI** [comment]
Thank you for the response

But I got the same problem again.

________________________________
De : Aron Barreira Bordin <notifications@github.com>
Envoyé : mardi 10 mai 2016 04:46:19
À : kivy/kivy-designer
Cc : Med Zied ARBI; Author
Objet : Re: [kivy/kivy-designer] I got this error can someone help (#217)


Hi, sorry, but your traceback is incomplete. I made some modifications on master, please, download kivy designer again, and if you face this same issue, reopen this issue with the traceback.

Thank you

-

**Comment by aron-bordin** [comment]
Hi, please, If you get the problem again, use the "copy to clipboard" button in the bug reporter and paste the result here. I was not able to identify the bug because the report above is not complete.

**Comment by aron-bordin** [comment]
I saw your new issue, I'll check the problem there. Thank you
