### ISSUE TITLE
Kivy issue when starting new project.

### ISSUE THREAD

**Issue by MeDzIeDaRbI** [kivy/kivy-designer#218]
I got this error while trying to start a new project.
Is there any fix ?
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 53
```
## Environment Info

kivy: 1.9.1
pygments: 2.1.3
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 1.0.2
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-7-6.1.7601-SP1
Python: 2.7.2

## Traceback

Traceback (most recent call last):
  File "C:\python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\python27\lib\site-packages\kivy\base.py", line 327, in idle
    Clock.tick()
  File "C:\python27\lib\site-packages\kivy\clock.py", line 515, in tick
    self._process_events()
  File "C:\python27\lib\site-packages\kivy\clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "C:\python27\lib\site-packages\kivy\clock.py", line 406, in tick
    ret = callback(self._dt)
  File "C:\Users\zied\Desktop\kivy-designer-master\designer\uix\kivy_console.py", line 291, in run_command
    self._run_command_list()
  File "C:\Users\zied\Desktop\kivy-designer-master\designer\uix\kivy_console.py", line 299, in _run_command_list
    self.stdin.write(self.command_list.pop(0))
  File "C:\Users\zied\Desktop\kivy-designer-master\designer\uix\kivy_console.py", line 855, in write
    self.obj.on_enter()
  File "C:\Users\zied\Desktop\kivy-designer-master\designer\uix\kivy_console.py", line 734, in on_ent
```

**Comment by aron-bordin** [comment]
Hi @MeDzIeDaRbI 
This traceback is not yet complete. Please, check the bug reporter instructions because the last line of the traceback must have "End of Traceback".

When you face this issue again, use the "Copy to clipboard" button and add the result in a new comment so we can identify what is wrong.

Thank you

**Comment by aron-bordin** [comment]
Hi,
This bug report is not complete, so I'm closing it. Also, check the master, I've fixed a similar problem, but I'm not sure if it's the problem if you are getting.
Thanks
