### ISSUE TITLE
error

### ISSUE THREAD

**Issue by maryito** [kivy/kivy-designer#222]
## Environment Info

kivy: 1.9.1
pygments: 2.1.3
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 2.0.3
six: 1.10.0
kivy-garden: 0.1.4

Platform: Linux-4.4.9-300.fc23.x86_64-x86_64-with-fedora-23-Twenty_Three
Python: 3.4.3

## Traceback

Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/kivy/core/window/window_pygame.py", line 403, in mainloop
    self._mainloop()
  File "/usr/lib64/python3.4/site-packages/kivy/core/window/window_pygame.py", line 290, in _mainloop
    EventLoop.idle()
  File "/usr/lib64/python3.4/site-packages/kivy/base.py", line 330, in idle
    self.dispatch_input()
  File "/usr/lib64/python3.4/site-packages/kivy/base.py", line 315, in dispatch_input
    post_dispatch_input(*pop(0))
  File "/usr/lib64/python3.4/site-packages/kivy/base.py", line 221, in post_dispatch_input
    listener.dispatch('on_motion', etype, me)
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-b9iwvmv7/kivy/kivy/_event.c:7699)
  File "/usr/lib64/python3.4/site-packages/kivy/core/window/__init__.py", line 1030, in on_motion
    self.dispatch('on_touch_down', me)
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-b9iwvmv7/kivy/kivy/_event.c:7699)
  File "/usr/lib64/python3.4/site-packages/kivy/core/window/__init__.py", line 1046, in on_touch_down
    if w.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-b9iwvmv7/kivy/kivy/_event.c:7699)
  File "/home/maryito/kivy-designer/designer/app.py", line 671, in on_touch_down
    return super(FloatLayout, self).on_touch_down(touch)
  File "/usr/lib64/python3.4/site-packages/kivy/uix/widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-b9iwvmv7/kivy/kivy/_event.c:7699)
  File "/usr/lib64/python3.4/site-packages/kivy/uix/widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-b9iwvmv7/kivy/kivy/_event.c:7699)
  File "/usr/lib64/python3.4/site-packages/kivy/uix/widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-b9iwvmv7/kivy/kivy/_event.c:7699)
  File "/usr/lib64/python3.4/site-packages/kivy/uix/widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-b9iwvmv7/kivy/kivy/_event.c:7699)
  File "/home/maryito/kivy-designer/designer/ui_creator.py", line 98, in on_touch_down
    return super(UICreator, self).on_touch_down(*args)
  File "/usr/lib64/python3.4/site-packages/kivy/uix/widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-b9iwvmv7/kivy/kivy/_event.c:7699)
  File "/usr/lib64/python3.4/site-packages/kivy/uix/widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-b9iwvmv7/kivy/kivy/_event.c:7699)
  File "/usr/lib64/python3.4/site-packages/kivy/uix/widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-b9iwvmv7/kivy/kivy/_event.c:7699)
  File "/home/maryito/kivy-designer/designer/playground.py", line 1246, in on_touch_down
    App.get_running_app().focus_widget(target)
  File "/home/maryito/kivy-designer/designer/app.py", line 1827, in focus_widget
    self.widget_focused = widget
  File "kivy/properties.pyx", line 408, in kivy.properties.Property.__set__ (/tmp/pip-build-b9iwvmv7/kivy/kivy/properties.c:5114)
  File "kivy/properties.pyx", line 446, in kivy.properties.Property.set (/tmp/pip-build-b9iwvmv7/kivy/kivy/properties.c:5876)
  File "kivy/properties.pyx", line 501, in kivy.properties.Property.dispatch (/tmp/pip-build-b9iwvmv7/kivy/kivy/properties.c:6557)
  File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (/tmp/pip-build-b9iwvmv7/kivy/kivy/_event.c:13497)
  File "kivy/_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (/tmp/pip-build-b9iwvmv7/kivy/kivy/_event.c:12696)
  File "kivy/_event.pyx", line 735, in kivy._event.EventDispatcher.__proxy_setter (/tmp/pip-build-b9iwvmv7/kivy/kivy/_event.c:8285)
  File "kivy/properties.pyx", line 446, in kivy.properties.Property.set (/tmp/pip-build-b9iwvmv7/kivy/kivy/properties.c:5876)
  File "kivy/properties.pyx", line 501, in kivy.properties.Property.dispatch (/tmp/pip-build-b9iwvmv7/kivy/kivy/properties.c:6557)
  File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (/tmp/pip-build-b9iwvmv7/kivy/kivy/_event.c:13497)
  File "kivy/_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (/tmp/pip-build-b9iwvmv7/kivy/kivy/_event.c:12696)
  File "/home/maryito/kivy-designer/designer/eventviewer.py", line 175, in on_widget
    self.discover(value)
  File "/home/maryito/kivy-designer/designer/eventviewer.py", line 193, in discover
    ip = self.build_for(event)
  File "/home/maryito/kivy-designer/designer/eventviewer.py", line 307, in build_for
    text = self.kv_code_input.get_property_value(self.widget, name)
  File "/home/maryito/kivy-designer/designer/uix/kv_lang_area.py", line 561, in get_property_value
    widget_line = lines[widget_lineno]
IndexError: list index out of range

End of Traceback

**Comment by aron-bordin** [comment]
Hi @maryito, thank you for reporting this bug. I'm closing this issue because this same problem was reported here: https://github.com/kivy/kivy-designer/issues/221

Thx,
Aron
