### ISSUE TITLE
Bug: when creating a new file "sample.py"

### ISSUE THREAD

**Issue by Theydarking** [kivy/kivy-designer#226]
## Environment Info

kivy: 1.9.1
pygments: 2.1.3
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 2.0.5
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-8-6.2.9200
Python: 3.4.3

## Traceback

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Python34\lib\site-packages\kivy\base.py", line 330, in idle
    self.dispatch_input()
  File "C:\Python34\lib\site-packages\kivy\base.py", line 315, in dispatch_input
    post_dispatch_input(*pop(0))
  File "C:\Python34\lib\site-packages\kivy\base.py", line 221, in post_dispatch_input
    listener.dispatch('on_motion', etype, me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python34\lib\site-packages\kivy\core\window\__init__.py", line 1030, in on_motion
    self.dispatch('on_touch_down', me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python34\lib\site-packages\kivy\core\window\__init__.py", line 1046, in on_touch_down
    if w.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python34\lib\s

**Comment by aron-bordin** [comment]
Hi @Theydarking you traceback is incomplete, can you comment it here using the clipboard ?

**Comment by Theydarking** [comment]
I closed the windows, if it happens another Time I'll send it

**Comment by Theydarking** [comment]
## Environment Info

kivy: 1.9.1
pygments: 2.1.3
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 2.0.5
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-8-6.2.9200
Python: 3.4.3

## Traceback

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Python34\lib\site-packages\kivy\base.py", line 330, in idle
    self.dispatch_input()
  File "C:\Python34\lib\site-packages\kivy\base.py", line 315, in dispatch_input
    post_dispatch_input(*pop(0))
  File "C:\Python34\lib\site-packages\kivy\base.py", line 281, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python34\lib\site-packages\kivy\uix\behaviors\button.py", line 138, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7654)
  File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
  File "kivy\_event.pyx", line 1108, in kivy._event.EventObservers._dispatch (kivy\_event.c:12329)
  File "C:\Python34\lib\site-packages\kivy\lang.py", line 1557, in custom_callback
    exec(__kvlang__.co_value, idmap)
  File "<string>", line 88, in <module>
  File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7654)
  File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
  File "kivy\_event.pyx", line 1148, in kivy._event.EventObservers._dispatch (kivy\_event.c:13023)
  File "C:\Users\ouifa\Desktop\kivyDesigner\designer\app.py", line 1032, in save_project
    self._perform_save_as(save_as_browser, exit_on_save=exit_on_save)
  File "C:\Users\ouifa\Desktop\kivyDesigner\designer\app.py", line 1057, in _perform_save_as
    self._perform_open(proj_dir)
  File "C:\Users\ouifa\Desktop\kivyDesigner\designer\app.py", line 945, in _perform_open
    project = self.project_manager.open_project(file_path)
  File "C:\Users\ouifa\Desktop\kivyDesigner\designer\project_manager.py", line 511, in open_project
    p.open()
  File "C:\Users\ouifa\Desktop\kivyDesigner\designer\project_manager.py", line 220, in open
    self.parse()
  File "C:\Users\ouifa\Desktop\kivyDesigner\designer\project_manager.py", line 276, in parse
    self.parse_py(py)
  File "C:\Users\ouifa\Desktop\kivyDesigner\designer\project_manager.py", line 398, in parse_py
    src = open(path, 'r').read()
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 308: character maps to <undefined>


End of Traceback
