### ISSUE TITLE
kivy designer is so buggy ... 

### ISSUE THREAD

**Issue by Theydarking** [kivy/kivy-designer#227]
## Environment Info

kivy: 1.9.1
pygments: 2.1.3
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 2.0.5
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-8-6.2.9200
Python: 3.4.3

## Traceback

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Python34\lib\site-packages\kivy\base.py", line 330, in idle
    self.dispatch_input()
  File "C:\Python34\lib\site-packages\kivy\base.py", line 315, in dispatch_input
    post_dispatch_input(*pop(0))
  File "C:\Python34\lib\site-packages\kivy\base.py", line 274, in post_dispatch_input
    wid.dispatch('on_touch_move', me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Users\ouifa\Desktop\kivyDesigner\designer\playground.py", line 238, in on_touch_move
    self.widget.parent.remove_widget(self.widget)
  File "C:\Python34\lib\site-packages\kivy\uix\screenmanager.py", line 894, in remove_widget
    'screens added via add_widget! use real_remove_widget.')
kivy.uix.screenmanager.ScreenManagerException: ScreenManager uses remove_widget only to removescreens added via add_widget! use real_remove_widget.

End of Traceback

**Comment by Theydarking** [comment]
Aron, do you think that kivy-designer is robust enough at this moment to develope a complete app ? Or should I wait ?

**Comment by aron-bordin** [comment]
Hi, 
kivy-designer is still a work in progress IDE, we've not even released the first beta version (and I'm a quite busy these months, so I'll just continue developing it in August).

**Comment by Theydarking** [comment]
I saw your blog, good job man

**Comment by aron-bordin** [comment]
thanks for all bug reports, I'll working in them when possible :+1:
