### ISSUE TITLE
Error on create new project

### ISSUE THREAD

**Issue by ats-sda** [kivy/kivy-designer#235]
## Environment Info

kivy: 1.9.1
pygments: 2.1.3
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 2.0.6
six: 1.10.0
kivy-garden: 0.1.4

Platform: Linux-4.4.0-24-generic-x86_64-with-Ubuntu-16.04-xenial
Python: 2.7.11+

## Traceback

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 327, in idle
    Clock.tick()
  File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 515, in tick
    self._process_events()
  File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 406, in tick
    ret = callback(self._dt)
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 255, in create_window
    super(WindowSDL, self).create_window()
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/__init__.py", line 907, in create_window
    self.dispatch('on_resize', *self.system_size)
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7699)
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/__init__.py", line 1075, in on_resize
    self.update_viewport()
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/__init__.py", line 1124, in update_viewport
    self.update_childsize()
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/__init__.py", line 1133, in update_childsize
    w.size = shw * width, shh * height
  File "kivy/properties.pyx", line 408, in kivy.properties.Property.__set__ (kivy/properties.c:5114)
  File "kivy/properties.pyx", line 1260, in kivy.properties.ReferenceListProperty.set (kivy/properties.c:20180)
  File "kivy/properties.pyx", line 424, in kivy.properties.Property.set (kivy/properties.c:5997)
  File "kivy/properties.pyx", line 446, in kivy.properties.Property.set (kivy/properties.c:5876)
  File "kivy/properties.pyx", line 501, in kivy.properties.Property.dispatch (kivy/properties.c:6557)
  File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy/_event.c:13497)
  File "kivy/_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (kivy/_event.c:12696)
  File "/home/jegidio/kivy-designer/designer/app.py", line 511, in on_height
    if self.actionbar and self.statusbar:
  File "kivy/weakproxy.pyx", line 62, in kivy.weakproxy.WeakProxy.__nonzero__ (kivy/weakproxy.c:2206)
  File "kivy/weakproxy.pyx", line 15, in kivy.weakproxy.WeakProxy.__ref__ (kivy/weakproxy.c:1042)
ReferenceError: weakly-referenced object no longer exists

End of Traceback

**Comment by MysticMight** [comment]
It looks like the popup window (or maybe another widget) is being garbage collected. To fix this issue use a strong link e.g. "popup_window: popup_window.__self__" in the following .kv example:
```kivy
    BoxLayout:
        orientation: 'vertical'
        #Strong links, to stop garbage collection of popup windows
        popup_window: popup_window.__self__
        Popup:
            id: popup_window
```
I've experienced this issue with my own kivy app before.
