### ISSUE TITLE
Error on edit statusbar properties

### ISSUE THREAD

**Issue by ats-sda** [kivy/kivy-designer#236]
## Environment Info

kivy: 1.9.1
pygments: 2.1.3
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 2.0.6
six: 1.10.0
kivy-garden: 0.1.4

Platform: Linux-4.4.0-24-generic-x86_64-with-Ubuntu-16.04-xenial
Python: 2.7.11+
## Traceback

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 327, in idle
    Clock.tick()
  File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 515, in tick
    self._process_events()
  File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 406, in tick
    ret = callback(self._dt)
  File "/home/jegidio/kivy-designer/designer/helper_functions.py", line 193, in wrapper
    f(_args, *_kwargs)
  File "/home/jegidio/kivy-designer/designer/app.py", line 995, in save_project
    show_message('Project saved!', 5, 'info')
  File "/home/jegidio/kivy-designer/designer/helper_functions.py", line 151, in show_message
    d.statusbar.show_message(_args, *_kwargs)
  File "kivy/weakproxy.pyx", line 19, in kivy.weakproxy.WeakProxy.__getattr__ (kivy/weakproxy.c:1143)
  File "kivy/weakproxy.pyx", line 15, in kivy.weakproxy.WeakProxy.**ref** (kivy/weakproxy.c:1042)
ReferenceError: weakly-referenced object no longer exists

End of Traceback

**Comment by Theydarking** [comment]
Same problem : 
 Traceback (most recent call last):
   File "C:\Users\ouifa\Desktop\Project_True\runner.py", line 79, in <module>
     MyApp().run()
   File "C:\python34\lib\site-packages\kivy\app.py", line 828, in run
     runTouchApp()
   File "C:\python34\lib\site-packages\kivy\base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
     self._mainloop()
   File "C:\python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 456, in _mainloop
     self._size = self._win.window_size
   File "kivy\properties.pyx", line 408, in kivy.properties.Property.__set__ (kivy\properties.c:5114)
   File "kivy\properties.pyx", line 733, in kivy.properties.ListProperty.set (kivy\properties.c:11127)
   File "kivy\properties.pyx", line 446, in kivy.properties.Property.set (kivy\properties.c:5876)
   File "kivy\properties.pyx", line 501, in kivy.properties.Property.dispatch (kivy\properties.c:6557)
   File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
   File "kivy\_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (kivy\_event.c:12696)
   File "kivy\properties.pyx", line 1368, in kivy.properties.AliasProperty.trigger_change (kivy\properties.c:22563)
   File "kivy\properties.pyx", line 1374, in kivy.properties.AliasProperty.trigger_change (kivy\properties.c:22448)
   File "kivy\properties.pyx", line 501, in kivy.properties.Property.dispatch (kivy\properties.c:6557)
   File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
   File "kivy\_event.pyx", line 1106, in kivy._event.EventObservers._dispatch (kivy\_event.c:12301)
   File "C:\python34\lib\site-packages\kivy\lang.py", line 1566, in call_fn
     e_value = eval(value, idmap)
   File "C:\Users\ouifa\Desktop\Project_True\container_kvs\User.kv", line 19, in <module>
     width: app.root_window.size[0]-root.height_value
   File "kivy\weakproxy.pyx", line 19, in kivy.weakproxy.WeakProxy.__getattr__ (kivy\weakproxy.c:1143)
   File "kivy\weakproxy.pyx", line 15, in kivy.weakproxy.WeakProxy.__ref__ (kivy\weakproxy.c:1042)
 ReferenceError: weakly-referenced object no longer exists
