### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by KJHamblin** [kivy/kivy-designer#244]
## Environment Info

kivy: 1.9.1
pygments: 2.1.3
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 2.0.8
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-7-6.1.7601-SP1
Python: 2.7.12

## Traceback

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Python27\lib\site-packages\kivy\base.py", line 330, in idle
    self.dispatch_input()
  File "C:\Python27\lib\site-packages\kivy\base.py", line 315, in dispatch_input
    post_dispatch_input(*pop(0))
  File "C:\Python27\lib\site-packages\kivy\base.py", line 221, in post_dispatch_input
    listener.dispatch('on_motion', etype, me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python27\lib\site-packages\kivy\core\window\__init__.py", line 1030, in on_motion
    self.dispatch('on_touch_down', me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python27\lib\site-packages\kivy\core\window\__init__.py", line 1046, in on_touch_down
    if w.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Program Fil

**Comment by aron-bordin** [comment]
Hi. This bug report is not complete. Please, check the bug reporters instructions and post the full log.

Thanks
