### ISSUE TITLE
actionbar > scroll > boxlayout

### ISSUE THREAD

**Issue by obuhhh** [kivy/kivy-designer#245]
## Environment Info

kivy: 1.9.1
pygments: 2.1.3
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 2.0.8
six: 1.10.0
kivy-garden: 0.1.4

Platform: Linux-4.4.0-34-generic-x86_64-with-Ubuntu-16.04-xenial
Python: 3.5.2

## Traceback

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "/usr/lib/python3/dist-packages/kivy/base.py", line 327, in idle
    Clock.tick()
  File "/usr/lib/python3/dist-packages/kivy/clock.py", line 515, in tick
    self._process_events()
  File "/usr/lib/python3/dist-packages/kivy/clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "/usr/lib/python3/dist-packages/kivy/clock.py", line 406, in tick
    ret = callback(self._dt)
  File "/home/obuhhh/kivy-designer/designer/nodetree.py", line 109, in _refresh
    self._clear_tree(self.tree, self.tree.root)
  File "/home/obuhhh/kivy-designer/designer/nodetree.py", line 102, in _clear_tree
    self._clear_tree(tree, n)
  File "/home/obuhhh/kivy-designer/designer/nodetree.py", line 102, in _clear_tree
    self._clear_tree(tree, n)
  File "/home/obuhhh/kivy-designer/designer/nodetree.py", line 102, in _clear_tree
    self._clear_tree(tree, n)
  File "/home/obuhhh/kivy-designer/designer/nodetree.py", line 101, in _clear_tree
    for n in node.nodes[:]:
  File "kivy/weakproxy.pyx", line 19, in kivy.weakproxy.WeakProxy.__getattr__ (kivy/weakproxy.c:1143)
  File "kivy/weakproxy.pyx", line 15, in kivy.weakproxy.WeakProxy.__ref__ (kivy/weakproxy.c:1042)
ReferenceError: weakly-referenced object no longer exists

End of Traceback

**Comment by MysticMight** [comment]
This may be a good reference for solving this issue: https://groups.google.com/forum/#!topic/kivy-users/0c4rTWU7glc
I have a weakly-referenced error before with a kivy popup and I fixed it by making strong links
e.g.  (in .kv file)
BoxLayout:
    orientation: 'vertical'
    id: mainBox
    #Strong links, to stop garbage collection of popup windows
    popup_input_dialog: input_dialog.__self__
    Popup:
        id: popup_input_dialog
        size_hint: (.8, .8)
        title: "Input dialog"
        on_parent:
            # Make popup disappear immediately
            if self.parent == mainBox: self.parent.remove_widget(self)
    #....other kivy code....

Hopefully this is helpful.
