### ISSUE TITLE
UnicodeDecodeError in windows

### ISSUE THREAD

**Issue by mustafaklcmk** [kivy/kivy-designer#248]
## Environment Info

kivy: 1.9.1
pygments: 2.1.3
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 2.0.8
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-10-10.0.10586
Python: 2.7.11

## Traceback

Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "c:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "c:\Python27\lib\site-packages\kivy\base.py", line 327, in idle
    Clock.tick()
  File "c:\Python27\lib\site-packages\kivy\clock.py", line 515, in tick
    self._process_events()
  File "c:\Python27\lib\site-packages\kivy\clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "c:\Python27\lib\site-packages\kivy\clock.py", line 406, in tick
    ret = callback(self._dt)
  File "C:\kivy-designer-master\designer\app.py", line 1761, in _setup
    self.root.fill_select_profile_menu()
  File "C:\kivy-designer-master\designer\app.py", line 1121, in fill_select_profile_menu
    'default_profile', '') == config_path:
  File "c:\Python27\lib\site-packages\kivy\config.py", line 462, in getdefault
    return self.get(section, option)
  File "c:\Python27\lib\site-packages\kivy\config.py", line 436, in get
    return value.decode('utf-8')
  File "c:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfd in position 18: invalid start byte

End of Traceback

**Comment by mustafaklcmk** [comment]
I solved this problem as follows:

in kivy direttory, change the section  #return value.decode('utf-8') and add return value.decode('ISO-8859-1') in config.py

    def get(self, section, option, **kwargs):
        value = PythonConfigParser.get(self, section, option, **kwargs)
        if PY2:
            if type(value) is str:
                #return value.decode('utf-8')
                return value.decode('ISO-8859-1')
        return value
