### ISSUE TITLE
 KeyError: 'kivy.garden.filebrowser'

### ISSUE THREAD

**Issue by brianbruggeman** [kivy/kivy-designer#265]
Macbook Pro (late 2013)
macOS Sierra
version 10.12.1

$ python -V
Python 3.5.2

$ python -c 'import kivy; print(kivy.__version__)'
v1.9.2-dev0

$ pip freeze
argh==0.26.2
Cython==0.25.1
docutils==0.12
gitdb2==2.0.0
GitPython==2.1.0
jedi==0.9.0
Kivy==1.9.2.dev0
kivy-designer==0.1.dev0
Kivy-Garden==0.1.4
pathtools==0.1.2
Pygments==2.1.3
PyInstaller==3.2
PyYAML==3.12
requests==2.11.1
six==1.10.0
smmap2==2.0.1
watchdog==0.8.3

$ python -m designer
[INFO   ] [Logger      ] Record log in $HOME/.kivy/logs/kivy_16-11-05_14.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v3.5.2 (default, Oct 11 2016, 04:59:56)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] OpenGL version <b'2.1 NVIDIA-10.12.68 355.10.05.05b16'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce GT 750M OpenGL Engine'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 184, in _run_module_as_main
     "__main__", mod_spec)
   File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File "$HOME/<kivy-designer-repo>/designer/__main__.py", line 3, in <module>
     from designer.app import DesignerApp
   File "$HOME/<kivy-designer-repo>/designer/app.py", line 11, in <module>
     from designer.components.dialogs.add_file import AddFileDialog
   File "$HOME/<kivy-designer-repo>/designer/components/dialogs/add_file.py", line 5, in <module>
     from kivy.garden.filebrowser import FileBrowser
   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 636, in _load_backward_compatible
 KeyError: 'kivy.garden.filebrowser'

**Comment by aron-bordin** [comment]
filebrowser is a dependency for running kivy-designer. Make sure to install it using "garden install filebrowser"
