### ISSUE TITLE
Error on create new project bug (cannot access the file)

### ISSUE THREAD

**Issue by MysticMight** [kivy/kivy-designer#270]
## Environment Info

kivy: 1.9.1
pygments: 2.1.3
docutils: 0.13.1
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 2.1.1
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-10-10.0.14393
Python: 3.4.4

## Traceback

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Python34\lib\site-packages\kivy\base.py", line 330, in idle
    self.dispatch_input()
  File "C:\Python34\lib\site-packages\kivy\base.py", line 315, in dispatch_input
    post_dispatch_input(*pop(0))
  File "C:\Python34\lib\site-packages\kivy\base.py", line 221, in post_dispatch_input
    listener.dispatch('on_motion', etype, me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python34\lib\site-packages\kivy\core\window\__init__.py", line 1030, in on_motion
    self.dispatch('on_touch_down', me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python34\lib\site-packages\kivy\core\window\__init__.py", line 1046, in on_touch_down
    if w.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python34\lib\site-packages\kivy\uix\popup.py", line 201, in on_touch_down
    return super(Popup, self).on_touch_down(touch)
  File "C:\Python34\lib\site-packages\kivy\uix\modalview.py", line 242, in on_touch_down
    super(ModalView, self).on_touch_down(touch)
  File "C:\Python34\lib\site-packages\kivy\uix\widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python34\lib\site-packages\kivy\uix\widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python34\lib\site-packages\kivy\uix\widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Users\USERNAME\kivy-designer\designer\components\dialogs\new_project.py", line 145, in on_touch_down
    return super(NewProjectDialog, self).on_touch_down(touch)
  File "C:\Python34\lib\site-packages\kivy\uix\widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python34\lib\site-packages\kivy\uix\widget.py", line 432, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python34\lib\site-packages\kivy\uix\behaviors\button.py", line 110, in on_touch_down
    self.dispatch('on_press')
  File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7654)
  File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
  File "kivy\_event.pyx", line 1148, in kivy._event.EventObservers._dispatch (kivy\_event.c:13023)
  File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7654)
  File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
  File "kivy\_event.pyx", line 1148, in kivy._event.EventObservers._dispatch (kivy\_event.c:13023)
  File "C:\Users\USERNAME\kivy-designer\designer\utils\utils.py", line 198, in wrapper
    f(*args, **kwargs)
  **File "C:\Users\USERNAME\kivy-designer\designer\app.py", line 766, in _perform_new
    shutil.rmtree(new_proj_dir)**
  File "C:\Python34\lib\shutil.py", line 482, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Python34\lib\shutil.py", line 381, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Python34\lib\shutil.py", line 379, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\USERNAME\\AppData\\Roaming\\designer\\.kivy-designer\\new_project'

End of Traceback

## My Comment
I believe this issue was caused because I currently had another template open at the same time named "new_project".

**Comment by MysticMight** [comment]
Could a system of getting a new name e.g. new_project2, new_project3 ... (if they already exist) be made?

**Comment by aron-bordin** [comment]
@MysticMight I think that the best way to handle is is to use temporary folders, instead of creating `new_project`X folders. 

So, instead of using a constant here: https://github.com/kivy/kivy-designer/blob/master/designer/app.py#L763 we should update it to create a temp folder and use it instead, so we will not face this problem again.

**Comment by manthansharma** [comment]
@aron-bordin Can we use [https://docs.python.org/2/library/tempfile.html](https://docs.python.org/2/library/tempfile.html) to create temp dir for project.

**Comment by MysticMight** [comment]
@manthansharma Yes, see #258

**Comment by manthansharma** [comment]
@MysticMight see #289 for creating new temp dir, i don't think we have to delete temp dir as soon as on exit / close of project, we can store project in /tmp directory which can be cleaned by OS itself.

**Comment by MysticMight** [comment]
I've attempted to delete the temp folder, but it doesn't work while its being accessed. Here's my current progress: [https://github.com/MysticMight/kivy-designer/tree/fix-new-project-handling]( https://github.com/MysticMight/kivy-designer/tree/fix-new-project-handling)

**Comment by manthansharma** [comment]
@MysticMight we can store project in /tmp directory which can be cleaned by OS itself.
