### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by tiagotcg** [kivy/kivy-designer#278]
## Environment Info

kivy: 1.9.1
pygments: 2.1.3
docutils: 0.13.1
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 2.1.1
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-10-10.0.14393-SP0
Python: 3.6.0

## Traceback

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Python36\lib\site-packages\kivy\base.py", line 330, in idle
    self.dispatch_input()
  File "C:\Python36\lib\site-packages\kivy\base.py", line 315, in dispatch_input
    post_dispatch_input(*pop(0))
  File "C:\Python36\lib\site-packages\kivy\base.py", line 281, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8164)
  File "C:\Python36\lib\site-packages\kivy\uix\behaviors\button.py", line 138, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8119)
  File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:14008)
  File "kivy\_event.pyx", line 1148, in kivy._event.EventObservers._dispatch (kivy\_event.c:13537)
  File "C:\Python36\lib\site-packages\kivy\uix\actionbar.py", line 335, in _toggle_dropdow

**Comment by MysticMight** [comment]
Is this the full log? It looks like some text is missing.
