### ISSUE TITLE
just probing a new project..

### ISSUE THREAD

**Issue by AlessandroMedici** [kivy/kivy-designer#282]
## Environment Info

kivy: 1.9.1
pygments: 2.1.3
docutils: 0.13.1
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 2.1.1
six: 1.10.0
kivy-garden: 0.1.4

Platform: Linux-4.8.0-2-amd64-x86_64-with-debian-stretch-sid
Python: 3.5.3rc1

## Traceback

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "/usr/lib/python3/dist-packages/kivy/base.py", line 330, in idle
    self.dispatch_input()
  File "/usr/lib/python3/dist-packages/kivy/base.py", line 315, in dispatch_input
    post_dispatch_input(*pop(0))
  File "/usr/lib/python3/dist-packages/kivy/base.py", line 281, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8164)
  File "/usr/lib/python3/dist-packages/kivy/uix/behaviors/button.py", line 138, in on_touch_up
    self.dispatch('on_release')
  File "kivy/_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8119)
  File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy/_event.c:14008)
  File "kivy/_event.pyx", line 1108, in kivy._event.EventObservers._dispatch (kivy/_event.c:12789)
  File "/usr/lib/python3/dist-packages/kivy/lang.py", line 1557, in custom_callback
    exec(__kvlang__.co_value, idmap)
  File "<string>", line 88, in <module>
  File "kivy/_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8119)
  File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy/_event.c:14008)
  File "kivy/_event.pyx", line 1148, in kivy._event.EventObservers._dispatch (kivy/_event.c:13537)
  File "/home/alex/designer-kivy/kivy-designer/designer/app.py", line 1040, in save_project
    self._perform_save_as(save_as_browser, exit_on_save=exit_on_save)
  File "/home/alex/designer-kivy/kivy-designer/designer/app.py", line 1065, in _perform_save_as
    self._perform_open(proj_dir)
  File "/home/alex/designer-kivy/kivy-designer/designer/app.py", line 951, in _perform_open
    project = self.project_manager.open_project(file_path)
  File "/home/alex/designer-kivy/kivy-designer/designer/core/project_manager.py", line 523, in open_project
    p.open()
  File "/home/alex/designer-kivy/kivy-designer/designer/core/project_manager.py", line 231, in open
    self.get_files()
  File "/home/alex/designer-kivy/kivy-designer/designer/core/project_manager.py", line 253, in get_files
    file_list += self.get_files(file_path)
  File "/home/alex/designer-kivy/kivy-designer/designer/core/project_manager.py", line 253, in get_files
    file_list += self.get_files(file_path)
  File "/home/alex/designer-kivy/kivy-designer/designer/core/project_manager.py", line 253, in get_files
    file_list += self.get_files(file_path)
  File "/home/alex/designer-kivy/kivy-designer/designer/core/project_manager.py", line 250, in get_files
    for _file in os.listdir(path):
PermissionError: [Errno 13] Permesso negato: '/home/alex/.config/pulse/daf980d4460777b772bea1195308e6f4-runtime'

End of Traceback

**Comment by MysticMight** [comment]
Looks like a similar write permission error as in #270.
