### ISSUE TITLE
Error when saving on exit (no crash)

### ISSUE THREAD

**Issue by MysticMight** [kivy/kivy-designer#285]
## Environment Info
kivy: 1.9.1
pygments: 2.1.3
docutils: 0.13.1
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 2.1.1
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-10-10.0.14393
Python: 3.4.4

## Error messages in console
[WARNING           ] [Lang        ] The file main.kv is loaded multiples times, you might have unwanted behaviors.
[ERROR             ] unable to access to <\hiberfil.sys>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kivy\uix\filechooser.py", line 177, in is_hidden
    return GetFileAttributesExW(fn)[0] & FILE_ATTRIBUTE_HIDDEN
pywintypes.error: (32, 'GetFileAttributesEx', 'The process cannot access the file because it is being used by another process.')
[ERROR             ] unable to access to <\pagefile.sys>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kivy\uix\filechooser.py", line 177, in is_hidden
    return GetFileAttributesExW(fn)[0] & FILE_ATTRIBUTE_HIDDEN
pywintypes.error: (32, 'GetFileAttributesEx', 'The process cannot access the file because it is being used by another process.')
[ERROR             ] unable to access to <\swapfile.sys>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kivy\uix\filechooser.py", line 177, in is_hidden
    return GetFileAttributesExW(fn)[0] & FILE_ATTRIBUTE_HIDDEN
pywintypes.error: (32, 'GetFileAttributesEx', 'The process cannot access the file because it is being used by another process.')
[INFO              ] [Base        ] Leaving application in progress...

## Comments
Project appears to save correctly, however the folder name given in the "Save As" popup isn't used.
Same error messages occur on opening the project, except 3 times (probably for main.py, main.kv and _something else_).

batch code used to display error:
```
cd %HOMEPATH%\kivy-designer
python -m designer
pause
```

**Comment by MysticMight** [comment]
Some info on: hiberfil.sys, pagefile.sys, swapfile.sys

http://www.thewindowsclub.com/hiberfil-pagefile-swapfile-sys-windows
