### ISSUE TITLE
Install on Windows 10 failed

### ISSUE THREAD

**Issue by WillAdams** [kivy/kivy-designer#290]
## Environment Info

kivy: 1.9.1
pygments: 2.2.0
docutils: 0.13.1
watchdog: 0.8.3
jedi: 0.10.0
gitpython: 2.1.1
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-10-10.0.14393
Python: 2.7.13

## Traceback

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Python27\lib\site-packages\kivy\base.py", line 330, in idle
    self.dispatch_input()
  File "C:\Python27\lib\site-packages\kivy\base.py", line 304, in dispatch_input
    provider.update(dispatch_fn=self._dispatch_input)
  File "C:\Python27\lib\site-packages\kivy\input\providers\wm_pen.py", line 143, in update
    self.pen.update_time_end()
AttributeError: 'NoneType' object has no attribute 'update_time_end'

End of Traceback

**Comment by manthansharma** [comment]
@WillAdams This is the issue of kivy not of kivy-designer. Reference this issues for more detail kivy/kivy#4651
