### ISSUE TITLE
Errors on saving new project and loading images

### ISSUE THREAD

**Issue by ticatwolves** [kivy/kivy-designer#291]
I have two issues 
1 On saving a new project Kivy GUI is going in not responding condition with the following error no doubt that the project is saves successfully in the directory selected but kivy designer window stuck in it and goes in not responding state. here is error i'm getting 

`you might have unwanted behaviors.
[ERROR             ] unable to access to <\hiberfil.sys>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kivy\uix\filechooser.py", line 177, in is_                                                                                                                hidden
    return GetFileAttributesExW(fn)[0] & FILE_ATTRIBUTE_HIDDEN
pywintypes.error: (32, 'GetFileAttributesEx', 'The process cannot access the fil                                                                                                                e because it is being used by another process.')
[ERROR             ] unable to access to <\pagefile.sys>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kivy\uix\filechooser.py", line 177, in is_                                                                                                                hidden
    return GetFileAttributesExW(fn)[0] & FILE_ATTRIBUTE_HIDDEN
pywintypes.error: (32, 'GetFileAttributesEx', 'The process cannot access the fil                                                                                                                e because it is being used by another process.')
[ERROR             ] unable to access to <\swapfile.sys>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kivy\uix\filechooser.py", line 177, in is_                                                                                                                hidden
    return GetFileAttributesExW(fn)[0] & FILE_ATTRIBUTE_HIDDEN
pywintypes.error: (32, 'GetFileAttributesEx', 'The process cannot access the fil                                                                                                                e because it is being used by another process.')
[ERROR             ] [unable to access to <C]\hiberfil.sys>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kivy\uix\filechooser.py", line 177, in is_                                                                                                                hidden
    return GetFileAttributesExW(fn)[0] & FILE_ATTRIBUTE_HIDDEN
pywintypes.error: (32, 'GetFileAttributesEx', 'The process cannot access the fil                                                                                                                e because it is being used by another process.')
[ERROR             ] [unable to access to <C]\pagefile.sys>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kivy\uix\filechooser.py", line 177, in is_                                                                                                                hidden
    return GetFileAttributesExW(fn)[0] & FILE_ATTRIBUTE_HIDDEN
pywintypes.error: (32, 'GetFileAttributesEx', 'The process cannot access the fil                                                                                                                e because it is being used by another process.')
[ERROR             ] [unable to access to <C]\swapfile.sys>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kivy\uix\filechooser.py", line 177, in is_                                                                                                                hidden
    return GetFileAttributesExW(fn)[0] & FILE_ATTRIBUTE_HIDDEN
pywintypes.error: (32, 'GetFileAttributesEx', 'The process cannot access the fil                                                                                                                e because it is being used by another process.')
[ERROR             ] [unable to access to <C]\hiberfil.sys>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kivy\uix\filechooser.py", line 177, in is_                                                                                                                hidden
    return GetFileAttributesExW(fn)[0] & FILE_ATTRIBUTE_HIDDEN
pywintypes.error: (32, 'GetFileAttributesEx', 'The process cannot access the fil                                                                                                                e because it is being used by another process.')
[ERROR             ] [unable to access to <C]\pagefile.sys>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kivy\uix\filechooser.py", line 177, in is_                                                                                                                hidden
    return GetFileAttributesExW(fn)[0] & FILE_ATTRIBUTE_HIDDEN
pywintypes.error: (32, 'GetFileAttributesEx', 'The process cannot access the fil                                                                                                                e because it is being used by another process.')
[ERROR             ] [unable to access to <C]\swapfile.sys>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kivy\uix\filechooser.py", line 177, in is_                                                                                                                hidden
    return GetFileAttributesExW(fn)[0] & FILE_ATTRIBUTE_HIDDEN
pywintypes.error: (32, 'GetFileAttributesEx', 'The process cannot access the fil                                                                                                                e because it is being used by another process.')

`

2 one is with loading images when you add more then one image then the tags mismatch like this 
`Image:
 Image:
source: oneimagesource
source:secondimagesource`

with single image it is like 
`Image:
    source:imagepath`

**Comment by MysticMight** [comment]
#285 same error messages as 1
