### ISSUE TITLE
kivy-designer - Error in font name change

### ISSUE THREAD

**Issue by benefonteles** [kivy/kivy-designer#296]
## Environment Info

kivy: 1.9.1
pygments: 2.2.0
docutils: 0.13.1
watchdog: 0.8.3
jedi: 0.10.0
gitpython: 2.1.3
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-10-10.0.14393-SP0
Python: 3.6.0

## Traceback

Traceback (most recent call last):
  File "E:\Programas\Anaconda3\envs\k36\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "E:\Programas\Anaconda3\envs\k36\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "E:\Programas\Anaconda3\envs\k36\lib\site-packages\kivy\base.py", line 327, in idle
    Clock.tick()
  File "E:\Programas\Anaconda3\envs\k36\lib\site-packages\kivy\clock.py", line 515, in tick
    self._process_events()
  File "E:\Programas\Anaconda3\envs\k36\lib\site-packages\kivy\clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "E:\Programas\Anaconda3\envs\k36\lib\site-packages\kivy\clock.py", line 406, in tick
    ret = callback(self._dt)
  File "E:\Programas\Anaconda3\envs\k36\lib\site-packages\kivy\uix\label.py", line 356, in texture_update
    self._label.refresh()
  File "E:\Programas\Anaconda3\envs\k36\lib\site-packages\kivy\core\text\__init__.py", line 633, in refresh
    self.resolve_font_name()
  File "E:\Programas\Anaconda3\envs\k36\lib\site-packages\kivy\core\text\__init__.py", line 261, in resolve_font_name
    r

**Comment by MysticMight** [comment]
I can't seem to find "text_init.py", the only file similar in that location is "\_\_init\_\_.py".
I checked my kivy, as well as the git repository; [https://github.com/kivy/kivy/tree/master/kivy/core](https://github.com/kivy/kivy/tree/master/kivy/core).

Also, looking at the traceback Kivy designer doesn't appear to be the cause, this seems more relevant to the Kivy framework. (Unless I am mistaken and Kivy Designer is using kivy, and then the issue occurs)

**Comment by aron-bordin** [comment]
This seems not to be related with kivy-designer. If the error persists, fell free to ping us on IRC or in the maillist.
