### ISSUE TITLE
Setting a GridLayout with both rows and columns equal to 1 and adding a second widget

### ISSUE THREAD

**Issue by nunobrum** [kivy/kivy-designer#297]
## Environment Info

kivy: 1.9.2.dev0
pygments: 2.2.0
docutils: 0.13.1
watchdog: 0.8.3
jedi: 0.10.0
gitpython: 2.1.3
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-7-6.1.7601-SP1
Python: 3.6.0

## Traceback

Traceback (most recent call last):
  File "c:\Python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 659, in mainloop
    self._mainloop()
  File "c:\Python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 405, in _mainloop
    EventLoop.idle()
  File "c:\Python36\lib\site-packages\kivy\base.py", line 348, in idle
    Clock.tick_draw()
  File "c:\Python36\lib\site-packages\kivy\clock.py", line 588, in tick_draw
    self._process_events_before_frame()
  File "kivy\_clock.pyx", line 405, in kivy._clock.CyClockBase._process_events_before_frame (kivy\_clock.c:8381)
  File "kivy\_clock.pyx", line 445, in kivy._clock.CyClockBase._process_events_before_frame (kivy\_clock.c:8255)
  File "kivy\_clock.pyx", line 443, in kivy._clock.CyClockBase._process_events_before_frame (kivy\_clock.c:8176)
  File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (kivy\_clock.c:3490)
  File "c:\Python36\lib\site-packages\kivy\uix\gridlayout.py", line 506, in do_layout
    self._fill_rows_cols_sizes()
  File "c:\Python36\lib\site-packages\kivy\uix\gridlayout.py", line 357, in _fill_rows_cols_sizes
    rows_sh[row] = nmax(rows_sh[row], shh)
IndexError: list index out of range

End of Traceback

**Comment by MysticMight** [comment]
I can't duplicate this message, though I am using a different environment (Kivy 1.9.1, Python 3.4.4, Windows 10). However I do get error messages, though they are only in console and do not cause any crash.

I receive several of the following:
 ```Exception ignored in: 'kivy.properties.observable_list_dispatch'
 Traceback (most recent call last):
   File "kivy\properties.pyx", line 501, in kivy.properties.Property.dispatch (kivy\properties.c:6557)
   File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
   File "kivy\_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (kivy\_event.c:12696)
   File "C:\Python34\lib\site-packages\kivy\uix\gridlayout.py", line 276, in on_children
     'Too many children in GridLayout. Increase rows/cols!')
 kivy.uix.gridlayout.GridLayoutException: Too many children in GridLayout. Increase rows/cols!
```
I expected the Kivy Designer "KV Lang Area" or Error console to report this as an error or warning, however no such message appears. The widget in the area still appears to be a child of the GridLayout, but only the positioning (bottom left corner) states otherwise.
