### ISSUE TITLE
image bug

### ISSUE THREAD

**Issue by Namansetth** [kivy/kivy-designer#298]
## Environment Info

kivy: 1.9.1
pygments: 2.2.0
docutils: 0.13.1
watchdog: 0.8.3
jedi: 0.10.0
gitpython: 2.1.3
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-8.1-6.3.9600-SP0
Python: 3.6.1

## Traceback

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Python\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Python\lib\site-packages\kivy\base.py", line 327, in idle
    Clock.tick()
  File "C:\Python\lib\site-packages\kivy\clock.py", line 515, in tick
    self._process_events()
  File "C:\Python\lib\site-packages\kivy\clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "C:\Python\lib\site-packages\kivy\clock.py", line 406, in tick
    ret = callback(self._dt)
  File "C:\Users\Deadpool\Downloads\Compressed\kivy-designer-master\kivy-designer-master\designer\components\widgets_tree.py", line 110, in _refresh
    self._clear_tree(self.tree, self.tree.root)
  File "C:\Users\Deadpool\Downloads\Compressed\kivy-designer-master\kivy-designer-master\designer\components\widgets_tree.py", line 103, in _clear_tree
    self._clear_tree(tree, n)
  File "C:\Users\Deadpool\Downloads\Compressed\kivy-designer-master\kivy-designer-master\designer\components\widgets_tree.py", line 103, in _clear_tree
    self._clear_tree(tre

**Comment by aron-bordin** [comment]
Hi, Unfortunately, your bug report is not complete. Please, check the bug reporter instructions on how to post the full traceback. You need to post the full message until the "End of Traceback" string.

Thank you for reporting.
