### ISSUE TITLE
Saving Error

### ISSUE THREAD

**Issue by Rami9284** [kivy/kivy-designer#299]
## Environment Info

kivy: 1.9.1
pygments: 2.2.0
docutils: 0.13.1
watchdog: 0.8.3
jedi: 0.10.0
gitpython: 2.1.3
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-10-10.0.14393
Python: 3.4.4

## Traceback

Traceback (most recent call last):
  File "C:\Python34\lib\distutils\file_util.py", line 35, in _copy_file_contents
    os.unlink(dst)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Asus\\AppData\\Roaming\\designer\\.kivy-designer\\new_project\\.designer\\config.ini'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Python34\lib\site-packages\kivy\base.py", line 330, in idle
    self.dispatch_input()
  File "C:\Python34\lib\site-packages\kivy\base.py", line 315, in dispatch_input
    post_dispatch_input(*pop(0))
  File "C:\Python34\lib\site-packages\kivy\base.py", line 281, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python34\lib\site-packages\kivy\uix\behaviors\button.py", line 138, in on_to

**Comment by manthansharma** [comment]
@Rami9284 Please paste full traceback, it should end with `End of Traceback`.

**Comment by MysticMight** [comment]
This seems related to the new_project fix in progress, changing to use temporary directory. #289 #294

**Comment by aron-bordin** [comment]
fixed by https://github.com/kivy/kivy-designer/pull/294
