### ISSUE TITLE
Unexpected crash during drag and drop of a box layout to the root widget

### ISSUE THREAD

**Issue by B00mGit** [kivy/kivy-designer#300]
## Environment Info

kivy: 1.9.2.dev0
pygments: 2.2.0
docutils: 0.13.1
watchdog: 0.8.3
jedi: 0.10.2
gitpython: 2.1.3
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-7-6.1.7601-SP1
Python: 3.6.1

## Traceback

Traceback (most recent call last):
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\core\window\window_pygame.py", line 403, in mainloop
    self._mainloop()
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\core\window\window_pygame.py", line 289, in _mainloop
    EventLoop.idle()
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\base.py", line 339, in idle
    Clock.tick()
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\clock.py", line 581, in tick
    self._process_events()
  File "kivy\_clock.pyx", line 367, in kivy._clock.CyClockBase._process_events (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_clock.c:7700)
  File "kivy\_clock.pyx", line 397, in kivy._clock.CyClockBase._process_events (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_clock.c:7577)
  File "kivy\_clock.pyx", line 395, in kivy._clock.CyClockBase._process_events (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_clock.c:7498)
  File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_clock.c:3490)
  File "C:\Users\B00m\kivy-designer\designer\components\widgets_tree.py", line 110, in _refresh
    self._clear_tree(self.tree, self.tree.root)
  File "C:\Users\B00m\kivy-designer\designer\components\widgets_tree.py", line 103, in _clear_tree
    self._clear_tree(tree, n)
  File "C:\Users\B00m\kivy-designer\designer\components\widgets_tree.py", line 103, in _clear_tree
    self._clear_tree(tree, n)
  File "C:\Users\B00m\kivy-designer\designer\components\widgets_tree.py", line 103, in _clear_tree
    self._clear_tree(tree, n)
  File "C:\Users\B00m\kivy-designer\designer\components\widgets_tree.py", line 102, in _clear_tree
    for n in node.nodes[:]:
  File "kivy\weakproxy.pyx", line 30, in kivy.weakproxy.WeakProxy.__getattr__ (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\weakproxy.c:1382)
  File "kivy\weakproxy.pyx", line 26, in kivy.weakproxy.WeakProxy.__ref__ (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\weakproxy.c:1284)
ReferenceError: weakly-referenced object no longer exists

End of Traceback

**Comment by MysticMight** [comment]
Looks similar to #235
