### ISSUE TITLE
Unexpected crash during drag and drop of a label widget

### ISSUE THREAD

**Issue by B00mGit** [kivy/kivy-designer#301]
## Environment Info

kivy: 1.9.2.dev0
pygments: 2.2.0
docutils: 0.13.1
watchdog: 0.8.3
jedi: 0.10.2
gitpython: 2.1.3
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-7-6.1.7601-SP1
Python: 3.6.1

## Traceback

Traceback (most recent call last):
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\core\window\window_pygame.py", line 403, in mainloop
    self._mainloop()
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\core\window\window_pygame.py", line 289, in _mainloop
    EventLoop.idle()
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\base.py", line 342, in idle
    self.dispatch_input()
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\base.py", line 327, in dispatch_input
    post_dispatch_input(*pop(0))
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\base.py", line 233, in post_dispatch_input
    listener.dispatch('on_motion', etype, me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_event.c:8191)
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\core\window\__init__.py", line 1192, in on_motion
    self.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_event.c:8191)
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\core\window\__init__.py", line 1228, in on_touch_up
    if w.dispatch('on_touch_up', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_event.c:8191)
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\widget.py", line 479, in on_touch_up
    if child.dispatch('on_touch_up', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_event.c:8191)
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\widget.py", line 479, in on_touch_up
    if child.dispatch('on_touch_up', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_event.c:8191)
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\widget.py", line 479, in on_touch_up
    if child.dispatch('on_touch_up', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_event.c:8191)
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\widget.py", line 479, in on_touch_up
    if child.dispatch('on_touch_up', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_event.c:8191)
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\widget.py", line 479, in on_touch_up
    if child.dispatch('on_touch_up', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_event.c:8191)
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\widget.py", line 479, in on_touch_up
    if child.dispatch('on_touch_up', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_event.c:8191)
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\widget.py", line 479, in on_touch_up
    if child.dispatch('on_touch_up', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_event.c:8191)
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\widget.py", line 479, in on_touch_up
    if child.dispatch('on_touch_up', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_event.c:8191)
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\widget.py", line 479, in on_touch_up
    if child.dispatch('on_touch_up', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_event.c:8191)
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\widget.py", line 479, in on_touch_up
    if child.dispatch('on_touch_up', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_event.c:8191)
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\widget.py", line 479, in on_touch_up
    if child.dispatch('on_touch_up', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_event.c:8191)
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\widget.py", line 479, in on_touch_up
    if child.dispatch('on_touch_up', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_event.c:8191)
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\widget.py", line 479, in on_touch_up
    if child.dispatch('on_touch_up', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_event.c:8191)
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\scrollview.py", line 833, in on_touch_up
    if self.dispatch('on_scroll_stop', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_event.c:8191)
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\scrollview.py", line 872, in on_scroll_stop
    self.simulate_touch_down(touch)
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\scrollview.py", line 596, in simulate_touch_down
    ret = super(ScrollView, self).on_touch_down(touch)
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\widget.py", line 457, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_event.c:8191)
  File "C:\Users\B00m\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\widget.py", line 457, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\_event.c:8191)
  File "C:\Users\B00m\kivy-designer\designer\components\property_viewer.py", line 160, in on_touch_down
    self._chooser.show_items()
  File "C:\Users\B00m\kivy-designer\designer\uix\settings.py", line 351, in show_items
    self.setting.items.sort()
  File "kivy\properties.pyx", line 697, in kivy.properties.ObservableList.sort (C:\Users\B00m\AppData\Local\Temp\pip-vr_h9ono-build\kivy\properties.c:10945)
TypeError: '<' not supported between instances of 'str' and 'NoneType'

End of Traceback

**Comment by B00mGit** [comment]
FYI
I'm getting strange red dots appearing in the designer interface each time I right click......

**Comment by MysticMight** [comment]
@B00mGit The red dots are a normal part of kivy. Here's a reference: http://stackoverflow.com/questions/12692851/why-does-right-clicking-create-an-orange-dot-in-the-center-of-the-circle
