### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dmunafo** [kivy/kivy-designer#306]
## Environment Info

kivy: 1.9.2.dev0
pygments: 2.2.0
docutils: 0.13.1
watchdog: 0.8.3
jedi: 0.10.2
gitpython: 2.1.3
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-8.1-6.3.9600-SP0
Python: 3.5.3

## Traceback

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\kivy\core\window\window_sdl2.py", line 663, in mainloop
    self._mainloop()
  File "C:\Python35\lib\site-packages\kivy\core\window\window_sdl2.py", line 602, in _mainloop
    self.modifiers):
  File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8146)
  File "kivy\_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy\_event.c:14035)
  File "kivy\_event.pyx", line 1149, in kivy._event.EventObservers._dispatch (kivy\_event.c:13564)
  File "C:\Python35\lib\site-packages\kivy\core\window\__init__.py", line 159, in _on_window_key_down
    return self.dispatch('on_key_down', keycode, text, modifiers)
  File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8146)
  File "kivy\_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy\_event.c:14035)
  File "kivy\_event.pyx", line 1149, in kivy._event.EventObservers._dispatch (kivy\_event.c:13564)
  File "C:\Users\dmunafo\Downloads\kivy-designer-master\designer\components\playground.py", line 1063, in _on_keyboard_down
    self.do_undo()
  File "C:\Users\dmunafo\Downloads\kivy-designer-master\designer\component

**Comment by aron-bordin** [comment]
Hi, Unfortunately, your bug report is not complete. Please, check the bug reporter instructions on how to post the full traceback. You need to post the full message until the "End of Traceback" string.

Thank you for reporting.
