### ISSUE TITLE
save error

### ISSUE THREAD

**Issue by dmunafo** [kivy/kivy-designer#307]
## Environment Info

kivy: 1.9.2.dev0
pygments: 2.2.0
docutils: 0.13.1
watchdog: 0.8.3
jedi: 0.10.2
gitpython: 2.1.3
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-8.1-6.3.9600-SP0
Python: 3.5.3

## Traceback

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\kivy\core\window\window_sdl2.py", line 663, in mainloop
    self._mainloop()
  File "C:\Python35\lib\site-packages\kivy\core\window\window_sdl2.py", line 405, in _mainloop
    EventLoop.idle()
  File "C:\Python35\lib\site-packages\kivy\base.py", line 342, in idle
    self.dispatch_input()
  File "C:\Python35\lib\site-packages\kivy\base.py", line 327, in dispatch_input
    post_dispatch_input(*pop(0))
  File "C:\Python35\lib\site-packages\kivy\base.py", line 233, in post_dispatch_input
    listener.dispatch('on_motion', etype, me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
  File "C:\Python35\lib\site-packages\kivy\core\window\__init__.py", line 1188, in on_motion
    self.dispatch('on_touch_down', me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
  File "C:\Python35\lib\site-packages\kivy\core\window\__init__.py", line 1204, in on_touch_down
    if w.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
  File "C:\User

**Comment by aron-bordin** [comment]
Hi, Unfortunately, your bug report is not complete. Please, check the bug reporter instructions on how to post the full traceback. You need to post the full message until the "End of Traceback" string.

Thank you for reporting.
