### ISSUE TITLE
Crash Help

### ISSUE THREAD

**Issue by moreiradev** [kivy/kivy-designer#309]
My kivy designer crashes quite often, if someone can help me. :)
## Environment Info

kivy: 1.9.1
pygments: 2.2.0
docutils: 0.13.1
watchdog: 0.8.3
jedi: 0.10.2
gitpython: 2.1.3
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-10-10.0.14393
Python: 2.7.13

## Traceback

Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "c:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "c:\Python27\lib\site-packages\kivy\base.py", line 336, in idle
    Clock.tick_draw()
  File "c:\Python27\lib\site-packages\kivy\clock.py", line 522, in tick_draw
    self._process_events_before_frame()
  File "c:\Python27\lib\site-packages\kivy\clock.py", line 672, in _process_events_before_frame
    event.tick(self._last_tick, remove)
  File "c:\Python27\lib\site-packages\kivy\clock.py", line 406, in tick
    ret = callback(self._dt)
  File "c:\Python27\lib\site-packages\kivy\uix\boxlayout.py", line 175, in do_layout
    c.width = w
  File "kivy\properties.pyx", line 408, in kivy.properties.Property.__set__ (kivy\properties.c:5114)
  File "kivy\properties.pyx", line 446, in kivy.properties.Property.set (kivy\properties.c:5876)
  File "kivy\properties.pyx", line 501, in kivy.properties.Property.dispatch (kivy\properties.c:6557)
  File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
  File "kivy\_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (kivy\_event.c:12696)
  File "c:\Python27\lib\site-packages\kivy\uix\actionbar.py", line 601, in on_width
    self._layout_all()
  File "c:\Python27\lib\site-packages\kivy\uix\actionbar.py", line 486, in _layout_all
    super_add(self.action_previous)
  File "c:\Python27\lib\site-packages\kivy\uix\boxlayout.py", line 211, in add_widget
    widget.bind(
AttributeError: 'NoneType' object has no attribute 'bind'

End of Traceback

**Comment by MysticMight** [comment]
@moreiradev Can you describe what you were doing, and what template was being used (I think I know what, but to be sure)?

**Comment by moreiradev** [comment]
Well, sometimes kivy designer crashes quite randomly but never shows up that crash report menu. 
It crashed when i clicked a recent project, where it says "Recent projects" and you click in the path of the file. I tested it again and it keeps crashing clicking there. 
If also you could help me with the random crashes I would be very apreciated! :)

Btw, does it usualy takes a lot of time to run android app?

**Comment by MysticMight** [comment]
I am not sure about android, but if you run kivy designer using the following commands in a batch (or your equivalent file and code if not using windows), a console should stay open with messages. These messages are also saved in a log with kivy here: "C:\Users\USERNAME\.kivy\logs".
(replace %HOMEPATH% with your path to kivy designer)
```
cd %HOMEPATH%\kivy-designer
python -m designer
pause
```

**Comment by moreiradev** [comment]
Using already a batch file, but I missed the "pause"
Thanks
