### ISSUE TITLE
"Saving as" the file without extension

### ISSUE THREAD

**Issue by MatheusKlauck** [kivy/kivy-designer#310]
## Environment Info

kivy: 1.9.1
pygments: 2.2.0
docutils: 0.13.1
watchdog: 0.8.3
jedi: 0.10.2
gitpython: 2.1.3
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-10-10.0.14393
Python: 3.4.4

## Traceback

Traceback (most recent call last):
  File "C:\Python34\lib\distutils\file_util.py", line 35, in _copy_file_contents
    os.unlink(dst)
PermissionError: [WinError 32] O arquivo já está sendo usado por outro processo: 'C:\\Python\\Projetos\\Momentum\\.designer\\config.ini'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Python34\lib\site-packages\kivy\base.py", line 330, in idle
    self.dispatch_input()
  File "C:\Python34\lib\site-packages\kivy\base.py", line 315, in dispatch_input
    post_dispatch_input(*pop(0))
  File "C:\Python34\lib\site-packages\kivy\base.py", line 281, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
  File "C:\Python34\lib\site-packages\kivy\uix\behaviors\button.py", line 138, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event

**Comment by MysticMight** [comment]
Looks similar to 270, trying to save to a file already being used.

**Comment by aron-bordin** [comment]
fixed by https://github.com/kivy/kivy-designer/pull/294, thank you for reporting.
