### ISSUE TITLE
window resize not work

### ISSUE THREAD

**Issue by mohendra** [kivy/kivy-designer#318]
## Environment Info

kivy: 1.10.1.dev0
pygments: 2.2.0
docutils: 0.13.1
watchdog: 0.8.3
jedi: 0.10.2
gitpython: 2.1.3
six: 1.10.0
kivy-garden: 0.1.4

Platform: Darwin-16.6.0-x86_64-i386-64bit
Python: 3.6.1

## Traceback

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/core/window/window_pygame.py", line 403, in mainloop
    self._mainloop()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/core/window/window_pygame.py", line 289, in _mainloop
    EventLoop.idle()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/base.py", line 348, in idle
    Clock.tick_draw()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/clock.py", line 588, in tick_draw
    self._process_events_before_frame()
  File "kivy/_clock.pyx", line 405, in kivy._clock.CyClockBase._process_events_before_frame (/private/var/folders/g2/2f_8s3311td99dwd0bxl_xz80000gn/T/pip-q_hoi6ps-build/kivy/_clock.c:8381)
  File "kivy/_clock.pyx", line 445, in kivy._clock.CyClockBase._process_events_before_frame (/private/var/folders/g2/2f_8s3311td99dwd0bxl_xz80000gn/T/pip-q_hoi6ps-build/kivy/_clock.c:8255)
  File "kivy/_clock.pyx", line 443, in kivy._clock.CyClockBase._process_events_before_frame (/private/var/folders/g2/2f_8s3311td99dwd0bxl_xz80000gn/T/pip-q_hoi6ps-build/kivy/_clock.c:8176)
  File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (/private/var/folders/g2/2f_8s3311td99dwd0bxl_xz80000gn/T/pip-q_hoi6ps-build/kivy/_clock.c:3490)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/uix/boxlayout.py", line 309, in do_layout
    c.size = (w, h)
  File "kivy/properties.pyx", line 478, in kivy.properties.Property.__set__ (/private/var/folders/g2/2f_8s3311td99dwd0bxl_xz80000gn/T/pip-q_hoi6ps-build/kivy/properties.c:5572)
  File "kivy/properties.pyx", line 1342, in kivy.properties.ReferenceListProperty.set (/private/var/folders/g2/2f_8s3311td99dwd0bxl_xz80000gn/T/pip-q_hoi6ps-build/kivy/properties.c:21169)
  File "kivy/properties.pyx", line 494, in kivy.properties.Property.set (/private/var/folders/g2/2f_8s3311td99dwd0bxl_xz80000gn/T/pip-q_hoi6ps-build/kivy/properties.c:6520)
  File "kivy/properties.pyx", line 516, in kivy.properties.Property.set (/private/var/folders/g2/2f_8s3311td99dwd0bxl_xz80000gn/T/pip-q_hoi6ps-build/kivy/properties.c:6405)
  File "kivy/properties.pyx", line 571, in kivy.properties.Property.dispatch (/private/var/folders/g2/2f_8s3311td99dwd0bxl_xz80000gn/T/pip-q_hoi6ps-build/kivy/properties.c:7105)
  File "kivy/_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (/private/var/folders/g2/2f_8s3311td99dwd0bxl_xz80000gn/T/pip-q_hoi6ps-build/kivy/_event.c:14035)
  File "kivy/_event.pyx", line 1131, in kivy._event.EventObservers._dispatch (/private/var/folders/g2/2f_8s3311td99dwd0bxl_xz80000gn/T/pip-q_hoi6ps-build/kivy/_event.c:13193)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/uix/actionbar.py", line 644, in on_width
    self._layout_group()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/uix/actionbar.py", line 538, in _layout_group
    self._clear_all()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/uix/actionbar.py", line 501, in _clear_all
    self.clear_widgets()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/uix/widget.py", line 605, in clear_widgets
    remove_widget(child)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/uix/actionbar.py", line 494, in remove_widget
    self._list_action_items.remove(item)
ValueError: list.remove(x): x not in list

End of Traceback

**Comment by manthansharma** [comment]
@mohendra Can you specify what you mean by window resize(designer or project window).

**Comment by tiktok7** [comment]
It appears to be triggered when one of the menu items is hidden and replaced by the vertical ellipsis. A short time after the redraw event will end in the exception shown above.

**Comment by tiktok7** [comment]
It appears to be a problem with the use of the kivy actionbar. In `_layout_random`, when the width contracts, the "Help" item is added to `hidden_groups` which is in turn added to `hidden_items`. All hidden items are then added to the `overflow_group` (so the Help menu item is no longer displayed unless the ellipsis is clicked). Unfortunately this means that the action_bar.remove_widget later fails because it tries to remove the group from the action items list even though it's not contained in it. 

I'm not entirely sure what the correction should be but I verified the problem with the following change (which allows the designer app to handle resizes without the same crash happening)

```
diff --git a/kivy/uix/actionbar.py b/kivy/uix/actionbar.py
index 5e4f400..c8161d7 100644
--- a/kivy/uix/actionbar.py
+++ b/kivy/uix/actionbar.py
@@ -491,7 +491,8 @@ class ActionView(BoxLayout):
         super(ActionView, self).remove_widget(widget)
         if isinstance(widget, ActionOverflow):
             for item in widget.list_action_item:
-                self._list_action_items.remove(item)
+                if item in self._list_action_items:
+                    self._list_action_items.remove(item)
 
         if widget in self._list_action_items:
             self._list_action_items.remove(widget)
```

**Comment by tiktok7** [comment]
Reported issue on kivy repo
https://github.com/kivy/kivy/issues/5333

**Comment by tiktok7** [comment]
@mohendra : this was just fixed in kivy. It should be enough to stop the crash
