### ISSUE TITLE
Crash on launch Windows 10 (new installation)

### ISSUE THREAD

**Issue by knatz-personal** [kivy/kivy-designer#325]
I installed kivy-designer following the instructions given for windows. When I ran the command 
> python -m designer 

I got the following eror

> [WARNING] [FileNotFoundError] [Errno 2] No such file or directory: 'C:\\Users\\Natha_000\\.kivy\\garden\\garden.xpopup\\xpopup.mo'. Switch to the defaults.
[INFO   ] [Clipboard   ] Provider: winctypes
 Traceback (most recent call last):
   File "C:\Anaconda3\lib\site-packages\git\cmd.py", line 599, in execute
     **subprocess_kwargs
   File "C:\Anaconda3\lib\subprocess.py", line 856, in __init__
     restore_signals, start_new_session)
   File "C:\Anaconda3\lib\subprocess.py", line 1111, in _execute_child
     startupinfo)
 FileNotFoundError: [WinError 2] The system cannot find the file specified
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
   File "C:\Anaconda3\lib\runpy.py", line 170, in _run_module_as_main
     "__main__", mod_spec)
   File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File "C:\Users\USER\Downloads\kivy-designer\designer\__main__.py", line 17, in <module>
     main()
   File "C:\Users\USER\Downloads\kivy-designer\designer\__main__.py", line 13, in main
     DesignerApp().run()
   File "C:\Anaconda3\lib\site-packages\kivy\app.py", line 802, in run
     root = self.build()
   File "C:\Users\USER\Downloads\kivy-designer\designer\app.py", line 1738, in build
     self.root = Designer()
   File "C:\Users\USER\Downloads\kivy-designer\designer\app.py", line 207, in __init__
     super(Designer, self).__init__(**kwargs)
   File "C:\Anaconda3\lib\site-packages\kivy\uix\floatlayout.py", line 65, in __init__
     super(FloatLayout, self).__init__(**kwargs)
   File "C:\Anaconda3\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "C:\Anaconda3\lib\site-packages\kivy\uix\widget.py", line 345, in __init__
     Builder.apply(self, ignored_consts=self._kwargs_applied_init)
   File "C:\Anaconda3\lib\site-packages\kivy\lang\builder.py", line 451, in apply
     self._apply_rule(widget, rule, rule, ignored_consts=ignored_consts)
   File "C:\Anaconda3\lib\site-packages\kivy\lang\builder.py", line 567, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "C:\Anaconda3\lib\site-packages\kivy\lang\builder.py", line 567, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "C:\Anaconda3\lib\site-packages\kivy\lang\builder.py", line 567, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "C:\Anaconda3\lib\site-packages\kivy\lang\builder.py", line 526, in _apply_rule
     cls = Factory_get(cname)
   File "C:\Anaconda3\lib\site-packages\kivy\factory.py", line 139, in __getattr__
     module = __import__(name=item['module'], fromlist='.')
   File "C:\Users\USER\Downloads\kivy-designer\designer\tools\git_integration.py", line 23, in <module>
     from git import GitCommandError, RemoteProgress, Repo
   File "C:\Anaconda3\lib\site-packages\git\__init__.py", line 45, in <module>
     from git.repo import Repo               # @NoMove @IgnorePep8
   File "C:\Anaconda3\lib\site-packages\git\repo\__init__.py", line 4, in <module>
     from .base import *
   File "C:\Anaconda3\lib\site-packages\git\repo\base.py", line 31, in <module>
     from git.remote import Remote, add_progress, to_progress_instance
   File "C:\Anaconda3\lib\site-packages\git\remote.py", line 190, in <module>
     class FetchInfo(object):
   File "C:\Anaconda3\lib\site-packages\git\remote.py", line 219, in FetchInfo
     v = Git().version_info[:2]
   File "C:\Anaconda3\lib\site-packages\git\cmd.py", line 461, in version_info
     return self._version_info
   File "C:\Anaconda3\lib\site-packages\git\cmd.py", line 424, in __getattr__
     return LazyMixin.__getattr__(self, name)
   File "C:\Anaconda3\lib\site-packages\gitdb\util.py", line 256, in __getattr__
     self._set_cache_(attr)
   File "C:\Anaconda3\lib\site-packages\git\cmd.py", line 444, in _set_cache_
     version_numbers = self._call_process('version').split(' ')[2]
   File "C:\Anaconda3\lib\site-packages\git\cmd.py", line 877, in _call_process
     return self.execute(call, **exec_kwargs)
   File "C:\Anaconda3\lib\site-packages\git\cmd.py", line 602, in execute
     raise GitCommandNotFound(command, err)
 git.exc.GitCommandNotFound: Cmd('git') not found due to: FileNotFoundError('[WinError 2] The system cannot find the file specified')
   cmdline: git version

I have already tried re-installing the prerequisites but the problem persists
PS. I very recently learned about kivy

**Comment by KeyWeeUsr** [comment]
The `git` executable has to be on your `%PATH%` env variable. If you have e.g. some `.bash_rc` alternative in Anaconda, the you can add it temporarily, or create a .bat file for that:

    set PATH=%PATH%;<folder with git.exe>
    python -m designer
    pause

or add git to the environment permanently

**Comment by knatz-personal** [comment]
Thanks that worked for me
