### ISSUE TITLE
Bug - Trying to run the project

### ISSUE THREAD

**Issue by bk-m** [kivy/kivy-designer#334]
# Explanation
When I try to run the project (with the Desktop profile selected) I consistently get this error.

# Environment Info
kivy: 1.10.0
pygments: 2.2.0
docutils: 0.13.1
watchdog: 0.8.3
jedi: 0.10.2
gitpython: 2.1.5
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows 7 - 6.1.7601
Python: 3.4.5

# Traceback
```
 Unhandled exception in thread started by <function KivyConsole.on_enter.<locals>.run_cmd at 0x00000000061F60D0>
 Traceback (most recent call last):
   File "C:\Users\bla\Desktop\PYTHON_TEST\kivy_test\kivy-designer\designer\components\kivy_console.py", line 658, in run_cmd
     creationflags=0)
   File "C:\Anaconda3\envs\kivy\lib\subprocess.py", line 856, in __init__
     restore_signals, start_new_session)
   File "C:\Anaconda3\envs\kivy\lib\subprocess.py", line 1111, in _execute_child
     startupinfo)
 TypeError: must be str or None, not bytes
```
End of Traceback

**Comment by ProductOfAmerica** [comment]
Same issue, still. Windows 10.
