### ISSUE TITLE
Crashed on Windows 10 

### ISSUE THREAD

**Issue by knatz-personal** [kivy/kivy-designer#338]
## Environment Info

kivy: 1.10.0
pygments: 2.2.0
docutils: 0.14
watchdog: 0.8.3
jedi: 0.10.2
gitpython: 2.1.5
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-10-10.0.15063-SP0
Python: 3.6.0

## Traceback

```
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 663, in mainloop
    self._mainloop()
  File "C:\Program Files\Anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 405, in _mainloop
    EventLoop.idle()
  File "C:\Program Files\Anaconda3\lib\site-packages\kivy\base.py", line 348, in idle
    Clock.tick_draw()
  File "C:\Program Files\Anaconda3\lib\site-packages\kivy\clock.py", line 588, in tick_draw
    self._process_events_before_frame()
  File "kivy\_clock.pyx", line 405, in kivy._clock.CyClockBase._process_events_before_frame (kivy\_clock.c:8381)
  File "kivy\_clock.pyx", line 445, in kivy._clock.CyClockBase._process_events_before_frame (kivy\_clock.c:8255)
  File "kivy\_clock.pyx", line 443, in kivy._clock.CyClockBase._process_events_before_frame (kivy\_clock.c:8176)
  File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (kivy\_clock.c:3490)
  File "C:\Program Files\Anaconda3\lib\site-packages\kivy\uix\boxlayout.py", line 309, in do_layout
    c.size = (w, h)
  File "kivy\properties.pyx", line 478, in kivy.properties.Property.__set__ (kivy\properties.c:5572)
  File "kivy\properties.pyx", line

**Comment by tito** [comment]
The traceback is incomplete so we cannot help. If you have a way to reproduce the issue, please share.

**Comment by knatz-personal** [comment]
The details were gathered automatically by the report feature
This is a new installation and I am just trying to make a test project.
Another crash outputted the following:
`

## Environment Info

kivy: 1.10.0
pygments: 2.2.0
docutils: 0.14
watchdog: 0.8.3
jedi: 0.10.2
gitpython: 2.1.5
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-10-10.0.15063-SP0
Python: 3.6.0

## Traceback

```
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 663, in mainloop
    self._mainloop()
  File "C:\Program Files\Anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 405, in _mainloop
    EventLoop.idle()
  File "C:\Program Files\Anaconda3\lib\site-packages\kivy\base.py", line 348, in idle
    Clock.tick_draw()
  File "C:\Program Files\Anaconda3\lib\site-packages\kivy\clock.py", line 588, in tick_draw
    self._process_events_before_frame()
  File "kivy\_clock.pyx", line 405, in kivy._clock.CyClockBase._process_events_before_frame (kivy\_clock.c:8381)
  File "kivy\_clock.pyx", line 445, in kivy._clock.CyClockBase._process_events_before_frame (kivy\_clock.c:8255)
  File "kivy\_clock.pyx", line 443, in kivy._clock.CyClockBase._process_events_before_frame (kivy\_clock.c:8176)
  File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (kivy\_clock.c:3490)
  File "C:\Program Files\Anaconda3\lib\site-packages\kivy\uix\boxlayout.py", line 309, in do_layout
    c.size = (w, h)
  File "kivy\properties.pyx", line 478, in kivy.properties.Property.__set__ (kivy\properties.c:5572)
  File "kivy\properties.pyx", line 1342, in kivy.properties.ReferenceListProperty.set (kivy\properties.c:21169)
  File "kivy\properties.pyx", line 494, in kivy.properties.Property.set (kivy\properties.c:6520)
  File "kivy\properties.pyx", line 516, in kivy.properties.Property.set (kivy\properties.c:6405)
  File "kivy\properties.pyx", line 571, in kivy.properties.Property.dispatch (kivy\properties.c:7105)
  File "kivy\_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy\_event.c:14035)
  File "kivy\_event.pyx", line 1131, in kivy._event.EventObservers._dispatch (kivy\_event.c:13193)
  File "C:\Program Files\Anaconda3\lib\site-packages\kivy\uix\actionbar.py", line 644, in on_width
    self._layout_group()
  File "C:\Program Files\Anaconda3\lib\site-packages\kivy\uix\actionbar.py", line 538, in _layout_group
    self._clear_all()
  File "C:\Program Files\Anaconda3\lib\site-packages\kivy\uix\actionbar.py", line 501, in _clear_all
    self.clear_widgets()
  File "C:\Program Files\Anaconda3\lib\site-packages\kivy\uix\widget.py", line 605, in clear_widgets
    remove_widget(child)
  File "C:\Program Files\Anaconda3\lib\site-packages\kivy\uix\actionbar.py", line 494, in remove_widget
    self._list_action_items.remove(item)
ValueError: list.remove(x): x not in list

```

End of Traceback


`
