### ISSUE TITLE
Error when moving main window to second screen

### ISSUE THREAD

**Issue by gitjoost** [kivy/kivy-designer#339]
## Environment Info

kivy: 1.10.0
pygments: 2.2.0
docutils: 0.14
watchdog: 0.8.3
jedi: 0.10.2
gitpython: 2.1.5
six: 1.10.0
kivy-garden: 0.1.4

Platform: Darwin-16.7.0-x86_64-i386-64bit
Python: 3.6.1

## Traceback

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 663, in mainloop
    self._mainloop()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 405, in _mainloop
    EventLoop.idle()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/base.py", line 348, in idle
    Clock.tick_draw()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/clock.py", line 588, in tick_draw
    self._process_events_before_frame()
  File "kivy/_clock.pyx", line 405, in kivy._clock.CyClockBase._process_events_before_frame
  File "kivy/_clock.pyx", line 445, in kivy._clock.CyClockBase._process_events_before_frame
  File "kivy/_clock.pyx", line 443, in kivy._clock.CyClockBase._process_events_before_frame
  File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/uix/boxlayout.py", line 309, in do_layout
    c.size = (w, h)
  File "kivy/properties.pyx", line 478, in kivy.properties.Property.__set__
  File "kivy/properties.pyx", line 1342, in kivy.properties.ReferenceListProperty.set
  File "kivy/properties.pyx", line 494, in kivy.properties.Property.set
  File "kivy/properties.pyx", line 516, in kivy.properties.Property.set
  File "kivy/properties.pyx", line 571, in kivy.properties.Property.dispatch
  File "kivy/_event.pyx", line 1225, in kivy._event.EventObservers.dispatch
  File "kivy/_event.pyx", line 1131, in kivy._event.EventObservers._dispatch
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/uix/actionbar.py", line 644, in on_width
    self._layout_group()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/uix/actionbar.py", line 538, in _layout_group
    self._clear_all()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/uix/actionbar.py", line 501, in _clear_all
    self.clear_widgets()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/uix/widget.py", line 605, in clear_widgets
    remove_widget(child)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/uix/actionbar.py", line 494, in remove_widget
    self._list_action_items.remove(item)
ValueError: list.remove(x): x not in list

```

End of Traceback

**Comment by manthansharma** [comment]
Duplicate of #318, Already been fixed in kivy/kivy#5335 and for xpopup FileNotFound Error, xpopup extensions need to be installed, follow the provided installation guidelines fromhttps://github.com/kivy/kivy-designer/blob/master/README.md#installation

**Comment by manthansharma** [comment]
`ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/ky/k_jtpzd92x13ns2njwnsfyk00000gn/T/org.python.python.savedState`

This message appears due to the "application resume" feature in newer versions of OS X. Clearly, this isn't a useful feature for most Python programs (in my case, plotting data with matplotlib), so we can just turn it off with the this command.

```
defaults write org.python.python ApplePersistenceIgnoreState NO
```

For more detail on this issue you can follow up on https://stackoverflow.com/questions/18733965/annoying-message-when-opening-windows-from-python-on-os-x-10-8
