### ISSUE TITLE
Menu Error

### ISSUE THREAD

**Issue by Jack839** [kivy/kivy-designer#341]
## Environment Info

kivy: 1.10.1.dev0
pygments: 2.2.0
docutils: 0.14
watchdog: 0.8.3
jedi: 0.10.2
gitpython: 2.1.5
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-10-10.0.15063
Python: 2.7.12

## Traceback

```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 712, in mainloop
    self._mainloop()
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 457, in _mainloop
    EventLoop.idle()
  File "C:\Python27\lib\site-packages\kivy\base.py", line 340, in idle
    self.dispatch_input()
  File "C:\Python27\lib\site-packages\kivy\base.py", line 325, in dispatch_input
    post_dispatch_input(*pop(0))
  File "C:\Python27\lib\site-packages\kivy\base.py", line 231, in post_dispatch_input
    listener.dispatch('on_motion', etype, me)
  File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "C:\Python27\lib\site-packages\kivy\core\window\__init__.py", line 1327, in on_motion
    self.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "C:\Python27\lib\site-packages\kivy\core\window\__init__.py", line 1363, in on_touch_up
    if w.dispatch('on_touch_up', touch):
  File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "C:\Python27\lib\site-packages\kivy\uix\dropdown.py", line 310, in on_touc

**Comment by manthansharma** [comment]
Hi, Unfortunately, your bug report is not complete. Please, check the bug reporter instructions on how to post the full traceback. You need to post the full message until the "End of Traceback" string.

Thank you for reporting.

**Comment by Jack839** [comment]
That Bug report was send using the built-in option for logging the report....anyway i have posted the whole error now.

**Comment by zeratod** [comment]
I meet the same error.Please tell me how to solve it.
