### ISSUE TITLE
Meet this problem when I install kivy-designer

### ISSUE THREAD

**Issue by xingzheduan** [kivy/kivy-designer#342]
I followed instruction on [https://kivy-designer.readthedocs.io/en/latest/installation.html](https://kivy-designer.readthedocs.io/en/latest/installation.html). But when I input "python -m designer", an error occured. Here is the traceback:
` Traceback (most recent call last):
   File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
     "__main__", mod_spec)
   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File "/home/xzd/pro/kivy-designer/designer/__main__.py", line 3, in <module>
     from designer.app import DesignerApp
   File "/home/xzd/pro/kivy-designer/designer/app.py", line 14, in <module>
     from designer.components.dialogs.add_file import AddFileDialog
   File "/home/xzd/pro/kivy-designer/designer/components/dialogs/add_file.py", line 5, in <module>
     from kivy.garden.xpopup.file import XFileOpen, XFolder
   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 636, in _load_backward_compatible
 KeyError: 'kivy.garden.xpopup'

I don't why because I  followed the instruction step by step.
`

**Comment by spikeo2** [comment]
xpopup is not installed on your system. It seems like the installation process is missing the information for "garden install xpopup". If you just install it by hand, you should be able to start the designer.

**Comment by anfemart** [comment]
Greetings, i have the same problem... how can i just install xpopup by hand??

**Comment by xingzheduan** [comment]
"garden install xpopup ".I suggest you follow the instruction online. Make sure that you have installed the right version of kivy. Hope it's useful for you!

**Comment by anfemart** [comment]
@xingzheduan Thanks for asnwering.. I followed instruction on: http://kivy-designer.readthedocs.io/en/latest/installation.html

and got this:

C:\Users\Andrés Felipe\kivy-designer>garden install xpopup

C:\Users\Andrés Felipe\kivy-designer>python.exe C:\Users\Andrés Felipe\AppData\Local\Programs\Python\Python35\Scripts\garden install xpopup
  File "C:\Users\Andrés", line 1
    ------------------------------------start------------------------------------
                                                                                ^
SyntaxError: invalid syntax

**Comment by drscotthawley** [comment]
@xingzheduan re. 

> "I suggest you follow the instruction online."

  Actually I found this page because I _did_ follow the instructions online, at https://kivy-designer.readthedocs.io/en/latest/installation.html , where there are many dependencies listed but xpopup is not among them.  Even running "pip -Ur requirements.txt" didn't get it.  Perhaps they need to update that document.
