### ISSUE TITLE
Can't start Designer

### ISSUE THREAD

**Issue by spikeo2** [kivy/kivy-designer#344]
Designer can not be started,even though alle requirements are installed.
Start ends in following traceback:

> 
[INFO   ] [Logger      ] Record log in C:\Users\jptas\.kivy\logs\kivy_17-09-20_31.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.4.0 - Build 20.19.15.4642'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 5500'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 4
[INFO   ] [GL          ] Shading version <b'4.40 - Build 20.19.15.4642'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Shader      ] fragment shader: <b"WARNING: 0:7: '' :  #version directive missing">
[INFO   ] [Shader      ] vertex shader: <b"WARNING: 0:7: '' :  #version directive missing">
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[WARNING] [FileNotFoundError] [Errno 2] No such file or directory: 'C:\\Users\\jptas\\.kivy\\garden\\garden.xpopup\\xpopup.mo'. Switch to the defaults.
[INFO   ] [Clipboard   ] Provider: winctypes
 Traceback (most recent call last):
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\site-packages\git\cmd.py", line 599, in execute
     **subprocess_kwargs
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 707, in __init__
     restore_signals, start_new_session)
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 992, in _execute_child
     startupinfo)
 FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
     "__main__", mod_spec)
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File "E:\Programmieren\kivy-designer-master\designer\__main__.py", line 17, in <module>
     main()
   File "E:\Programmieren\kivy-designer-master\designer\__main__.py", line 13, in main
     DesignerApp().run()
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\app.py", line 802, in run
     root = self.build()
   File "E:\Programmieren\kivy-designer-master\designer\app.py", line 1738, in build
     self.root = Designer()
   File "E:\Programmieren\kivy-designer-master\designer\app.py", line 207, in __init__
     super(Designer, self).__init__(**kwargs)
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\floatlayout.py", line 65, in __init__
     super(FloatLayout, self).__init__(**kwargs)
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\widget.py", line 345, in __init__
     Builder.apply(self, ignored_consts=self._kwargs_applied_init)
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\lang\builder.py", line 451, in apply
     self._apply_rule(widget, rule, rule, ignored_consts=ignored_consts)
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\lang\builder.py", line 567, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\lang\builder.py", line 567, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\lang\builder.py", line 567, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\lang\builder.py", line 526, in _apply_rule
     cls = Factory_get(cname)
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\factory.py", line 139, in __getattr__
     module = __import__(name=item['module'], fromlist='.')
   File "E:\Programmieren\kivy-designer-master\designer\tools\git_integration.py", line 23, in <module>
     from git import GitCommandError, RemoteProgress, Repo
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\site-packages\git\__init__.py", line 45, in <module>
     from git.repo import Repo               # @NoMove @IgnorePep8
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\site-packages\git\repo\__init__.py", line 4, in <module>
     from .base import *
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\site-packages\git\repo\base.py", line 31, in <module>     from git.remote import Remote, add_progress, to_progress_instance
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\site-packages\git\remote.py", line 190, in <module>
     class FetchInfo(object):
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\site-packages\git\remote.py", line 219, in FetchInfo
     v = Git().version_info[:2]
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\site-packages\git\cmd.py", line 461, in version_info
     return self._version_info
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\site-packages\git\cmd.py", line 424, in __getattr__
     return LazyMixin.__getattr__(self, name)
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\site-packages\gitdb\util.py", line 256, in __getattr__
     self._set_cache_(attr)
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\site-packages\git\cmd.py", line 444, in _set_cache_
     version_numbers = self._call_process('version').split(' ')[2]
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\site-packages\git\cmd.py", line 877, in _call_process     return self.execute(call, **exec_kwargs)
   File "C:\Users\jptas\AppData\Local\Programs\Python\Python36\lib\site-packages\git\cmd.py", line 602, in execute
     raise GitCommandNotFound(command, err)
 git.exc.GitCommandNotFound: Cmd('git') not found due to: FileNotFoundError('[WinError 2] Das System kann die angegebene Datei nicht finden')
   cmdline: git version

**Comment by Gettyk** [comment]
Same error here: xpopup is installed in the correct folder  `C:\\Users\\xx\\.kivy\\garden\\garden.xpopup\\` but the file `xpopup.mo` doesn't exist. The only file with a `.mo` extension is this folder is `xpopup_ru.mo`.


Here is the full debug. 
```
C:\Users\xx\Desktop\kivy-designer-master>python -m designer
[INFO   ] [Logger      ] Record log in C:\Users\xx\.kivy\logs\kivy_17-09-24_8.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-484b2f7, 20170513
[INFO   ] [Python      ] v3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.5.0 NVIDIA 369.09'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GT 555M/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <b'4.50 NVIDIA'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[WARNING] [FileNotFoundError] [Errno 2] No such file or directory: 'C:\\Users\\Me\\.kivy\\garden\\garden.xpopup\\xpopup.mo'. Switch to the defaults.
[INFO   ] [Clipboard   ] Provider: winctypes
 Traceback (most recent call last):
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\git\cmd.py", line 599, in execute
     **subprocess_kwargs
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 707, in __init__
     restore_signals, start_new_session)
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 990, in _execute_child
     startupinfo)
 FileNotFoundError: [WinError 2] The system cannot find the file specified

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
     "__main__", mod_spec)
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File "C:\Users\xx\Desktop\kivy-designer-master\designer\__main__.py", line 17, in <module>
     main()
   File "C:\Users\xx\Desktop\kivy-designer-master\designer\__main__.py", line 13, in main
     DesignerApp().run()
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\app.py", line 802, in run
     root = self.build()
   File "C:\Users\xx\Desktop\kivy-designer-master\designer\app.py", line 1738, in build
     self.root = Designer()
   File "C:\Users\xx\Desktop\kivy-designer-master\designer\app.py", line 207, in __init__
     super(Designer, self).__init__(**kwargs)
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\floatlayout.py", line 65, in __init__
     super(FloatLayout, self).__init__(**kwargs)
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\widget.py", line 345, in __init__
     Builder.apply(self, ignored_consts=self._kwargs_applied_init)
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\lang\builder.py", line 451, in apply
     self._apply_rule(widget, rule, rule, ignored_consts=ignored_consts)
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\lang\builder.py", line 567, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\lang\builder.py", line 567, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\lang\builder.py", line 567, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\lang\builder.py", line 526, in _apply_rule
     cls = Factory_get(cname)
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\factory.py", line 139, in __getattr__
     module = __import__(name=item['module'], fromlist='.')
   File "C:\Users\xx\Desktop\kivy-designer-master\designer\tools\git_integration.py", line 23, in <module>
     from git import GitCommandError, RemoteProgress, Repo
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\git\__init__.py", line 45, in <module>
     from git.repo import Repo               # @NoMove @IgnorePep8
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\git\repo\__init__.py", line 4, in <module>
     from .base import *
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\git\repo\base.py", line 31, in <module>
     from git.remote import Remote, add_progress, to_progress_instance
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\git\remote.py", line 190, in <module>
     class FetchInfo(object):
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\git\remote.py", line 219, in FetchInfo
     v = Git().version_info[:2]
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\git\cmd.py", line 461, in version_info
     return self._version_info
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\git\cmd.py", line 424, in __getattr__
     return LazyMixin.__getattr__(self, name)
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\gitdb\util.py", line 256, in __getattr__
     self._set_cache_(attr)
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\git\cmd.py", line 444, in _set_cache_
     version_numbers = self._call_process('version').split(' ')[2]
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\git\cmd.py", line 877, in _call_process
     return self.execute(call, **exec_kwargs)
   File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\git\cmd.py", line 602, in execute
     raise GitCommandNotFound(command, err)
 git.exc.GitCommandNotFound: Cmd('git') not found due to: FileNotFoundError('[WinError 2] The system cannot find the file specified')
   cmdline: git version
```

**Comment by manthansharma** [comment]
Both of the above FileNotFoundError is due to git not installed. Refer to following steps to installed git: https://git-scm.com/book/id/v2/Getting-Started-Installing-Git

**Comment by Gettyk** [comment]
Thanks for this! I tried to install git by installing github desktop but it didn't work so I had to install git from http://git-scm.com/download/win

**Comment by nitinphlp** [comment]
Hi, I'm facing this issue and I tried installing GIT from the link mentioned in your post. But still I'm not able to launch the designer. Is there anything else that I should be doing?

By the way, I'm able to launch the installed designer from cmd (python -m designer) without any issues and it runs fine. The error comes when I try to run the app.py in the git repo.
