### ISSUE TITLE
example crashes at startup 

### ISSUE THREAD

**Issue by betidav** [kivy/kivy-designer#348]
## Environment Info

kivy: 1.10.0
pygments: 2.2.0
docutils: 0.14
watchdog: 0.8.3
jedi: 0.11.0
gitpython: 2.1.7
six: 1.11.0
kivy-garden: 0.1.4

Platform: Windows-10-10.0.15063
Python: 2.7.13

## Traceback

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\site-packages\kivy\core\window\window_sdl2.py", line 663, in mainloop
    self._mainloop()
  File "C:\ProgramData\Anaconda2\lib\site-packages\kivy\core\window\window_sdl2.py", line 405, in _mainloop
    EventLoop.idle()
  File "C:\ProgramData\Anaconda2\lib\site-packages\kivy\base.py", line 342, in idle
    self.dispatch_input()
  File "C:\ProgramData\Anaconda2\lib\site-packages\kivy\base.py", line 327, in dispatch_input
    post_dispatch_input(*pop(0))
  File "C:\ProgramData\Anaconda2\lib\site-packages\kivy\base.py", line 233, in post_dispatch_input
    listener.dispatch('on_motion', etype, me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
  File "C:\ProgramData\Anaconda2\lib\site-packages\kivy\core\window\__init__.py", line 1188, in on_motion
    self.dispatch('on_touch_down', me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
  File "C:\ProgramData\Anaconda2\lib\site-packages\kivy\core\window\__init__.py", line 1204, in on_touch_down
    if w.dispatch('on_touch_down', touch):
  File "kivy\_event.pyx", line 71

**Comment by betidav** [comment]
Designer crashes at startup
