### ISSUE TITLE
error

### ISSUE THREAD

**Issue by VladShashkov** [kivy/kivy-designer#349]
## Environment Info

kivy: 1.10.0
pygments: 2.2.0
docutils: 0.15b0.dev0
watchdog: 0.8.3
jedi: 0.11.0
gitpython: 2.1.6
six: 1.11.0
kivy-garden: 0.1.4

Platform: Windows-10-10.0.15063-SP0
Python: 3.6.3

## Traceback

```
Traceback (most recent call last):
  File "C:\Users\vlads_000\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 663, in mainloop
    self._mainloop()
  File "C:\Users\vlads_000\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 405, in _mainloop
    EventLoop.idle()
  File "C:\Users\vlads_000\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\base.py", line 348, in idle
    Clock.tick_draw()
  File "C:\Users\vlads_000\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\clock.py", line 588, in tick_draw
    self._process_events_before_frame()
  File "kivy\_clock.pyx", line 405, in kivy._clock.CyClockBase._process_events_before_frame (kivy\_clock.c:8381)
  File "kivy\_clock.pyx", line 445, in kivy._clock.CyClockBase._process_events_before_frame (kivy\_clock.c:8255)
  File "kivy\_clock.pyx", line 443, in kivy._clock.CyClockBase._process_events_before_frame (kivy\_clock.c:8176)
  File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (kivy\_clock.c:3490)
  File "C:\Users\vlads_000\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\treeview.py", line 454, in _do_layout
    self._do_open_nod

**Comment by manthansharma** [comment]
Hi, Unfortunately, your bug report is not complete. Please, check the bug reporter instructions on how to post the full traceback. You need to post the full message until the "End of Traceback" string.

Thank you for reporting.
