### ISSUE TITLE
Unable to launching Kivy-Designer ("ImportError: Bad git executable.")

### ISSUE THREAD

**Issue by Kingkon963** [kivy/kivy-designer#354]
C:\Python34\kivy-designer>python -m designer
[INFO   ] [Logger      ] Record log in C:\Users\USER\.kivy\logs\kivy_17-11-24_2.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.5.0 - Build 22.20.16.4749'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 630'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <b'4.50 - Build 22.20.16.4749'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Shader      ] fragment shader: <b"WARNING: 0:4: '' :  #version directive missing">
[INFO   ] [Shader      ] vertex shader: <b"WARNING: 0:4: '' :  #version directive missing">
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[WARNING] [FileNotFoundError] [Errno 2] No such file or directory: 'C:\\Users\\USER\\.kivy\\garden\\garden.xpopup\\xpopup.mo'. Switch to the defaults.
[INFO   ] [Clipboard   ] Provider: winctypes
 Traceback (most recent call last):
   File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
     "__main__", mod_spec)
   File "C:\Python34\lib\runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File "C:\Python34\kivy-designer\designer\__main__.py", line 17, in <module>
     main()
   File "C:\Python34\kivy-designer\designer\__main__.py", line 13, in main
     DesignerApp().run()
   File "C:\Python34\lib\site-packages\kivy\app.py", line 802, in run
     root = self.build()
   File "C:\Python34\kivy-designer\designer\app.py", line 1738, in build
     self.root = Designer()
   File "C:\Python34\kivy-designer\designer\app.py", line 207, in __init__
     super(Designer, self).__init__(**kwargs)
   File "C:\Python34\lib\site-packages\kivy\uix\floatlayout.py", line 65, in __init__
     super(FloatLayout, self).__init__(**kwargs)
   File "C:\Python34\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "C:\Python34\lib\site-packages\kivy\uix\widget.py", line 345, in __init__
     Builder.apply(self, ignored_consts=self._kwargs_applied_init)
   File "C:\Python34\lib\site-packages\kivy\lang\builder.py", line 451, in apply
     self._apply_rule(widget, rule, rule, ignored_consts=ignored_consts)
   File "C:\Python34\lib\site-packages\kivy\lang\builder.py", line 567, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "C:\Python34\lib\site-packages\kivy\lang\builder.py", line 567, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "C:\Python34\lib\site-packages\kivy\lang\builder.py", line 567, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "C:\Python34\lib\site-packages\kivy\lang\builder.py", line 526, in _apply_rule
     cls = Factory_get(cname)
   File "C:\Python34\lib\site-packages\kivy\factory.py", line 139, in __getattr__
     module = __import__(name=item['module'], fromlist='.')
   File "C:\Python34\kivy-designer\designer\tools\git_integration.py", line 23, in <module>
     from git import GitCommandError, RemoteProgress, Repo
   File "C:\Python34\lib\site-packages\git\__init__.py", line 82, in <module>
     refresh()
   File "C:\Python34\lib\site-packages\git\__init__.py", line 73, in refresh
     if not Git.refresh(path=path):
   File "C:\Python34\lib\site-packages\git\cmd.py", line 293, in refresh
     raise ImportError(err)
 ImportError: Bad git executable.
 The git executable must be specified in one of the following ways:
     - be included in your $PATH
     - be set via $GIT_PYTHON_GIT_EXECUTABLE
     - explicitly set via git.refresh()

 All git commands will error until this is rectified.

 This initial warning can be silenced or aggravated in the future by setting the
 $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
     - quiet|q|silence|s|none|n|0: for no warning or exception
     - warn|w|warning|1: for a printed warning
     - error|e|raise|r|2: for a raised exception

 Example:
     export GIT_PYTHON_REFRESH=quiet

**Comment by landersaavedra** [comment]
You managed to solve?, because I'm with the same problem

**Comment by Kingkon963** [comment]
Yes, I managed to solve the issue by installing Git on my PC. 
Download it from [here](https://git-scm.com/downloads).
