### ISSUE TITLE
Bug on the startup

### ISSUE THREAD

**Issue by xrt5** [kivy/kivy-designer#355]
## Environment Info

kivy: 1.10.1.dev0
pygments: 2.2.0
docutils: 0.14
watchdog: 0.8.3
jedi: 0.11.0
gitpython: 2.1.7
six: 1.11.0
kivy-garden: 0.1.4

Platform: Windows-10-10.0.16299-SP0
Python: 3.6.3

## Traceback

```
[INFO   ] [Logger      ] Record log in C:\Users\bill\.kivy\logs\kivy_17-12-09_0.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-0456eff, 20171125
[INFO   ] [Python      ] v3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 388.13'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 960/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[WARNING] [FileNotFoundError] [Errno 2] No such file or directory: 'C:\\Users\\bill\\.kivy\\garden\\garden.xpopup\\xpopup.mo'. Switch to the defaults.
[INFO   ] [Clipboard   ] Provider: winctypes
 Traceback (most recent call last):
   File "C:\Users\bill\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
     "__main__", mod_spec)
   File "C:\Users\bill\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File "D:\Downloads\kivy-designer\designer\__main__.py", line 17, in <module>
     main()
   File "D:\Downloads\kivy-designer\designer\__main__.py", line 13, in main
     DesignerApp().run()
   File "C:\Users\bill\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\app.py", line 803, in run
     root = self.build()
   File "D:\Downloads\kivy-designer\designer\app.py", line 1738, in build
     self.root = Designer()
   File "D:\Downloads\kivy-designer\designer\app.py", line 207, in __init__
     super(Designer, self).__init__(**kwargs)
   File "C:\Users\bill\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\floatlayout.py", line 65, in __init__
     super(FloatLayout, self).__init__(**kwargs)
   File "C:\Users\bill\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "C:\Users\bill\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\widget.py", line 345, in __init__
     Builder.apply(self, ignored_consts=self._kwargs_applied_init)
   File "C:\Users\bill\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\lang\builder.py", line 451, in apply
     self._apply_rule(widget, rule, rule, ignored_consts=ignored_consts)
   File "C:\Users\bill\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\lang\builder.py", line 567, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "C:\Users\bill\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\lang\builder.py", line 567, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "C:\Users\bill\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\lang\builder.py", line 567, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "C:\Users\bill\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\lang\builder.py", line 526, in _apply_rule
     cls = Factory_get(cname)
   File "C:\Users\bill\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\factory.py", line 142, in __getattr__
     level=0  # force absolute
   File "D:\Downloads\kivy-designer\designer\tools\git_integration.py", line 23, in <module>
     from git import GitCommandError, RemoteProgress, Repo
   File "C:\Users\bill\AppData\Local\Programs\Python\Python36\lib\site-packages\git\__init__.py", line 82, in <module>
     refresh()
   File "C:\Users\bill\AppData\Local\Programs\Python\Python36\lib\site-packages\git\__init__.py", line 73, in refresh
     if not Git.refresh(path=path):
   File "C:\Users\bill\AppData\Local\Programs\Python\Python36\lib\site-packages\git\cmd.py", line 293, in refresh
     raise ImportError(err)
 ImportError: Bad git executable.
 The git executable must be specified in one of the following ways:
     - be included in your $PATH
     - be set via $GIT_PYTHON_GIT_EXECUTABLE
     - explicitly set via git.refresh()

 All git commands will error until this is rectified.

 This initial warning can be silenced or aggravated in the future by setting the
 $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
     - quiet|q|silence|s|none|n|0: for no warning or exception
     - warn|w|warning|1: for a printed warning
     - error|e|raise|r|2: for a raised exception

 Example:
     export GIT_PYTHON_REFRESH=quiet
```

End of Traceback

**Comment by ClaytonKeu** [comment]
Anyone have a solution to this problem?

**Comment by 2ik** [comment]
+1 
Python: 3.6.5

**Comment by winlock** [comment]
same
winPython 3.6.5 32bit
