### ISSUE TITLE
Error when run 'python -m designer'

### ISSUE THREAD

**Issue by dssantos** [kivy/kivy-designer#362]
## CLI info ##
danilo@dserver:~/Desenvolvimento/kivy_projects/kivy-designer$ python -m designer
[INFO   ] [Logger      ] Record log in /home/danilo/.kivy/logs/kivy_18-02-02_16.txt
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609]
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 12.0.6>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Sandybridge Mobile >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[WARNING] [IOError     ] [Errno 2] No such file or directory: '/home/danilo/.kivy/garden/garden.xpopup/xpopup.mo'. Switch to the defaults.
[INFO   ] [Clipboard   ] Provider: gtk3(['clipboard_dbusklipper'] ignored)
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
[INFO   ] [Cutbuffer   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[WARNING] [Accordion   ] not enough space for displaying all children
[WARNING] [Accordion   ] need 220px, got 100px
[WARNING] [Accordion   ] layout aborted.
[WARNING] [Accordion   ] not enough space for displaying all children
[WARNING] [Accordion   ] need 176px, got 100px
[WARNING] [Accordion   ] layout aborted.
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[WARNING] [Accordion   ] not enough space for displaying all children
[WARNING] [Accordion   ] need 220px, got 100px
[WARNING] [Accordion   ] layout aborted.
[INFO   ] [Base        ] Leaving application in progress...
[INFO   ] [Base        ] Start application main loop
[WARNING] [Accordion   ] not enough space for displaying all children
[WARNING] [Accordion   ] need 176px, got 100px
[WARNING] [Accordion   ] layout aborted.
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[INFO   ] [Base        ] Leaving application in progress...
 Exception KeyError: (2030,) in <functools.partial object at 0x7f3d82b29e68> ignored
 Exception KeyError: (2214,) in <functools.partial object at 0x7f3d82af3890> ignored
 Exception KeyError: (2256,) in <functools.partial object at 0x7f3d82ac12b8> ignored
 Exception KeyError: (2298,) in <functools.partial object at 0x7f3d82642260> ignored
 Exception KeyError: (3029,) in <functools.partial object at 0x7f3d824182b8> ignored
 Exception KeyError: (3215,) in <functools.partial object at 0x7f3d822d5578> ignored
 Exception KeyError: (3401,) in <functools.partial object at 0x7f3d82190838> ignored

## Environment Info

kivy: 1.10.0
pygments: 2.2.0
docutils: 0.14
watchdog: 0.8.3
jedi: 0.11.1
gitpython: 2.1.8
six: 1.11.0
kivy-garden: 0.1.4

Platform: Linux-4.8.0-36-generic-x86_64-with-Ubuntu-16.04-xenial
Python: 2.7.12

## Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 663, in mainloop
    self._mainloop()
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 405, in _mainloop
    EventLoop.idle()
  File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 348, in idle
    Clock.tick_draw()
  File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 588, in tick_draw
    self._process_events_before_frame()
  File "kivy/_clock.pyx", line 405, in kivy._clock.CyClockBase._process_events_before_frame (kivy/_clock.c:8093)
  File "kivy/_clock.pyx", line 445, in kivy._clock.CyClockBase._process_events_before_frame (kivy/_clock.c:7965)
  File "kivy/_clock.pyx", line 443, in kivy._clock.CyClockBase._process_events_before_frame (kivy/_clock.c:7887)
  File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (kivy/_clock.c:3211)
  File "/usr/lib/python2.7/dist-packages/kivy/uix/boxlayout.py", line 309, in do_layout
    c.size = (w, h)
  File "kivy/properties.pyx", line 478, in kivy.properties.Property.__set__ (kivy/properties.c:5171)
  File "kivy/properties.pyx", line 1342, in kivy.properties.ReferenceListProperty.set (kivy/properties.c:20421)
  File "kivy/properties.pyx", line 494, in kivy.properties.Property.set (kivy/properties.c:6054)
  File "kivy/properties.pyx", line 516, in kivy.properties.Property.set (kivy/properties.c:5933)
  File "kivy/properties.pyx", line 571, in kivy.properties.Property.dispatch (kivy/properties.c:6614)
  File "kivy/_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy/_event.c:13524)
  File "kivy/_event.pyx", line 1131, in kivy._event.EventObservers._dispatch (kivy/_event.c:12723)
  File "/usr/lib/python2.7/dist-packages/kivy/uix/actionbar.py", line 644, in on_width
    self._layout_group()
  File "/usr/lib/python2.7/dist-packages/kivy/uix/actionbar.py", line 538, in _layout_group
    self._clear_all()
  File "/usr/lib/python2.7/dist-packages/kivy/uix/actionbar.py", line 501, in _clear_all
    self.clear_widgets()
  File "/usr/lib/python2.7/dist-packages/kivy/uix/widget.py", line 605, in clear_widgets
    remove_widget(child)
  File "/usr/lib/python2.7/dist-packages/kivy/uix/actionbar.py", line 494, in remove_widget
    self._list_action_items.remove(item)
ValueError: list.remove(x): x not in list

```

End of Traceback

**Comment by manthansharma** [comment]
Duplicate of #318
