### ISSUE TITLE
Error when opening Project Settings

### ISSUE THREAD

**Issue by danmattsson** [kivy/kivy-designer#366]
## Environment Info

kivy: 1.10.1.dev0
pygments: 2.2.0
docutils: 0.14
watchdog: 0.8.3
jedi: 0.11.1
gitpython: 2.1.8
six: 1.11.0
kivy-garden: 0.1.4

Platform: Darwin-17.4.0-x86_64-i386-64bit
Python: 3.6.4

## Traceback

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 723, in mainloop
    self._mainloop()
  File "/usr/local/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 460, in _mainloop
    EventLoop.idle()
  File "/usr/local/lib/python3.6/site-packages/kivy/base.py", line 340, in idle
    self.dispatch_input()
  File "/usr/local/lib/python3.6/site-packages/kivy/base.py", line 325, in dispatch_input
    post_dispatch_input(*pop(0))
  File "/usr/local/lib/python3.6/site-packages/kivy/base.py", line 231, in post_dispatch_input
    listener.dispatch('on_motion', etype, me)
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "/usr/local/lib/python3.6/site-packages/kivy/core/window/__init__.py", line 1349, in on_motion
    self.dispatch('on_touch_up', me)
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "/usr/local/lib/python3.6/site-packages/kivy/core/window/__init__.py", line 1385, in on_touch_up
    if w.dispatch('on_touch_up', touch):
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "/usr/local/lib/python3.6/site-packages/kivy/uix/dropdown.py", line 310, in on_touch_up
    if super(DropDown, self).on_touch_up(touch):
  File "/usr/local/lib/python3.6/site-packages/kivy/uix/scrollview.py", line 848, in on_touch_up
    if self.dispatch('on_scroll_stop', touch):
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "/usr/local/lib/python3.6/site-packages/kivy/uix/scrollview.py", line 887, in on_scroll_stop
    self.simulate_touch_down(touch)
  File "/usr/local/lib/python3.6/site-packages/kivy/uix/scrollview.py", line 607, in simulate_touch_down
    ret = super(ScrollView, self).on_touch_down(touch)
  File "/usr/local/lib/python3.6/site-packages/kivy/uix/widget.py", line 460, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "/usr/local/lib/python3.6/site-packages/kivy/uix/widget.py", line 460, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "/usr/local/lib/python3.6/site-packages/kivy/uix/behaviors/button.py", line 151, in on_touch_down
    self.dispatch('on_press')
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "/Users/dan/Source/kivy-designer/designer/uix/action_items.py", line 183, in on_press
    self.cont_menu.dismiss()
AttributeError: 'NoneType' object has no attribute 'dismiss'

```

End of Traceback

**Comment by danmattsson** [comment]
Seems like a duplicate of #363
