### ISSUE TITLE
Abnormal exit

### ISSUE THREAD

**Issue by azluck** [kivy/kivy-designer#373]
## Environment Info

Pip is not installed

## Traceback

```
Traceback (most recent call last):
  File "D:\Python35\lib\site-packages\kivy\core\window\window_sdl2.py", line 663, in mainloop
    self._mainloop()
  File "D:\Python35\lib\site-packages\kivy\core\window\window_sdl2.py", line 602, in _mainloop
    self.modifiers):
  File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8146)
  File "kivy\_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy\_event.c:14035)
  File "kivy\_event.pyx", line 1149, in kivy._event.EventObservers._dispatch (kivy\_event.c:13564)
  File "D:\Python35\lib\site-packages\kivy\core\window\__init__.py", line 159, in _on_window_key_down
    return self.dispatch('on_key_down', keycode, text, modifiers)
  File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8146)
  File "kivy\_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy\_event.c:14035)
  File "kivy\_event.pyx", line 1149, in kivy._event.EventObservers._dispatch (kivy\_event.c:13564)
  File "D:\Python35\lib\site-packages\kivy\uix\textinput.py", line 2404, in keyboard_on_key_down
    self.copy()
  File "D:\Python35\lib\site-packages\kivy\uix\textinput.py", line 1712, in copy
    return Clipboard.copy(self.selection_text)
  File "D:\Python35\lib\site-packages\kivy\core\clipboard\__init__.py", line 73, in copy
    self._copy(data)
  File "D:\Python35\lib\site-packages\kivy\core\clipboard\__init__.py", line 87, in _copy
    self.put(data, self._clip_mime_type)
  File "D:\Python35\lib\site-packages\kivy\core\clipboard\clipboard_winctypes.py", line 55, in put
    msvcrt.wcscpy_s(c_wchar_p(hCd), len(text), c_wchar_p(text))
ValueError: embedded null character

```

End of Traceback

**Comment by shahrukh1514** [comment]
I too have experienced similar issue when using keyboard shortcut of copying text from kv editor
