### ISSUE TITLE
error while executing for first time

### ISSUE THREAD

**Issue by amrithmmh** [kivy/kivy-designer#388]
i installed kivy and checked if all the requirements are met
i get this error 
Traceback (most recent call last):
   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
     "__main__", fname, loader, pkg_name)
   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
     exec code in run_globals
   File "/home/novatek/kivy-designer/designer/__main__.py", line 3, in <module>
     from designer.app import DesignerApp
   File "designer/app.py", line 11, in <module>
     from designer.components.buildozer_spec_editor import BuildozerSpecEditor
   File "designer/components/buildozer_spec_editor.py", line 19, in <module>
     from pygments.lexers.configs import IniLexer
 ImportError: No module named pygments.lexers.configs

using lubuntu latest stable

**Comment by AlexanderUsselmann** [comment]
same on macOS High Sierra 10.13.6

> [INFO   ] [Logger      ] Record log in /Applications/Kivy3.app/Contents/Resources/.kivy/logs/kivy_18-07-31_11.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.6.5 (default, Jun 18 2018, 16:36:13) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'2.1 INTEL-10.36.19'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) Iris(TM) Graphics 540'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "/Applications/Kivy3.app/Contents/Frameworks/python/3.6.5/lib/python3.6/runpy.py", line 193, in _run_module_as_main
     "__main__", mod_spec)
   File "/Applications/Kivy3.app/Contents/Frameworks/python/3.6.5/lib/python3.6/runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File "designer/__main__.py", line 3, in <module>
     from designer.app import DesignerApp
   File "/Users/xxxxxxxxxxx/Downloads/kivy-designer-master/designer/app.py", line 11, in <module>
     from designer.components.buildozer_spec_editor import BuildozerSpecEditor
   File "/Users/xxxxxxxxxxx/Downloads/kivy-designer-master/designer/components/buildozer_spec_editor.py", line 19, in <module>
     from pygments.lexers.configs import IniLexer
 ModuleNotFoundError: No module named 'pygments'

>
