### ISSUE TITLE
Cannot add <designer.uix.designer_action_items.DesignerActionButton object

### ISSUE THREAD

**Issue by areben** [kivy/kivy-designer#61]
````
[INFO   ] Kivy v1.8.0
[INFO   ] [Logger      ] Record log in /home/areben/.kivy/logs/kivy_15-01-04_4.txt
[INFO   ] [Factory     ] 157 symbols loaded
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=Nones
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60s
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=Nones
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif 
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60s
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600s
[DEBUG  ] [Window      ] Ignored <egl_rpi> (import error)
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[DEBUG  ] [Window      ] Display driver x11
[DEBUG  ] [Window      ] Actual window size: 800x600
[DEBUG  ] [Window      ] Actual color bits r8 g8 b8 a8
[DEBUG  ] [Window      ] Actual depth bits: 24
[DEBUG  ] [Window      ] Actual stencil bits: 8
[DEBUG  ] [Window      ] Actual multisampling samples: 4
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 10.1.3>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Haswell Mobile >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <32>
[DEBUG  ] [Shader      ] Fragment compiled successfully
[DEBUG  ] [Shader      ] Vertex compiled successfully
[DEBUG  ] [ImagePygame ] Load </usr/lib/python2.7/dist-packages/kivy/data/glsl/default.png>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: pygame
[WARNING] Call to deprecated function __call__ in /usr/lib/python2.7/dist-packages/kivy/utils.py line 246.Called from /home/areben/.kivy/garden/garden.filebrowser/__init__.py line 80 by <module>().
[DEBUG  ] [Cache       ] register <kv.loader> with limit=500, timeout=60s
[INFO   ] [Loader      ] using a thread pool of 2 workers
[DEBUG  ] [Cache       ] register <textinput.label> with limit=None, timeout=60.0s
[DEBUG  ] [Cache       ] register <textinput.width> with limit=None, timeout=60.0s
[INFO   ] [Clipboard   ] Provider: pygame
[DEBUG  ] [App         ] Loading kv </home/areben/Dropbox/Code/python/kivy-designer/designer/designer.kv>
[DEBUG  ] [Atlas       ] Load </usr/lib/python2.7/dist-packages/kivy/data/../data/images/defaulttheme.atlas>
[DEBUG  ] [Atlas       ] Need to load 1 images
[DEBUG  ] [Atlas       ] Load </usr/lib/python2.7/dist-packages/kivy/data/../data/images/defaulttheme-0.png>
[DEBUG  ] [ImagePygame ] Load </usr/lib/python2.7/dist-packages/kivy/data/../data/images/defaulttheme-0.png>
[DEBUG  ] [ImagePygame ] Load </usr/lib/python2.7/dist-packages/kivy/data/../data/logo/kivy-icon-32.png>
[INFO   ] [OSC         ] using <multiprocessing> for socket
[DEBUG  ] [Base        ] Create provider from mouse
[DEBUG  ] [Base        ] Create provider from probesysfs
[DEBUG  ] [ProbeSysfs  ] using probsysfs!
[DEBUG  ] [ProbeSysfs  ] found device: ELAN Touchscreen at /dev/input/event12
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event12
[INFO   ] [MTD         ] Read event from </dev/input/event12>
[DEBUG  ] [ProbeSysfs  ] found device: ETPS/2 Elantech Touchpad at /dev/input/event6
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event6
[INFO   ] [MTD         ] Read event from </dev/input/event6>
[INFO   ] [Base        ] Start application main loop
[INFO   ] [MTD         ] </dev/input/event12> range position X is 0 - 3776
[INFO   ] [MTD         ] </dev/input/event6> range position X is 0 - 3097
[INFO   ] [MTD         ] </dev/input/event12> range position Y is 0 - 2112
[INFO   ] [MTD         ] </dev/input/event6> range position Y is 0 - 1956
[INFO   ] [MTD         ] </dev/input/event12> range touch major is 0 - 255
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [MTD         ] </dev/input/event6> range touch major is 0 - 2445
[INFO   ] [MTD         ] </dev/input/event12> range touch minor is 0 - 255
[INFO   ] [MTD         ] </dev/input/event6> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event12> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event6> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event12> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event6> axes invertion: X is 0, Y is 0
[WARNING] [Accordion   ] not enough space for displaying all children
[WARNING] [Accordion   ] need 220px, got 100px
[WARNING] [Accordion   ] layout aborted.
[WARNING] [Accordion   ] not enough space for displaying all children
[WARNING] [Accordion   ] need 176px, got 100px
[WARNING] [Accordion   ] layout aborted.
[WARNING] [Accordion   ] not enough space for displaying all children
[WARNING] [Accordion   ] need 220px, got 100px
[WARNING] [Accordion   ] layout aborted.
[WARNING] [Accordion   ] not enough space for displaying all children
[WARNING] [Accordion   ] need 220px, got 100px
[WARNING] [Accordion   ] layout aborted.
[DEBUG  ] [Window      ] Display driver x11
[DEBUG  ] [Window      ] Actual window size: 2601x1683
[DEBUG  ] [Window      ] Actual color bits r8 g8 b8 a8
[DEBUG  ] [Window      ] Actual depth bits: 24
[DEBUG  ] [Window      ] Actual stencil bits: 8
[DEBUG  ] [Window      ] Actual multisampling samples: 4
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "main.py", line 3, in <module>
     DesignerApp().run()
   File "/usr/lib/python2.7/dist-packages/kivy/app.py", line 792, in run
     runTouchApp()
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 481, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_pygame.py", line 381, in mainloop
     self._mainloop()
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_pygame.py", line 287, in _mainloop
     EventLoop.idle()
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 330, in idle
     Clock.tick_draw()
   File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 429, in tick_draw
     self._process_events_before_frame()
   File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 562, in _process_events_before_frame
     if event.tick(self._last_tick) is False:
   File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 309, in tick
     ret = callback(self._dt)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/boxlayout.py", line 175, in do_layout
     c.width = w
   File "properties.pyx", line 345, in kivy.properties.Property.__set__ (kivy/properties.c:3589)
   File "properties.pyx", line 377, in kivy.properties.Property.set (kivy/properties.c:4064)
   File "properties.pyx", line 431, in kivy.properties.Property.dispatch (kivy/properties.c:4657)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/actionbar.py", line 548, in on_width
     self._layout_all()
   File "/usr/lib/python2.7/dist-packages/kivy/uix/actionbar.py", line 442, in _layout_all
     group.show_group()
   File "/usr/lib/python2.7/dist-packages/kivy/uix/actionbar.py", line 272, in show_group
     self._dropdown.add_widget(item)
   File "/home/areben/Dropbox/Code/python/kivy-designer/designer/uix/contextual.py", line 307, in add_widget
     self.container.add_widget(widget, index)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/layout.py", line 78, in add_widget
     return super(Layout, self).add_widget(widget, index)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/widget.py", line 344, in add_widget
     % (widget, parent))
 kivy.uix.widget.WidgetException: Cannot add <designer.uix.designer_action_items.DesignerActionButton object at 0x7fae08c794c8>, it already has a parent <kivy.uix.gridlayout.GridLayout object at 0x7fae05592ae0>
````

**Comment by gopar** [comment]
@areben Had the same error except it only occurred to me when I shrunk the window to a certain size. I solved the issue by deleting the config.ini file. For example i'm on linux, and my config.ini is in the path: 
/home/daniel/.config/designer/.kivy-designer/config.ini 
After deleting that and restarting KD, everything worked again. Not sure if that will help.

**Comment by dkollmann** [comment]
Any news on this one? I have the same problem, strangely only under Mac OS X. The Windows version works fine.

**Comment by aron-bordin** [comment]
Hi @dkollmann ,
I fixed this problem, it'll be available soon. You can check this branch: https://github.com/aron-bordin/kivy-designer/tree/pr_organized or just remove the config.ini and run kivy designer.

**Comment by dkollmann** [comment]
Thanks for the info. I am already using your fork of kivy-designer.
Would you recommend I work from the pr_organized branch instead of master?

**Comment by aron-bordin** [comment]
I'm a GSOC student, and I have some branches with new features/bug fixes. This bug was fixed in this pr_organized branch. 
My master is equals to kivy/kivy-designer/master, so yes, try to use pr_organized

**Comment by dkollmann** [comment]
Okay, thank you very much for your effort :)

Should I fix some issues myself, I will share them with your guys.

Thanks again.

**Comment by tshirtman** [comment]
Had the same issue, this branch indeed solves the issue, i didn't check other differences yet, but if it makes the project usable, maybe it should be merged.

**Comment by pierre3401** [comment]
I'm under ubuntu 15.04...
I already deleted the config.ini but it does not work

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_pygame.py", line 381, in mainloop
    self._mainloop()
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_pygame.py", line 285, in _mainloop
    EventLoop.idle()
  File "/usr/local/lib/python2.7/dist-packages/kivy/base.py", line 333, in idle
    Clock.tick_draw()
  File "/usr/local/lib/python2.7/dist-packages/kivy/clock.py", line 490, in tick_draw
    self._process_events_before_frame()
  File "/usr/local/lib/python2.7/dist-packages/kivy/clock.py", line 640, in _process_events_before_frame
    event.tick(self._last_tick, remove)
  File "/usr/local/lib/python2.7/dist-packages/kivy/clock.py", line 374, in tick
    ret = callback(self._dt)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/boxlayout.py", line 174, in do_layout
    c.width = w
  File "kivy/properties.pyx", line 377, in kivy.properties.Property.__set__ (kivy/properties.c:4351)
  File "kivy/properties.pyx", line 409, in kivy.properties.Property.set (kivy/properties.c:4866)
  File "kivy/properties.pyx", line 460, in kivy.properties.Property.dispatch (kivy/properties.c:5442)
  File "kivy/_event.pyx", line 1055, in kivy._event.EventObservers.dispatch (kivy/_event.c:10974)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/actionbar.py", line 564, in on_width
    self._layout_group()
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/actionbar.py", line 469, in _layout_group
    group.show_group()
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/actionbar.py", line 272, in show_group
    self._dropdown.add_widget(item)
  File "/home/brp/kivy-designer/designer/uix/contextual.py", line 325, in add_widget
    self.container.add_widget(widget, index)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/layout.py", line 81, in add_widget
    return super(Layout, self).add_widget(widget, index)
  File "/usr/local/lib/python2.7/dist-packages/kivy/uix/widget.py", line 454, in add_widget
    % (widget, parent))
WidgetException: Cannot add <designer.uix.designer_action_items.DesignerActionButton object at 0x7f69641567a0>, it already has a parent <kivy.uix.gridlayout.GridLayout object at 0x7f6961241a10>

**Comment by aron-bordin** [comment]
Hi @pierre3401 
I'll try to provide the fix asap. This problem is usually caused when the Kivy Designer window is smaller than 800x600. It's a bug in the master version, where the actionbar cannot be hidden in smaller window.

Tries to restore this default config: https://raw.githubusercontent.com/kivy/kivy-designer/master/config.ini
If you still getting the error, increase the 

    window_width = 800
    window_height = 600

values.

Hope this helps :)

**Comment by dessant** [comment]
@aron-bordin we could start the app in a maximized state, there's the `window_state` config option.

**Comment by aron-bordin** [comment]
@dessant there is an option on KD to restore KD with the last window size. 

This bug is fixed on master, if something similar persists, please, open a new issue or re-open it.

Thank you everyone :)
