### ISSUE TITLE
Getting ImportError: No module named watchdog.events

### ISSUE THREAD

**Issue by Tkizzy** [kivy/kivy-designer#62]
Traceback (most recent call last):
   File "/Users/anty/Downloads/kivy-designer-master/main.py", line 2, in <module>
     from designer.app import DesignerApp
   File "/Users/anty/Downloads/kivy-designer-master/designer/app.py", line 34, in <module>
     from designer.project_loader import ProjectLoader, ProjectLoaderException
   File "/Users/anty/Downloads/kivy-designer-master/designer/project_loader.py", line 23, in <module>
     from designer.proj_watcher import ProjectWatcher
   File "/Users/anty/Downloads/kivy-designer-master/designer/proj_watcher.py", line 5, in <module>
     from watchdog.events import FileSystemEventHandler
 ImportError: No module named watchdog.events
[Finished in 0.9s with exit code 1]
[cmd: ['/usr/local/bin/kivy', '-u', '/Users/anty/Downloads/kivy-designer-master/main.py']]
[dir: /Users/anty/Downloads/kivy-designer-master]
[path: /usr/bin:/bin:/usr/sbin:/sbin]

On OS X Yosemite 10.10.2, Python 2.7

**Comment by auvipy** [comment]
you installed watchdog ?

**Comment by Sentient07** [comment]
@Tkizzy do
$pip install watchdog
and if there are any further import errors, try doing the similar  :)

**Comment by Sentient07** [comment]
@tito : IMO, this issue can be closed :)

**Comment by kived** [comment]
No response from the OP. Make sure that watchdog is installed in the Kivy package - I believe that installing it to the system won't work on OS X.
