### ISSUE TITLE
import error: kivy

### ISSUE THREAD

**Issue by YK2** [kivy/kivy-designer#66]
PS C:\Users\Administrator\kivy-designer-master> python main.py
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from designer.app import DesignerApp
  File "C:\Users\Administrator\kivy-designer-master\designer\app.py", line 3, in <module>
    import kivy
ImportError: No module named kivy

server 2012 r2 update 1 all dependencies are installed using pip including kivy, not sure what i am doing wrong ?

hopefully one of you guys can shed some light on it for me.

tnx

**Comment by YK2** [comment]
sorted this myself, it was my mistake as i was not pip installing the file browser correctly using kivy.bat
